% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  a4paper,
]{book}
\usepackage{xcolor}
\usepackage[top=2.5cm,bottom=2.5cm,left=2.5cm,right=2.5cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{xcolor}
\definecolor{isublue}{RGB}{30,56,100}
\definecolor{accent}{RGB}{46,117,182}
\definecolor{darkgrey}{RGB}{80,80,80}
\renewcommand{\maketitle}{}
\newcommand{\doop}{\operatorname{do}}
\newcommand{\indep}{\perp\!\!\!\perp}
\newcommand{\nindep}{\mathrel{\not\!\perp\!\!\!\perp}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Gcal}{\mathcal{G}}
\newcommand{\Pa}{\mathrm{Pa}}
\newcommand{\De}{\mathrm{De}}
\newcommand{\An}{\mathrm{An}}
\newcommand{\Nd}{\mathrm{Nd}}
\newcommand{\pto}{\overset{p}{\to}}
\newcommand{\expit}{\operatorname{expit}}
\AtBeginDocument{%
  \begin{titlepage}
    \centering
    \vspace*{3cm}
    {\Huge\bfseries\color{isublue}
      Theory and Methods in Causal Inference}\\[1.2cm]
    {\LARGE\color{accent} Lecture Notes}\\[0.8cm]
    \color{accent}\rule{0.6\textwidth}{1.2pt}\\[0.8cm]
    {\large Jae Kwang Kim \\[0.3cm]
      Department of Statistics\\[0.3cm]
      Iowa State University}\\[2cm]
    {\normalsize STAT 5900B}\\[0.8cm]
    {\normalsize\color{darkgrey} Last updated: \today}\\[0.3cm]
    \vfill
  \end{titlepage}
  \tableofcontents
  \newpage
}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Theory and Methods in Causal Inference},
  pdfauthor={Jae-kwang Kim},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Theory and Methods in Causal Inference}
\author{Jae-kwang Kim}
\date{2026-04-10}
\begin{document}
\frontmatter
\maketitle


\mainmatter
\bookmarksetup{startatroot}

\chapter*{Preface}\label{preface}
\addcontentsline{toc}{chapter}{Preface}

\markboth{Preface}{Preface}

These lecture notes accompany the graduate course \textbf{STAT 5900B:
Theory and Methods in Causal Inference} at the Department of Statistics,
Iowa State University.

The course targets graduate students in statistics. It assumes
familiarity with probability theory, mathematical statistics, and linear
models at the level of a graduate sequence, but no prior exposure to
causal inference.

📄 \href{Theory-and-Methods-in-Causal-Inference.pdf}{Download full PDF}

\section*{Organization}\label{organization}
\addcontentsline{toc}{section}{Organization}

\markright{Organization}

The notes are organized in four parts.

\textbf{Part I --- Foundations} (Chapters 1--4) builds the graphical and
conceptual foundation: the causal trinity (SEM, DAG, potential
outcomes), DAGs and d-separation, the do-calculus and identification
criteria, and the connection between potential outcomes and the
do-calculus.

\textbf{Part II --- Identification} (Chapters 5--8) bridges the
graphical framework and observed data: randomization and back-door
adjustment, propensity score methods, instrumental variables, and
mediation and front-door identification.

\textbf{Part III --- Estimation} (Chapters 9--12) covers semiparametric
efficiency theory: estimating equations and influence functions, doubly
robust estimation, flexible nuisance estimation with cross-fitting, and
estimation under instrumental variables.

\textbf{Part IV --- Policy Learning and Sequential Decision Making}
(Chapters 13--15) covers policy evaluation, optimal policy learning, and
dynamic treatment regimes.

\section*{Notation}\label{notation}
\addcontentsline{toc}{section}{Notation}

\markright{Notation}

Throughout these notes:

\begin{itemize}
\tightlist
\item
  \(\doop(T = t)\) denotes the do-operator (intervention).
\item
  \(Y(t)\) denotes the potential outcome under \(T = t\).
\item
  \(\E[\,\cdot\,]\) denotes expectation; \(\indep\) denotes conditional
  independence.
\item
  \(\mathcal{G}\) denotes a DAG; \(\mathcal{G}_T\) denotes the mutilated
  graph after intervening on \(T\).
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Introduction}\label{introduction}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Learning Objectives}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

By the end of this chapter, students should be able to:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Articulate the distinction between an interventional distribution
  \(f(y \mid \doop(T{=}t))\) and an observational conditional
  distribution \(f(y \mid T{=}t)\), and explain why they differ whenever
  \(T\) is endogenous.
\item
  Describe the same causal question in all three languages --- SEM, DAG
  graph surgery, and potential outcomes --- and begin to translate
  between them.
\item
  Derive the two densities explicitly in the Gaussian linear confounded
  model, and identify the endogeneity bias
  \(\alpha\gamma\sigma_U^2/\sigma_T^2\) as the gap between them.
\item
  State the two-step paradigm (identification then estimation) and
  locate each step in the causal inference pipeline.
\item
  Distinguish the IV DAG from the mediation DAG and explain why
  conflating an instrument with a mediator leads to identification
  failure.
\end{enumerate}

\end{tcolorbox}

This chapter is an orientation, not a complete treatment. It introduces
four ideas --- the interventional/observational distinction, the causal
trinity, the Gaussian confounded model as a running example, and the
identification-versus-estimation paradigm --- that will be developed
rigorously in Chapters 2--4 and beyond. After one reading, students
should have a map of the territory; the details will become clear as the
course proceeds.

\section{Motivation: Why Causal Inference Is
Hard}\label{motivation-why-causal-inference-is-hard}

Causal inference studies when and how the observational distribution can
be used to recover the distribution that would arise under
interventions.

\subsection{The Central Question}\label{the-central-question}

Causal inference is concerned with a deceptively simple question: what
would happen to \(Y\) if we were to \emph{set} \(T = t\)? This is
fundamentally different from the question that standard statistical
procedures answer: what is the distribution of \(Y\) among units
\emph{observed} to have \(T = t\)?

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Interventional vs.~Observational Distribution}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\begin{itemize}
\tightlist
\item
  The \emph{interventional distribution} \(f(y \mid \doop(T{=}t))\) is
  the distribution of \(Y\) in a hypothetical world where \(T\) has been
  \emph{externally set} to \(t\), regardless of the usual
  data-generating mechanism for \(T\).
\item
  The \emph{observational conditional distribution} \(f(y \mid T{=}t)\)
  is the distribution of \(Y\) among the subpopulation of units for whom
  \(T = t\) was \emph{observed} to hold.
\end{itemize}

These two distributions coincide only when \(T\) is randomized
(exogenous). In all other cases they differ, and the difference is
\emph{endogeneity bias}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Exogeneity and Endogeneity}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Suppose the outcome is generated by the structural equation
\[Y = f_Y(T, X, U),\] where \(T\) is the treatment, \(X\) are observed
covariates, and \(U\) represents unobserved common causes of \(T\) and
\(Y\) (confounders).

\begin{itemize}
\tightlist
\item
  The treatment \(T\) is \emph{exogenous given \(X\)} if
  \(T \indep U \mid X\).
\item
  The treatment \(T\) is \emph{endogenous given \(X\)} if
  \(T \not\indep U \mid X\), so that some unobserved variable \(U\)
  affects both \(T\) and \(Y\).
\end{itemize}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Drug Trial with Unmeasured Severity}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Does a new drug (\(T=1\)) reduce blood pressure (\(Y\))? Suppose sicker
patients are more likely to take the drug, so that unmeasured severity
\(U\) is a common cause of \(T\) and \(Y\). Then:

\begin{itemize}
\tightlist
\item
  \emph{Observational study}: \(\E[Y \mid T{=}1] > \E[Y \mid T{=}0]\).
  Drug users have higher blood pressure on average. A naïve analyst
  concludes the drug is harmful.
\item
  \emph{Randomized trial}:
  \(\E[Y \mid \doop(T{=}1)] < \E[Y \mid \doop(T{=}0)]\). Forcing
  everyone to take the drug reduces blood pressure. The drug is
  beneficial.
\end{itemize}

Same data. Different questions. Opposite answers. The entire discrepancy
is caused by the back-door path \(T \leftarrow U \to Y\), which the
observational quantity \(\E[Y \mid T{=}1]\) cannot remove.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-warning-color!10!white, colframe=quarto-callout-warning-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={The Fundamental Problem of Causal Inference}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

We observe \(f(y \mid T{=}t)\) directly from data. We want
\(f(y \mid \doop(T{=}t))\). The goal of \emph{identification theory} is
to find conditions under which the former can be used to recover the
latter.

\end{tcolorbox}

\section{The Causal Trinity: Three Languages for One
Idea}\label{the-causal-trinity-three-languages-for-one-idea}

The same causal question --- what happens when we set \(T = t\)? --- can
be expressed in three distinct but equivalent languages. Collectively,
we call these the \textbf{causal trinity}: the \emph{structural equation
model} (SEM), the \emph{directed acyclic graph} (DAG) with graph
surgery, and the \emph{potential outcomes} framework. Each member of the
trinity illuminates a different facet of the same underlying idea, and
fluency in all three is essential for modern causal reasoning.
Figure~\ref{fig-trinity} depicts their relationships.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-trinity-1.pdf}}

}

\caption{\label{fig-trinity}The \textbf{causal trinity}: three languages
that express the same causal question from different vantage points.
Potential outcomes define \emph{what} we want to estimate; the DAG with
graph surgery specifies \emph{how} to identify it from observed data;
the SEM provides the \emph{generative mechanism} for likelihood
construction. Double-headed arrows show the translation assumptions
connecting adjacent languages. All three converge on the same central
question (ellipse).}

\end{figure}%

\subsection{Language 1: Structural Equation
Models}\label{language-1-structural-equation-models}

A structural equation model (SEM) represents the causal data-generating
mechanism as a system of equations, one per variable, together with a
joint distribution over exogenous errors.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Structural Equation Model (SEM)}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A recursive SEM over variables \((U, T, Y)\) is a system
\[U \sim p(u), \qquad T = f_T(U, Z, \delta), \qquad Y = f_Y(T, U, \varepsilon),\]
where \(\delta\) and \(\varepsilon\) are mutually independent exogenous
disturbances, \(Z\) is an observed instrument, and \(U\) is an
unobserved confounder.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark: Error Independence in the NPSEM-IE}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

The assumption that the disturbances \(\delta\) and \(\varepsilon\) are
\emph{mutually independent} is a substantive restriction, not merely a
technical convenience. Because \(U\) is unobserved and enters both
\(f_T\) and \(f_Y\), error independence does not remove the dependence
between \(T\) and \(Y(t)\) induced by \(U\); it restricts only the
additional channel of dependence running through the equation-specific
errors \((\delta, \varepsilon)\). Richardson and Robins (2014) call SEMs
with this structure \emph{Nonparametric Structural Equation Models with
Independent Errors} (NPSEM-IEs).

These notes adopt the NPSEM-IE framework throughout for two practical
reasons: error independence ensures the DAG's Markov condition holds,
making the Markov factorization of the joint density immediate; and it
integrates cleanly with the graphical identification theory developed in
later chapters.

\end{tcolorbox}

\textbf{Observational regime.} \(T\) is determined by \(f_T\). Because
\(U\) appears in both \(f_T\) and \(f_Y\), we have
\(\mathrm{Cov}(T, \varepsilon) \neq 0\) in general: this is endogeneity.

\textbf{Interventional regime.} The do-operator replaces the equation
for \(T\) with a constant \(t\), yielding the \emph{mutilated system}:
\[U \sim p(u), \qquad T = t \text{ (fixed)}, \qquad Y = f_Y(t, U, \varepsilon).\]
Now \(T\) and \(U\) are independent by construction: the back-door path
through \(U\) has been severed.

\subsection{Language 2: Directed Acyclic
Graphs}\label{language-2-directed-acyclic-graphs}

A DAG makes the same surgery graphically visible.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Graph Surgery}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

In the observational DAG, arrows into \(T\) encode the mechanisms that
determine \(T\) (including back-door paths through unobserved
variables). Under \(\doop(T{=}t)\), all arrows into \(T\) are
\emph{deleted}. The resulting mutilated graph \(\Gcal_T\) has no
back-door paths from \(T\) to \(Y\): the causal effect flows only along
the direct path \(T \to Y\).

\end{tcolorbox}

The observational and mutilated DAGs for the Gaussian confounded model
are shown side by side in Figure~\ref{fig-surgery} in
Section~\ref{sec-gaussian}.

\subsection{Language 3: Potential
Outcomes}\label{language-3-potential-outcomes}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Potential Outcome {[}@rubin1974estimating{]}}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\(Y(t)\) is the outcome that \emph{would have been observed} had \(T\)
been set to \(t\), possibly contrary to fact.

\textbf{SUTVA} (stable unit treatment value assumption):
\(Y_i = Y_i(T_i)\), i.e., the observed outcome for unit \(i\) equals the
potential outcome at the actual treatment received. This rules out
interference between units and multiple versions of treatment.

\end{tcolorbox}

\textbf{Connection to the do-operator.} Under standard structural
assumptions (consistency + no interference), the potential outcome
\(Y(t)\) and the interventional distribution are linked by
\[Y(t) \;\sim\; f(y \mid \doop(T{=}t)).\]

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Potential outcomes define what we want to estimate (e.g.,
\(\E[Y(1)] - \E[Y(0)]\)), but they do not specify how to write an
observed-data likelihood for estimation. The do-operator fills this gap
by providing an explicit link between the interventional density and the
observational distribution via identification rules (back-door,
front-door, do-calculus).

\end{tcolorbox}

\subsection{Roadmap: How the Trinity Organizes These
Notes}\label{roadmap-how-the-trinity-organizes-these-notes}

The three languages are not used equally throughout the course.

\textbf{Part I --- Foundations: the language of DAGs.} The DAG and the
do-operator are the primary language here because they make the
interventional/observational distinction \emph{syntactically explicit}:
confounding is visible as an open back-door path, and identifying
assumptions are visible as graph criteria.

\textbf{Part II --- Identification: bridging DAGs and observed data.}
Ignorability (\(Y(t) \indep T \mid X\)) is the potential-outcomes
counterpart of the back-door criterion; the propensity score
\(\pi(X) = P(T{=}1 \mid X)\) operationalizes it in observed data.

\textbf{Part III --- Estimation: semiparametric and machine-learning
methods.} The semiparametric efficiency framework --- efficient
influence functions, doubly robust estimators, double machine learning
--- is largely language-neutral: it works with whatever moment condition
the identification step produces.

\subsection{Historical Roots of the Causal Trinity}\label{sec-history}

The three languages grew independently in different disciplines over
more than a century, driven by different scientific questions and
different communities. Understanding this history explains why the three
schools sometimes use incompatible terminology for the same idea.

\textbf{Structural Equation Models: genetics and econometrics.} The
oldest strand begins with the biologist Sewall Wright (1921), who
introduced \emph{path analysis} to decompose correlations among
hereditary traits into direct and indirect causal contributions. The
framework was transplanted into economics by Haavelmo (1943), who argued
that economic relationships should be modeled as autonomous structural
equations robust to policy interventions. The Cowles Commission
formalized simultaneous equation systems throughout the 1940s--50s.
Lucas's (1976) critique --- that reduced-form equations break down when
policy changes the data-generating process --- is essentially a
statement of the interventional/observational distinction, decades
before that phrase existed.

\textbf{Potential Outcomes: experimental statistics and epidemiology.}
Neyman (1923) introduced the notation \(Y_i(t)\) in the context of
randomized agricultural experiments. Fisher (1935) placed randomization
at the foundation of causal inference. The crucial extension to
\emph{observational} studies was made by Rubin (1974), who formalized
the assignment mechanism and stated SUTVA explicitly. Robins (1986)
extended potential outcomes to longitudinal treatments and time-varying
confounding via \(g\)-computation. Imbens and Angrist (1994) connected
the framework to instrumental variables and defined the LATE.

\textbf{DAGs and do-calculus: computer science and philosophy.} Pearl
developed Bayesian networks through the 1980s as a representation for
probabilistic reasoning in AI. The pivotal step came in Pearl (1995),
where the \emph{do-operator} was introduced as a formal syntax for
distinguishing interventional from observational distributions within a
graph-based algebra. The 2000 monograph \emph{Causality} synthesised
DAGs, the do-calculus, identification theory, and the connections to
potential outcomes into a unified framework.

\textbf{Convergence.} By the 2000s it became clear that all three
frameworks are, under standard assumptions, \emph{logically equivalent}:
any result expressible in one can be translated into the others. The
causal trinity is therefore not three competing theories but three
dialects of the same language, each optimized for a different task.
Figure~\ref{fig-timeline} summarizes the key milestones.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-timeline-1.pdf}}

}

\caption{\label{fig-timeline}Key milestones in the three schools of
causal inference. SEM (top, blue) originates in genetics and
econometrics; PO (middle, purple) in experimental statistics; DAG
(bottom, green) in computer science and philosophy. The three developed
largely in isolation until converging in the 2000s.}

\end{figure}%

\section{The Core Distinction}\label{the-core-distinction}

The single most important inequality of this course is:
\begin{equation}\protect\phantomsection\label{eq-core}{
  \underbrace{f\!\left(y \mid x,\, \doop(T{=}t)\right)}_{\text{interventional}}
  \;\neq\;
  \underbrace{f\!\left(y \mid x,\, T{=}t\right)}_{\text{observational}}
  \qquad \text{whenever } T \text{ is endogenous.}
}\end{equation} The key assumption that connects the two densities is
\emph{conditional exchangeability}.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Conditional Exchangeability}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Given observed covariates \(X\) and confounders \(U\), the treatment
assignment is \emph{conditionally exchangeable with the intervention} if
\[Y(t) \indep T \mid X,\, U,\] or equivalently,
\[f(y \mid x,\, T{=}t,\, U{=}u) \;=\; f(y \mid x,\, \doop(T{=}t),\, U{=}u).\]
This says that once we condition on all common causes \((X, U)\) of
\(T\) and \(Y\), observing \(T{=}t\) and intervening to set \(T{=}t\)
produce the same distribution of \(Y\): there is no residual confounding
given \((X, U)\).

\end{tcolorbox}

Under conditional exchangeability, the interventional density has a
direct representation in terms of observable quantities.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-tip-color!10!white, colframe=quarto-callout-tip-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Proposition: Back-Door Adjustment Formula}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Under conditional exchangeability (Definition above),
\begin{equation}\protect\phantomsection\label{eq-backdoor-formula}{
  f(y \mid x,\, \doop(T{=}t))
  \;=\; \int f(y \mid x,\, T{=}t,\, U{=}u)\; p(u \mid x)\; du.
}\end{equation}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Proof}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\textbf{Step (i): weight under the intervention.} Under
\(\doop(T{=}t)\), the arrow \(U \to T\) is severed in the mutilated
graph \(\Gcal_T\), so \(U \indep T \mid X\) under the intervention. The
law of total probability therefore gives: \[f(y \mid x,\, \doop(T{=}t))
  = \int f(y \mid x,\, \doop(T{=}t),\, U{=}u)\; p(u \mid x)\; du.\]

\textbf{Step (ii): replacing the interventional kernel.} By conditional
exchangeability,
\(f(y \mid x,\, \doop(T{=}t),\, U{=}u) = f(y \mid x,\, T{=}t,\, U{=}u)\).
Substituting completes the proof. \(\square\)

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark: Confounding Discrepancy}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

What OLS estimates is the observational density \(f(y \mid x, T{=}t)\),
not the interventional density. The gap
\[f(y \mid x,\, T{=}t) - f(y \mid x,\, \doop(T{=}t))
  = \int f(y \mid x,\, T{=}t,\, U{=}u)
    \bigl[\, p(u \mid x,\, T{=}t) - p(u \mid x) \,\bigr]\, du\] is
non-zero whenever \(U\) and \(T\) are dependent --- the endogeneity
condition.

\end{tcolorbox}

\subsection{Two Scenarios: Observed vs.~Unobserved
Confounder}\label{two-scenarios-observed-vs.-unobserved-confounder}

\textbf{Scenario 1: \(U\) is observed (no unmeasured confounding).} When
every component of \(U\) is recorded in the data, the back-door
adjustment formula (Equation~\ref{eq-backdoor-formula}) becomes usable
from data:
\begin{equation}\protect\phantomsection\label{eq-backdoor-cont}{
  f(y \mid x,\, \doop(T{=}t))
  = \int f(y \mid x,\, T{=}t,\, U{=}u)\; p(u \mid x)\; du.
}\end{equation} The confounder is averaged over its \emph{population}
distribution \(p(u \mid x)\), not over the treatment-conditional
distribution. A special case is \emph{unconfoundedness}: if
\(U \indep T \mid X\) already holds observationally, formula
Equation~\ref{eq-backdoor-cont} reduces to the familiar regression
\(\E[Y \mid X{=}x, T{=}t]\). This is the key assumption behind
regression adjustment and propensity score methods studied in Chapter 6.

\textbf{Scenario 2: \(U\) is unobserved (unmeasured confounding).} When
\(U\) is latent, formula Equation~\ref{eq-backdoor-cont} is not usable.
Additional structure beyond \((Y, T, X)\) must be imposed. The main
strategies studied in this course are \textbf{instrumental variables}
(Chapter 7), the \textbf{front-door criterion} (Chapter 3), and
\textbf{sensitivity analysis}.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\caption{The two scenarios arising from the back-door adjustment
proposition.}\label{tbl-scenarios}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Scenario 1: \(U\) observed}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Scenario 2: \(U\) unobserved}
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Scenario 1: \(U\) observed}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Scenario 2: \(U\) unobserved}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Confounding type & No unmeasured confounding & Unmeasured confounding \\
Back-door formula usable? & Yes & No \\
Identification route & Back-door / standardization & IV, front-door,
\ldots{} \\
Key assumption & Unconfoundedness: \(U \indep T \mid X\) & Exclusion
restriction, monotonicity, \ldots{} \\
Chapters & 2--6 & 7 \\
\end{longtable}

\section{The Gaussian Linear Confounded Model}\label{sec-gaussian}

\subsection{Setup}\label{setup}

The Gaussian linear confounded model is our primary running example
throughout this course. It is simple enough to permit closed-form
calculations yet rich enough to illustrate every key concept.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Gaussian Linear Confounded Model}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

The structural equations are
\begin{equation}\protect\phantomsection\label{eq-iv}{
  Y = \beta T + \gamma U + \varepsilon, \qquad T = \alpha U + \delta,
}\end{equation} where \(U\) is an unobserved confounder and the three
primitive variables are mutually independent:
\[U \sim \mathcal{N}(0,\sigma_U^2), \qquad
  \varepsilon \sim \mathcal{N}(0,\sigma_\varepsilon^2), \qquad
  \delta \sim \mathcal{N}(0,\sigma_\delta^2).\] Here \(\beta\) is the
causal effect of \(T\) on \(Y\), \(\gamma\) is the direct effect of the
confounder \(U\) on \(Y\), and \(\alpha\) is the direct effect of \(U\)
on \(T\).

\end{tcolorbox}

The endogeneity of \(T\) is immediate. From the analyst's perspective,
the composite error in the \(Y\) equation is \(\gamma U + \varepsilon\),
so: \[\mathrm{Cov}(T,\; \gamma U + \varepsilon)
  = \gamma\,\mathrm{Cov}(\alpha U + \delta,\; U)
  = \gamma\alpha\sigma_U^2 \;\neq\; 0
  \quad (\text{when } \alpha \neq 0 \text{ and } \gamma \neq 0).\]
Consequently, OLS regressing \(Y\) on \(T\) does not estimate \(\beta\).

The causal structure is captured by the DAG pair in
Figure~\ref{fig-surgery}. In the observational DAG, the back-door path
\(T \leftarrow U \to Y\) is open: unobserved confounder \(U\) causes
both \(T\) and \(Y\), making \(T\) and the composite error
\(\gamma U + \varepsilon\) correlated. Under the intervention
\(\doop(T{=}t)\), all arrows into \(T\) are deleted (shown faded),
severing the back-door path.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-surgery-1.pdf}}

}

\caption{\label{fig-surgery}Graph surgery on the Gaussian confounded
model. The faded arrow in the mutilated DAG has been severed by the
intervention \(\doop(T{=}t)\). The back-door path
\(T \leftarrow U \to Y\) is eliminated; only the causal path \(T \to Y\)
remains active. The treatment node becomes a fixed constant
(rectangle).}

\end{figure}%

\subsection{Two Explicit Densities}\label{two-explicit-densities}

Write \(\sigma_T^2 = \alpha^2\sigma_U^2 + \sigma_\delta^2\) for the
marginal variance of \(T\).

\textbf{Interventional density.} Set \(T = t\) externally. The back-door
path through \(U\) is severed, so \(U\) is independent of \(T\) under
the intervention and is drawn from its marginal
\(\mathcal{N}(0,\sigma_U^2)\). Then
\(Y \mid \doop(T{=}t) = \beta t + \gamma U + \varepsilon\) with
\(U \indep \varepsilon\). Hence
\begin{equation}\protect\phantomsection\label{eq-int}{
  f\!\left(y \mid \doop(T{=}t)\right)
  = \mathcal{N}\!\left(\beta t,\;\;
    \gamma^2\sigma_U^2 + \sigma_\varepsilon^2\right).
}\end{equation}

\textbf{Observational density.} Observe \(T = t\). Since \(Y\) and \(T\)
are both linear combinations of the independent normals
\((U, \varepsilon, \delta)\), the pair \((Y, T)\) is jointly normal.
Their covariance is
\(\mathrm{Cov}(Y, T) = \beta\sigma_T^2 + \gamma\alpha\sigma_U^2\).
Applying the conditional normal formula:
\begin{equation}\protect\phantomsection\label{eq-obs}{
  f\!\left(y \mid T{=}t\right)
  = \mathcal{N}\!\left(
      \left(\beta + \frac{\gamma\alpha\sigma_U^2}{\sigma_T^2}\right)t,\;\;
      \frac{\gamma^2\sigma_U^2\sigma_\delta^2}{\sigma_T^2}
      + \sigma_\varepsilon^2
    \right).
}\end{equation}

\subsection{The Endogeneity Gap}\label{the-endogeneity-gap}

Equations Equation~\ref{eq-int} and Equation~\ref{eq-obs} differ in both
mean and variance:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\caption{\emph{Equal when \(\alpha = 0\) or \(\gamma = 0\) (no
confounding)}}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Interventional}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Observational}
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Interventional}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Observational}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mean & \(\beta t\) &
\(\left(\beta + \frac{\gamma\alpha\sigma_U^2}{\sigma_T^2}\right)t\) \\
Variance & \(\gamma^2\sigma_U^2 + \sigma_\varepsilon^2\) &
\(\frac{\gamma^2\sigma_U^2\sigma_\delta^2}{\sigma_T^2} + \sigma_\varepsilon^2\) \\
Residual & \((\gamma U{+}\varepsilon) \indep T\) &
\((\gamma U{+}\varepsilon)\) correlated with \(T\) \\
Identified by & RCT (or IV, Chapter 7) & OLS \\
\end{longtable}

The \emph{endogeneity bias} of OLS is
\(\gamma\alpha\sigma_U^2/\sigma_T^2\): the coefficient of \(T\) in the
observational mean exceeds the causal coefficient \(\beta\) by this
amount. Numerically, with \(\alpha = \gamma = 1\) and
\(\sigma_U^2 = \sigma_\delta^2 = 1\):
\[\text{bias} = \frac{1 \times 1 \times 1}{1^2 \times 1 + 1} = \frac{1}{2} = 0.5.\]

\subsection{Lab: Simulating the Two
Densities}\label{lab-simulating-the-two-densities}

The analytical results of this section were verified by simulation using
\(n = 10{,}000\) draws from the structural equations with parameters
\(\beta = 2\), \(\alpha = 1\), \(\gamma = 1\),
\(\sigma_U = \sigma_\varepsilon = \sigma_\delta = 1\). The R code is
distributed separately as \texttt{chapter1\_lab.R}.

\textbf{Experiment 1: OLS bias.} By the omitted-variable bias formula,
the OLS probability limit is
\(\beta + \gamma\alpha\sigma_U^2/\sigma_T^2 = 2 + 0.5 = 2.5\).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Simulated}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Theory}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Formula}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
OLS slope & 2.5147 & 2.5000 &
\(\beta + \gamma\alpha\sigma_U^2/\sigma_T^2\) \\
True \(\beta\) & --- & 2.0000 & \(\beta\) \\
Bias & 0.5147 & 0.5000 & \(\gamma\alpha\sigma_U^2/\sigma_T^2\) \\
\end{longtable}
}

OLS overestimates the causal effect by 25\%.

\textbf{Experiment 2: Two-sample comparison at \(t_0 = 1\).} Theoretical
values are from Equation~\ref{eq-int} and Equation~\ref{eq-obs} at
\(t_0 = 1\).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Mean (Simulated)}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Mean (Theory)}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{SD (Simulated)}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{SD (Theory)}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\(\E[Y \mid T{=}1]\) & 2.567 & 2.500 & 1.240 & \(\sqrt{1.5} = 1.225\) \\
\(\E[Y \mid \doop(T{=}1)]\) & 1.999 & 2.000 & 1.423 &
\(\sqrt{2} = 1.414\) \\
\end{longtable}
}

The variance reduction in the observational distribution reflects the
ratio
\(\sigma_{\mathrm{obs}}^2/\sigma_{\mathrm{int}}^2 = 1.5/2 = 0.75\).

\textbf{Experiment 3: Density overlay for varying \(\alpha\).}
Figure~\ref{fig-density} shows the interventional density
\(\mathcal{N}(\beta t_0,\, \gamma^2\sigma_U^2 + \sigma_\varepsilon^2)\)
(solid) and the observational density Equation~\ref{eq-obs} (dashed),
both evaluated at \(t_0 = 1\), for \(\alpha \in \{0, 0.3, 0.7, 1.0\}\).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-density-1.pdf}}

}

\caption{\label{fig-density}Interventional density \(\mathcal{N}(2,2)\)
(solid black) versus observational density for
\(\alpha \in \{0, 0.3, 0.7, 1.0\}\) (dashed), evaluated at \(t_0 = 1\).
As \(\alpha\) increases, the observational curve shifts rightward
(growing bias) and narrows (reduced variance). At \(\alpha = 0\) there
is no confounding and the two densities coincide. The interventional
curve (solid) is invariant to \(\alpha\).}

\end{figure}%

\subsection{The IV DAG Versus the Mediation DAG}\label{sec-iv-vs-med}

The IV DAG introduced above looks, at first glance, structurally similar
to the mediation DAG that will appear in Chapter 8. The similarity is
superficial; the conceptual difference is fundamental. Confusing the two
is one of the most common errors in applied causal inference.

Figure~\ref{fig-iv-vs-med} places the two DAGs side by side.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-iv-vs-med-1.pdf}}

}

\caption{\label{fig-iv-vs-med}The IV DAG (a) and the mediation DAG (b)
both involve a three-node chain, but they are structurally and
conceptually distinct. In (a), the instrument \(Z\) is pre-treatment and
exogenous: it satisfies \(Z \indep U\) and has no direct path to \(Y\)
(exclusion restriction). In (b), the mediator \(M\) is post-treatment
and endogenous: it is caused by \(T\) and transmits part of \(T\)'s
effect to \(Y\).}

\end{figure}%

Table~\ref{tbl-iv-vs-med} makes the comparison systematic.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\caption{Instrumental variable versus mediator: a systematic
comparison.}\label{tbl-iv-vs-med}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Instrument \(Z\)}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Mediator \(M\)}
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Instrument \(Z\)}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Mediator \(M\)}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Position relative to \(T\) & Pre-treatment (upstream) & Post-treatment
(downstream) \\
Causal relationship to \(T\) & \(Z\) causes \(T\) & \(T\) causes
\(M\) \\
Direct path to \(Y\)? & \textbf{No} (exclusion restriction) &
\textbf{Yes} (\(M \to Y\) on causal path) \\
Independence from \(U\)? & \textbf{Yes} (\(Z \indep U\)) & Not
required \\
Primary purpose & Identify \(T \to Y\) with unmeasured confounding &
Decompose \(T \to Y\) into direct and indirect \\
Key assumptions & Relevance, exogeneity, exclusion & Cross-world
independence; no \(M\)--\(Y\) unmeasured confounding \\
Course coverage & Chapter 7 & Chapter 8 \\
\end{longtable}

The two chains look similar but are not interchangeable:
\[\underbrace{Z \;\longrightarrow\; T \;\longrightarrow\; Y}_{\text{IV chain: } Z \text{ is the identification device}}
  \qquad\text{versus}\qquad
  \underbrace{T \;\longrightarrow\; M \;\longrightarrow\; Y}_{\text{Mediation chain: } M \text{ is on the causal path}}\]

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

There is one important configuration where an observed post-treatment
variable serves a role \emph{analogous} to an instrument: the
\emph{front-door criterion} (Chapter 3). When \(T \to M \to Y\) and
\(T \leftarrow U \to Y\) with \(U\) unobserved, but \(M\) is itself
unconfounded, the causal effect of \(T\) on \(Y\) can still be
identified by combining two back-door adjustments. This is the one case
where a mediator also plays an identification role.

\end{tcolorbox}

\section{The Two-Step Paradigm}\label{sec-two-step}

Causal inference is a two-step discipline. The two steps are logically
distinct and require different tools.

\subsection{Step 1: Identification}\label{step-1-identification}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Identification}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A causal quantity \(P(y \mid \doop(T{=}t))\) is \emph{identified} from
the observational distribution \(P\) if there exists a functional
\(\Psi\) such that \[P(y \mid \doop(T{=}t)) = \Psi(P),\] and \(\Psi(P)\)
depends only on the observable joint distribution.

\end{tcolorbox}

Identification is a purely mathematical question about the structure of
the causal model: given the assumed graph and assumptions, can the
interventional density be expressed as a function of the observed-data
distribution? It does not depend on sample size.

The main tools are: the back-door criterion (Chapters 2--3, applied in
Chapters 5--6), the front-door criterion (Chapter 3), the three rules of
the do-calculus (Chapter 3), and IV assumptions (Chapter 7).

\subsection{Step 2: Estimation}\label{step-2-estimation}

Once \(\Psi(P)\) has been identified, the statistical problem is to
estimate \(\Psi(P)\) from \(n\) observations \(O_1,\dots,O_n\) as
efficiently as possible. The main tools are efficient influence
functions (EIF), inverse probability weighting (IPW), doubly robust
estimators, and double machine learning (DML), all covered in Part III.

\subsection{A Worked Example: Flu Vaccination and
Infection}\label{sec-simpson}

\textbf{Scenario.} A public health agency observes 1,000 individuals
over one flu season. Each person either received a flu vaccine (\(T=1\))
or did not (\(T=0\)), and either became infected (\(Y=1\)) or did not
(\(Y=0\)). Age group \(X\) (elderly \(= E\), young \(= Y\)) is recorded
for all individuals. Elderly people are both more likely to be
vaccinated and more susceptible to infection, so \(X\) confounds the
relationship between \(T\) and \(Y\).

The causal DAG is shown in Figure~\ref{fig-vaccination}.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_01_files/figure-pdf/fig-vaccination-1.pdf}}

}

\caption{\label{fig-vaccination}Causal DAG for the vaccination example.
The green arrow is the causal path \(T \to Y\). The red dashed arrows
form the back-door path \(T \leftarrow X \to Y\): age \(X\) causes both
vaccination \(T\) and infection \(Y\), creating a spurious association.
Because \(X\) is observed, conditioning on it blocks the back-door
path.}

\end{figure}%

\textbf{Observed data.}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llllll@{}}
\toprule\noalign{}
& \textbf{Vaccinated (\(T=1\))} & & \textbf{Unvaccinated (\(T=0\))} & &
Total \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
& \(n\) & Infected & \(n\) & Infected & \\
Elderly (\(X=E\)) & 360 & 108 (30\%) & 40 & 20 (50\%) & 400 \\
Young (\(X=Y\)) & 60 & 3 (5\%) & 540 & 54 (10\%) & 600 \\
\textbf{Total} & 420 & 111 (26.4\%) & 580 & 74 (12.8\%) & 1,000 \\
\end{longtable}
}

\textbf{Simpson's paradox.} Within every stratum the vaccine reduces
infection. Yet in the aggregate the vaccinated group has a \emph{higher}
infection rate (26.4\% vs 12.8\%). The reversal occurs because the
vaccinated group is disproportionately elderly (86\% of vaccinated
vs.~7\% of unvaccinated).

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Stratum
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Vaccinated
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Unvaccinated
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Difference
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Conclusion
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Elderly (\(X=E\)) & 30\% & 50\% & \(-20\) pp & vaccine helps \\
Young (\(X=Y\)) & 5\% & 10\% & \(-5\) pp & vaccine helps \\
\textbf{Aggregate} & \textbf{26.4\%} & \textbf{12.8\%} &
\textbf{\(+13.6\) pp} & \textbf{vaccine harms??} \\
\end{longtable}
}

\textbf{Step 1: Identification.} The set \(\{X\}\) satisfies the
back-door criterion: it blocks the path \(T \leftarrow X \to Y\) and
contains no descendant of \(T\). By the back-door formula:
\begin{equation}\protect\phantomsection\label{eq-backdoor}{
  P\!\left(Y{=}1 \mid \doop(T{=}t)\right)
  = \sum_{x \in \{E,Y\}}
    P(Y{=}1 \mid T{=}t, X{=}x)\,P(X{=}x).
}\end{equation}

\textbf{Step 2: Estimation.} Plugging sample proportions into
Equation~\ref{eq-backdoor}, with \(\hat{P}(X{=}E) = 0.4\) and
\(\hat{P}(X{=}Y) = 0.6\): \[\hat{P}(Y{=}1 \mid \doop(T{=}1))
    = 0.30 \times 0.4 + 0.05 \times 0.6 = 0.15, \qquad
  \hat{P}(Y{=}1 \mid \doop(T{=}0))
    = 0.50 \times 0.4 + 0.10 \times 0.6 = 0.26.\] The estimated causal
risk difference is
\(\hat{\Delta}_{\mathrm{causal}} = 0.15 - 0.26 = -0.11\): the vaccine
causally reduces infection probability by 11 percentage points.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={The Two Steps, Concretely}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\textbf{Step 1 (identification)} established --- from the DAG alone ---
that the back-door formula (Equation~\ref{eq-backdoor}) expresses the
causal quantity as a functional of observable data.

\textbf{Step 2 (estimation)} replaced the population probabilities in
that formula with sample proportions.

These two steps are logically separate: Step 1 is a mathematical
argument about the causal model that does not depend on sample size;
Step 2 is a statistical argument about finite-sample estimation that
does not depend on the causal model. A researcher who skips Step 1 and
reports the raw difference conflates the two and draws the wrong
conclusion.

\end{tcolorbox}

\section{Summary}\label{summary}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Interventional vs.~observational distribution.} Causal
  inference answers questions about interventions
  \(f(y \mid \doop(T{=}t))\), not about observations
  \(f(y \mid T{=}t)\). These two distributions coincide only under
  exogeneity; whenever \(T\) is endogenous they differ, and the
  difference is endogeneity bias.
\item
  \textbf{The causal trinity.} The same causal question can be expressed
  in three languages --- SEM (equation surgery), DAG (graph surgery),
  and potential outcomes (\(Y(t)\)). The do-operator makes the
  interventional/observational distinction syntactically explicit.
  Fluency in all three is essential for modern causal reasoning.
\item
  \textbf{Endogeneity bias in the Gaussian confounded model.} In the
  Gaussian linear confounded model, the coefficient of \(T\) in the
  observational mean \(\E[Y \mid T{=}t]\) exceeds the causal coefficient
  \(\beta\) by \(\gamma\alpha\sigma_U^2/\sigma_T^2\), where
  \(\sigma_T^2 = \alpha^2\sigma_U^2 + \sigma_\delta^2\). This is the
  omitted-variable bias.
\item
  \textbf{Two-step paradigm.} Causal inference is a two-step discipline:
  \emph{identification} (expressing \(\Psi(P)\) as a functional of
  observable data, a mathematical question about the causal model)
  followed by \emph{estimation} (constructing \(\hat{\Psi}_n\)
  efficiently from \(n\) observations, a statistical question about
  finite samples). The two steps are logically independent.
\item
  \textbf{Instrument vs.~mediator.} The IV DAG (\(Z \to T \to Y\) with
  \(Z \indep U\)) and the mediation DAG (\(T \to M \to Y\)) are
  structurally distinct. Conflating the two leads to violations of the
  exclusion restriction and identification failure.
\end{enumerate}

\emph{Causal inference is the study of when the observational
distribution contains enough information to recover the interventional
distribution. Everything in this course --- the back-door criterion,
do-calculus, instrumental variables, doubly robust estimation --- is an
answer to that question in a particular setting.}

\section{Problems}\label{problems}

\textbf{1. Do-notation fundamentals.} For each statement below, decide
whether it refers to an interventional or an observational distribution,
and rewrite it unambiguously using do-notation where appropriate.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  ``The probability that a patient recovers given that they took the
  drug.''
\item
  ``The probability that a patient would recover if we prescribed the
  drug to everyone.''
\item
  ``Among students who attended tutoring, the average exam score was
  85.''
\item
  ``If we enrolled all students in tutoring, the average exam score
  would be 85.''
\end{enumerate}

\textbf{2. Deriving the observational density.} In the Gaussian
confounded model, verify Equation~\ref{eq-obs} by carrying out the
following steps. Let
\(\sigma_T^2 = \alpha^2\sigma_U^2 + \sigma_\delta^2\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Show that \((Y, T)\) is jointly normal by writing both as linear
  combinations of the independent normals \((U, \varepsilon, \delta)\).
\item
  Compute \(\mathrm{Cov}(Y, T)\) and \(\mathrm{Var}(T)\).
\item
  Apply the conditional normal formula to derive \(\E[Y \mid T{=}t]\)
  and \(\mathrm{Var}[Y \mid T{=}t]\), and hence verify
  Equation~\ref{eq-obs}.
\item
  Show that the OLS probability limit is
  \(\beta + \gamma\alpha\sigma_U^2/\sigma_T^2\), and interpret this as
  an omitted-variable bias formula.
\end{enumerate}

\textbf{3. The causal trinity.} Consider the following verbal causal
claim: ``Aspirin (\(T\)) reduces the risk of heart attack (\(Y\))
because it inhibits platelet aggregation (\(M\)), but patients with
pre-existing cardiovascular disease (\(U\), unobserved) are both more
likely to take aspirin and more likely to have a heart attack.''

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Draw the causal DAG implied by this description.
\item
  Write down the recursive SEM with appropriate structural functions
  \(f_T\), \(f_M\), \(f_Y\).
\item
  State the SUTVA assumption and discuss whether it is plausible in this
  setting.
\item
  Explain why \(\E[Y \mid T{=}1] - \E[Y \mid T{=}0]\) does not identify
  the causal effect
  \(\E[Y \mid \doop(T{=}1)] - \E[Y \mid \doop(T{=}0)]\) in this DAG.
\end{enumerate}

\textbf{4. IV versus mediation.} For each scenario below, determine
whether the intermediate variable described is an \emph{instrument} or a
\emph{mediator}, and state which identifying assumption it satisfies or
violates.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  A researcher uses distance to the nearest college (\(Z\)) to study the
  effect of college attendance (\(T\)) on earnings (\(Y\)).
\item
  A nutritionist studies how a high-fiber diet (\(T\)) reduces
  cholesterol (\(M\)), which in turn reduces heart disease risk (\(Y\)).
\item
  A political scientist uses rainfall on election day (\(Z\)) to
  estimate the effect of voter turnout (\(T\)) on electoral outcomes
  (\(Y\)).
\item
  A pharmacologist studies whether a drug (\(T\)) reduces blood pressure
  (\(Y\)) by inhibiting a specific enzyme (\(M\)), and proposes to use
  \(M\) as an instrument for \(T\). Evaluate this proposal.
\end{enumerate}

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\markright{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-berkson1946limitations}
Berkson, Joseph. 1946. {``Limitations of the Application of Fourfold
Table Analysis to Hospital Data.''} \emph{Biometrics Bulletin} 2 (3):
47--53.

\bibitem[\citeproctext]{ref-lauritzen1996graphical}
Lauritzen, Steffen L. 1996. \emph{Graphical Models}. Oxford University
Press.

\bibitem[\citeproctext]{ref-richardson2014ace}
Richardson, Thomas S., and James M. Robins. 2014. \emph{{ACE} Bounds;
Single World Intervention Graphs ({SWIGs}) and Identification of Causal
Effects}. University of Washington.

\bibitem[\citeproctext]{ref-shachter1998bayesball}
Shachter, Ross D. 1998. {``Bayes-Ball: The Rational Pastime (for
Determining Irrelevance and Requisite Information in Belief Networks and
Influence Diagrams).''} \emph{Proceedings of the Fourteenth Conference
on Uncertainty in Artificial Intelligence (UAI)}, 480--87.

\end{CSLReferences}

\bookmarksetup{startatroot}

\chapter{DAGs and d-Separation}\label{dags-and-d-separation}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Learning Objectives}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

By the end of this chapter, students should be able to:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Construct a DAG from a verbal description of a causal model and
  identify parents, descendants, ancestors, and non-descendants of any
  node.
\item
  Classify every intermediate node on a path as a chain, fork, or
  collider, and apply the blocking rule for each.
\item
  Apply the d-separation criterion to determine all conditional
  independence relationships implied by a DAG.
\item
  Recognize and avoid collider bias, including the case where a
  descendant of a collider is conditioned upon.
\item
  State the Markov factorization and use it to write the joint density
  of a DAG in terms of local conditional densities.
\item
  Interpret d-separation results as conditional independence assumptions
  on observed variables, and recognize their role as the graphical
  expression of causal assumptions.
\end{enumerate}

\end{tcolorbox}

\section{Directed Acyclic Graphs}\label{directed-acyclic-graphs}

DAGs allow us to translate qualitative causal assumptions into
quantitative statistical restrictions. This single idea underlies
everything in this chapter: once we draw a graph encoding what we
believe about the causal structure of a problem, the graph tells us
exactly which variables are independent, which are confounded, and what
we need to condition on to identify a causal effect.

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

In this chapter, the word \emph{graph} does not mean a plot of data or a
graph of a function. It means a collection of nodes and edges used to
represent relationships among variables. Our objective is to understand
how such graphs encode statistical structure --- especially conditional
independence, confounding, and path blocking --- and how this graphical
structure will later support causal identification.

\end{tcolorbox}

\subsection{Basic Definition}\label{basic-definition}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Directed Acyclic Graph}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A \emph{directed acyclic graph} (DAG) \(\Gcal = (V, E)\) consists of a
finite set of nodes \(V\) and a set of directed edges
\(E \subseteq V \times V\) such that there is no directed cycle: no node
\(V_i\) has a directed path to itself.

\end{tcolorbox}

In a causal DAG each node represents a variable and each directed edge
\(A \to B\) encodes ``\(A\) is a direct cause of \(B\), given all other
variables in the model.'' The acyclicity condition is essential: it
guarantees that the variables can be ordered topologically so that the
joint density admits the recursive factorization
\[p(v_1,\dots,v_k) = \prod_{i=1}^{k} p(v_i \mid \Pa(v_i)).\]

\subsection{Structural Relationships}\label{structural-relationships}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Structural Relationships in a DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

For a node \(v \in \mathcal{V}\) in \(\Gcal = (\mathcal{V}, E)\):

\begin{itemize}
\tightlist
\item
  \(\Pa(v) = \{w \in \mathcal{V} : w \to v \in E\}\) are the
  \emph{parents} of \(v\).
\item
  \(\De(v)\) = all nodes reachable from \(v\) by directed paths are the
  \emph{descendants} of \(v\).
\item
  \(\An(v)\) = all nodes with a directed path to \(v\) are the
  \emph{ancestors} of \(v\).
\item
  \(\Nd(v) = \mathcal{V} \setminus (\De(v) \cup \{v\})\) are the
  \emph{non-descendants} of \(v\).
\end{itemize}

Note that \(\Nd(v)\) includes the parents of \(v\); when stating the
local Markov property in Section~\ref{sec-markov}, we will exclude the
parents explicitly.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Quick Terminology Summary}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A \emph{node} represents a variable, and an \emph{edge} represents a
relationship between two variables. If \(A \to B\), then \(A\) is a
\emph{parent} of \(B\) and \(B\) is a \emph{child} of \(A\). Two nodes
are \emph{adjacent} if they are connected by an edge. A \emph{path} is
any sequence of connected nodes, regardless of arrow direction; a
\emph{directed path} is a path whose arrows all point in the same
direction. A node is an \emph{ancestor} of another if there is a
directed path from the former to the latter, and a \emph{descendant} if
the direction is reversed. A \emph{directed acyclic graph} (DAG) is a
directed graph with no directed cycles.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Education, Earnings, and Family Background}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Consider the causal story: education (\(E\)) affects earnings (\(Y\));
family background (\(B\)) is a common cause of both; and neighborhood
(\(N\)) affects education but has no direct effect on earnings.

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-1-1.pdf}}

The Markov factorization is
\(p(n,b,e,y) = p(n)\,p(b)\,p(e\mid n,b)\,p(y\mid e,b)\). Reading off
structural relationships: \(\Pa(E) = \{N,B\}\), \(\Pa(Y) = \{E,B\}\),
\(\Pa(N)=\Pa(B)=\varnothing\). The descendants of \(N\) are \(\{E,Y\}\);
\(B\) and \(N\) are non-descendants of each other.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: The IV DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

The canonical instrumental variable model involves four nodes: \(Z\)
(instrument), \(T\) (treatment), \(Y\) (outcome), and \(U\) (unobserved
confounder).

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-2-1.pdf}}

\(\Pa(T) = \{Z,U\}\), \(\Pa(Y) = \{T,U\}\),
\(\Pa(Z) = \Pa(U) = \varnothing\). The descendants of \(Z\) are
\(\{T, Y\}\); \(U\) and \(Z\) are non-descendants of each other.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: The Mediation DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

In a mediation model, treatment \(T\) affects outcome \(Y\) both
directly and through an intermediate variable \(M\) (the mediator). An
unobserved confounder \(U\) creates a back-door path
\(T \leftarrow U \rightarrow Y\), making \(T\) endogenous. The mediator
\(M\) is itself unconfounded.

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-3-1.pdf}}

\(\Pa(T) = \{U\}\), \(\Pa(M) = \{T\}\), \(\Pa(Y) = \{M, T, U\}\),
\(\Pa(U) = \varnothing\). The total effect of \(T\) on \(Y\) travels
along two paths: the direct path \(T \to Y\) and the indirect path
\(T \to M \to Y\).

\end{tcolorbox}

\section{Paths, Blocking, and
d-Separation}\label{paths-blocking-and-d-separation}

A DAG encodes direct causal relationships through its edges, but
variables can also be statistically related through longer routes that
mix directed and reversed edges. The concept of a \emph{path} formalises
these routes, and the question of whether a path transmits or blocks
statistical dependence --- depending on which variables are conditioned
upon --- is precisely what d-separation answers. The key insight is that
conditioning can both \emph{close} channels that were open (by blocking
a chain or fork) and \emph{open} channels that were closed (by
activating a collider). Figure~\ref{fig-chain-fork-collider} illustrates
all three cases.

\subsection{Path Structures}\label{path-structures}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Path}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A \emph{path} between nodes \(X\) and \(Y\) in \(\Gcal\) is any sequence
of distinct nodes \(X = V_0, V_1, \dots, V_k = Y\) such that each
consecutive pair is connected by an edge in either direction.

\end{tcolorbox}

Every intermediate node \(V_m\) on a path plays one of three structural
roles. In a \textbf{chain} (\(V_{m-1} \to V_m \to V_{m+1}\)), \(V_m\) is
a causal intermediary through which influence is transmitted. In a
\textbf{fork} (\(V_{m-1} \leftarrow V_m \to V_{m+1}\)), \(V_m\) is a
common cause that creates confounding between the two endpoints. In a
\textbf{collider} (\(V_{m-1} \to V_m \leftarrow V_{m+1}\)), both arrows
point \emph{into} \(V_m\); this is the crucial asymmetric case whose
behavior under conditioning is the opposite of the other two.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/fig-chain-fork-collider-1.pdf}}

}

\caption{\label{fig-chain-fork-collider}The three fundamental path
structures in a DAG, with their default independence status and the
effect of conditioning on the middle node \(M\). Chains and forks are
\emph{open by default} and are blocked by conditioning on \(M\).
Colliders are \emph{closed by default} and are opened by conditioning on
\(M\) (or any descendant of \(M\)).}

\end{figure}%

\subsection{Blocking Rules}\label{blocking-rules}

Conditioning on a node affects the paths it lies on differently
depending on its structural role:

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Structure}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Pattern}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Effect of conditioning}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Key intuition}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Chain & \(A \to M \to B\) & Blocks the path & Causal transmission \\
Fork & \(A \leftarrow M \to B\) & Blocks the path & Common cause \\
Collider & \(A \to M \leftarrow B\) & \textbf{Opens} the path & Common
effect \\
\end{longtable}
}

The critical asymmetry --- colliders are \emph{closed by default} and
\emph{opened} by conditioning, while chains and forks are \emph{open by
default} and \emph{closed} by conditioning --- is what makes collider
bias so easy to overlook in practice.

\textbf{Chain: Smoking \(\to\) Tar \(\to\) Cancer.} Let \(A\) = smoking,
\(M\) = tar deposits, \(B\) = lung cancer. Marginally, heavy smokers
have elevated cancer rates --- the path is open. But conditioning on tar
level blocks the path: once tar level is fixed, the causal channel is
fully accounted for.

\textbf{Fork: Poverty \(\to\) Poor Diet; Poverty \(\to\) Lack of
Exercise.} Let \(M\) = poverty, \(A\) = poor diet, \(B\) = lack of
exercise. Unconditionally, diet quality and exercise are correlated
through poverty. Conditioning on income level blocks the path and
removes this spurious association.

\textbf{Collider: Accident \(\to\) Hospitalization \(\leftarrow\)
Cancer.} Let \(A\) = traffic accident, \(B\) = cancer, \(M\) =
hospitalization. In the general population, \(A \indep B\). But among
hospitalized patients --- conditioning on \(M\) --- the two become
negatively associated. This is Berkson's bias (Berkson 1946).

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Three-Node Motifs at a Glance}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

In a \emph{chain} \(A \to M \to B\), conditioning on \(M\) blocks the
path. In a \emph{fork} \(A \leftarrow M \to B\), conditioning on \(M\)
removes the spurious association. In a \emph{collider}
\(A \to M \leftarrow B\), the path is blocked by default, but
conditioning on \(M\) --- or on any descendant of \(M\) --- opens the
path and induces association. These three motifs are the local building
blocks of d-separation in arbitrary DAGs.

\end{tcolorbox}

\subsection{The d-Separation
Criterion}\label{the-d-separation-criterion}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: d-Blocking and d-Separation}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A path \(\pi\) is \emph{d-blocked} by a set \(\mathbf{S}\) if:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\pi\) contains a chain \(A \to M \to B\) or fork
  \(A \leftarrow M \to B\) with \(M \in \mathbf{S}\); or
\item
  \(\pi\) contains a collider \(A \to C \leftarrow B\) with
  \(C \notin \mathbf{S}\) and no descendant of \(C\) is in
  \(\mathbf{S}\).
\end{enumerate}

Nodes \(X\) and \(Y\) are \emph{d-separated} by \(\mathbf{S}\), written
\((X \indep Y \mid \mathbf{S})_{\Gcal}\), if every path between \(X\)
and \(Y\) in \(\Gcal\) is d-blocked by \(\mathbf{S}\).

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Applying the d-Separation Definition to the Three Toy Settings}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\textbf{(i) Chain --- Smoking \(\to\) Tar \(\to\) Cancer.} The only path
is \(A \to M \to B\).

\begin{itemize}
\tightlist
\item
  \(\mathbf{S} = \varnothing\): not d-blocked.
  \(\Rightarrow A \nindep B\).
\item
  \(\mathbf{S} = \{M\}\): clause (1) applies.
  \(\Rightarrow A \indep B \mid M\).
\end{itemize}

\textbf{(ii) Fork --- Poverty \(\to\) Poor Diet; Poverty \(\to\) Lack of
Exercise.} The only path is \(A \leftarrow M \to B\).

\begin{itemize}
\tightlist
\item
  \(\mathbf{S} = \varnothing\): not d-blocked.
  \(\Rightarrow A \nindep B\).
\item
  \(\mathbf{S} = \{M\}\): clause (1) applies.
  \(\Rightarrow A \indep B \mid M\).
\end{itemize}

\textbf{(iii) Collider --- Accident \(\to\) Hospitalization
\(\leftarrow\) Cancer.} The only path is \(A \to M \leftarrow B\).

\begin{itemize}
\tightlist
\item
  \(\mathbf{S} = \varnothing\): collider \(M \notin \mathbf{S}\), clause
  (2) applies. \(\Rightarrow A \indep B\).
\item
  \(\mathbf{S} = \{M\}\): clause (2) no longer blocks.
  \(\Rightarrow A \nindep B \mid M\) (Berkson's bias).
\end{itemize}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: A Direct Probability Proof for the Chain}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Consider the chain \(X_1 \to X_2 \to X_3\). By the Markov factorization,
\(p(x_1, x_2, x_3) = p(x_1)\,p(x_2 \mid x_1)\,p(x_3 \mid x_2)\).
Conditioning on \(X_2 = x_2\):
\[p(x_1, x_3 \mid x_2) = \frac{p(x_1)\,p(x_2 \mid x_1)\,p(x_3 \mid x_2)}{p(x_2)} = p(x_1 \mid x_2)\,p(x_3 \mid x_2).\]
Hence \(X_1 \indep X_3 \mid X_2\). The fork case
\(X_1 \leftarrow X_2 \to X_3\) follows by an identical calculation.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-tip-color!10!white, colframe=quarto-callout-tip-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Theorem: Verma \& Pearl (1988); @pearl2009causality, Theorem 1.2.4}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

If \((X \indep Y \mid \mathbf{S})_{\Gcal}\), then
\(X \indep Y \mid \mathbf{S}\) in every distribution that is Markov with
respect to \(\Gcal\).

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark: Soundness, Not Converse}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

\textbf{?@thm-dsep} states that d-separation implies conditional
independence for every distribution Markov with respect to \(\Gcal\).
The converse need not hold without additional assumptions such as
\emph{faithfulness}: a conditional independence may occur in the data
because of special parameter values even when the corresponding nodes
are not d-separated in the graph.

\end{tcolorbox}

Table~\ref{tbl-markov-implications} summarizes the Markov factorization
and its independence implication for each of the three path structures.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\caption{Markov factorization and d-separation result for each path
structure.}\label{tbl-markov-implications}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Structure}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Markov factorization} \(p(a,m,b)\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{d-separation}
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Structure}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Markov factorization} \(p(a,m,b)\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{d-separation}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Chain \(A\!\to\!M\!\to\!B\) & \(p(a)\,p(m\mid a)\,p(b\mid m)\) &
\((A\indep B\mid M)_{\Gcal}\) \\
Fork \(A\!\leftarrow\!M\!\to\!B\) & \(p(m)\,p(a\mid m)\,p(b\mid m)\) &
\((A\indep B\mid M)_{\Gcal}\) \\
Collider \(A\!\to\!M\!\leftarrow\!B\) & \(p(a)\,p(b)\,p(m\mid a,b)\) &
\((A\indep B)_{\Gcal}\) \\
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Checking d-Separation in a Four-Node DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Consider the DAG with edges \(Z \to T\), \(U \to T\), \(T \to Y\),
\(U \to Y\).

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-4-1.pdf}}

\textbf{Query 1.} Is \((Z \indep U)_{\Gcal}\)? The only path
\(Z \to T \leftarrow U\) has \(T\) as a collider with
\(T \notin \varnothing\) --- blocked.
\(\Rightarrow (Z \indep U)_{\Gcal}\).

\textbf{Query 2.} Is \((Z \indep U \mid T)_{\Gcal}\)? Now
\(T \in \mathbf{S}\): the collider is observed, so the ball passes
through. The path is open. \(\Rightarrow Z \nindep U \mid T\).

Comparing the two queries: \(Z\) and \(U\) are marginally independent
(the instrument is exogenous) but become dependent once we condition on
\(T\). This is Berkson's bias.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Practice DAG --- Eight-Node Graph}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Consider the DAG with nodes \(W\), \(X_1\), \(T\), \(M_1\), \(M_2\),
\(Y\), \(C\), \(D\) and edges \(W \to X_1\), \(W \to T\), \(W \to Y\),
\(T \to M_1\), \(M_1 \to Y\), \(M_1 \to M_2\), \(X_1 \to C\),
\(M_2 \to C\), \(C \to D\).

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-5-1.pdf}}

\textbf{(1)} Is \(X_1 \indep Y\)? No.~Two open paths:
\(X_1 \leftarrow W \to Y\) and \(X_1 \leftarrow W \to T \to M_1 \to Y\).

\textbf{(2)} Is \(X_1 \indep Y \mid W\)? Yes. Both open paths pass
through the fork \(W\); conditioning on \(W\) blocks them.

\textbf{(3)} Is \(T \indep M_2 \mid M_1\)? Yes. The path
\(T \to M_1 \to M_2\) is blocked by \(M_1\); all other paths are also
blocked.

\textbf{(4)} Does conditioning on \(C\) create collider bias? Yes. \(C\)
is a collider on \(X_1 \to C \leftarrow M_2\). Conditioning on \(C\)
opens this path, inducing a spurious association between \(X_1\) and
\(M_2\).

\textbf{(5)} Does conditioning on \(D\) open the path
\(X_1 \to C \leftarrow M_2\)? Yes. \(D\) is a descendant of \(C\). By
clause (2) of the d-separation definition, the collider at \(C\) is
activated.

\end{tcolorbox}

\subsection{Practical Ways to Check
d-Separation}\label{practical-ways-to-check-d-separation}

\textbf{Bayes-Ball Intuition.} Imagine releasing a ball from \(X\)
asking whether it can reach \(Y\), given that nodes in \(\mathbf{S}\)
are observed. At a chain or fork node not in \(\mathbf{S}\): ball passes
through. At a chain or fork node in \(\mathbf{S}\): ball stops. At a
collider not in \(\mathbf{S}\) (and no descendant in \(\mathbf{S}\)):
ball stops. At a collider in \(\mathbf{S}\) (or with a descendant in
\(\mathbf{S}\)): ball passes through. The algorithm is formalized in
Shachter (1998).

\textbf{Moral Graph Transformation.} (1) Restrict to the ancestral set
\(\An(X \cup Y \cup \mathbf{S})\). (2) Moralise: for every collider
\(A \to C \leftarrow B\), add an undirected edge \(A - B\). (3) Remove
all edge directions. (4) Delete all nodes in \(\mathbf{S}\). If \(X\)
and \(Y\) are disconnected in the result, then
\((X \indep Y \mid \mathbf{S})_{\Gcal}\). A full treatment is in
Lauritzen (1996, Ch. 3).

\section{Collider Bias and the IV DAG}\label{sec-collider}

\subsection{Berkson's Bias}\label{berksons-bias}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-warning-color!10!white, colframe=quarto-callout-warning-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Warning: Collider Bias {[}@berkson1946limitations{]}}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Conditioning on a collider variable induces a spurious association
between its parents, \emph{even when they are marginally independent}.
The same effect occurs when conditioning on any descendant of a
collider.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Collider Bias in the IV DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

In the IV DAG, \(T\) is a collider on the path \(Z \to T \leftarrow U\).
Marginally, \(Z \indep U\) (the instrument is exogenous). However,
\[Z \indep U \qquad \text{but} \qquad Z \nindep U \mid T.\] Conditioning
on \(T\) --- restricting to the treated subpopulation --- makes the
instrument \(Z\) appear associated with \(U\), invalidating the IV
argument within that stratum.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Collider Bias through Selection: Talent and Wealth}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Suppose both talent (\(A\)) and wealth (\(B\)) increase the probability
of admission to an elite school, so admission (\(S\)) is a collider:
\(A \to S \leftarrow B\).

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-6-1.pdf}}

In the general population, talent and wealth may be independent:
\(A \indep B\). But among admitted students --- conditioning on \(S\)
--- lower talent makes higher wealth more likely, and vice versa. This
is collider bias: admission is a common effect of talent and wealth, and
restricting to admitted students is precisely conditioning on that
common effect.

\end{tcolorbox}

\subsection{Full d-Separation Analysis of the IV
DAG}\label{full-d-separation-analysis-of-the-iv-dag}

We work through the IV DAG with edges \(Z \to T\), \(T \to Y\),
\(U \to T\), \(U \to Y\), where \(U\) is unobserved.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Endpoints}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Path}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Type}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{Why}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\(Z \leftrightarrow Y\) & \(Z \to T \to Y\) & \emph{Causal} & Directed
from \(Z\) to \(Y\); carries the IV signal \\
\(Z \leftrightarrow Y\) & \(Z \to T \leftarrow U \to Y\) &
\emph{Associational} & Collider at \(T\); activates back-door via
\(U\) \\
\(Z \leftrightarrow U\) & \(Z \to T \leftarrow U\) &
\emph{Associational} & Collider at \(T\); dormant unless \(T\)
conditioned on \\
\end{longtable}
}

\textbf{Question 1.} Is \(Z \indep Y \mid \varnothing\)? Causal path
\(Z \to T \to Y\): open. Associational path: blocked by collider at
\(T\). \(\Rightarrow Z \nindep Y\).

\textbf{Question 2.} Is \(Z \indep Y \mid T\)? Causal path: blocked by
\(T\). Associational path: collider at \(T\) opened.
\(\Rightarrow Z \nindep Y \mid T\). The residual association is entirely
spurious --- a collider artefact, not a causal effect.

\textbf{Question 3.} Is \(Z \indep Y \mid \{T, U\}\)? Both paths
blocked. \(\Rightarrow Z \indep Y \mid \{T, U\}\).

\textbf{Question 4.} Is \(Z \indep U \mid \varnothing\)? The only path
\(Z \to T \leftarrow U\) is blocked by collider at \(T\).
\(\Rightarrow Z \indep U\). This is \emph{exogeneity}.

The four questions give a complete graphical account of the three IV
assumptions. Question 1 establishes \emph{relevance}; Question 4
establishes \emph{exogeneity}; Question 3 establishes the
\emph{exclusion restriction}. Question 2 is the warning: conditioning on
\(T\) alone simultaneously closes the causal channel and opens the
confounded channel.

\section{The Markov Property and Factorization}\label{sec-markov}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-tip-color!10!white, colframe=quarto-callout-tip-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Proposition: Conditional Independence in the Three-Node Chain}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Let \(X_1 \to X_2 \to X_3\) be a chain with Markov factorization
\(p(x_1, x_2, x_3) = p(x_1)\,p(x_2 \mid x_1)\,p(x_3 \mid x_2)\). Then
\(X_1 \indep X_3 \mid X_2\). The analogous result for the fork
\(X_1 \leftarrow X_2 \to X_3\) is left as an exercise.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Definition: Local Markov Property}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

A distribution \(P\) satisfies the \emph{local Markov property} with
respect to \(\Gcal\) if, for every node \(V_i \in \mathcal{V}\):
\[V_i \indep \bigl(\Nd(V_i) \setminus \Pa(V_i)\bigr) \mid \Pa(V_i).\]
That is, once we condition on the direct causes of a node, that node is
independent of all variables that are neither its descendants nor its
parents.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Remark}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

The \emph{global Markov property} is the statement that every
d-separation in \(\Gcal\) implies a conditional independence in \(P\)
--- precisely the content of \textbf{?@thm-dsep}. For DAGs, the local
and global Markov properties are equivalent (Lauritzen 1996, Proposition
3.27).

\end{tcolorbox}

An immediate consequence is the \emph{Markov factorization}:
\begin{equation}\protect\phantomsection\label{eq-markov}{p(v_1, \dots, v_k) \;=\; \prod_{i=1}^{k} p\!\left(v_i \mid \Pa(v_i)\right).}\end{equation}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Markov Factorization in the Education Example}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

For the DAG with edges \(N \to E\), \(B \to E\), \(B \to Y\),
\(E \to Y\):
\[p(n, b, e, y) = p(n)\,p(b)\,p(e \mid n, b)\,p(y \mid e, b).\] A
regression of \(Y\) on \(E\) alone is confounded by \(B\). Conditioning
on \(B\) blocks the back-door path \(E \leftarrow B \to Y\) and
identifies the causal effect \(P(y \mid \doop(E{=}e))\) via the
back-door formula (Chapter 3).

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, arc=.35mm, bottomrule=.15mm, bottomtitle=1mm, breakable, colback=white, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, left=2mm, leftrule=.75mm, opacityback=0, opacitybacktitle=0.6, rightrule=.15mm, title={Example: Markov Factorization in the IV DAG}, titlerule=0mm, toprule=.15mm, toptitle=1mm]

Including the latent \(U\):
\[p(z, t, y, u) = p(z)\,p(u)\,p(t \mid z, u)\,p(y \mid t, u).\] Since
\(U\) is unobserved, the observable factorization is obtained by
marginalizing:
\[p(z, t, y) = \int p(z)\,p(u)\,p(t \mid z, u)\,p(y \mid t, u)\,\mathrm{d}u.\]
This cannot be simplified to \(p(z)\,p(t\mid z)\,p(y\mid t)\) when \(U\)
is a common cause of \(T\) and \(Y\): this is precisely the endogeneity
problem.

\end{tcolorbox}

\section{Worked Example: The Education--Earnings
DAG}\label{sec-education}

This section is the template for how we will use DAGs throughout the
course: specify the DAG, read off the factorization, use d-separation to
identify implied conditional independences, and interpret the result in
causal terms.

\textbf{The causal story.} Education (\(E\)) affects earnings (\(Y\));
family background (\(B\)) is a common cause of both education and
earnings; neighborhood (\(N\)) affects education but has no direct
effect on earnings. All four variables are observed; there are no latent
confounders.

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/unnamed-chunk-7-1.pdf}}

\textbf{Step 1 --- Markov factorization.}
\(\Pa(N) = \Pa(B) = \varnothing\), \(\Pa(E) = \{N, B\}\),
\(\Pa(Y) = \{E, B\}\).
\[p(n, b, e, y) \;=\; p(n)\,p(b)\,p(e \mid n, b)\,p(y \mid e, b).\]

\textbf{Step 2 --- d-Separation.} There are two paths between \(N\) and
\(Y\): Path 1: \(N \to E \to Y\) (chain through \(E\)). Path 2:
\(N \to E \leftarrow B \to Y\) (collider at \(E\)).

\begin{itemize}
\tightlist
\item
  \emph{Query (i):} \((N \indep Y)_{\Gcal}\)? Path 1 open.
  \(\Rightarrow N \nindep Y\).
\item
  \emph{Query (ii):} \((N \indep Y \mid E)_{\Gcal}\)? Path 1 blocked by
  \(E\); Path 2 collider \(E\) opened. Path still open through \(B\).
  \(\Rightarrow N \nindep Y \mid E\). This is a collider trap:
  conditioning on \(E\) inadvertently opens a spurious association
  between \(N\) and \(Y\) through \(B\).
\item
  \emph{Query (iii):} \((N \indep Y \mid \{E, B\})_{\Gcal}\)? Path 1
  blocked by \(E\); Path 2 collider opened but \(B\) blocks it.
  \(\Rightarrow (N \indep Y \mid E, B)_{\Gcal}\).
\item
  \emph{Query (iv):} \((N \indep B)_{\Gcal}\)? Path
  \(N \to E \leftarrow B\): collider at \(E\) with
  \(E \notin \varnothing\) --- blocked. \(\Rightarrow N \indep B\).
\end{itemize}

\textbf{Step 3 --- Conditional Independence.} By \textbf{?@thm-dsep}:
\(N \indep B\), \(N \indep Y \mid E, B\), \(N \nindep Y\),
\(N \nindep Y \mid E\).

\textbf{Step 4 --- Identification.} The only back-door path is
\(E \leftarrow B \to Y\). With \(\mathbf{S} = \{B\}\):
\[P(y \mid \doop(E{=}e)) \;=\; \sum_{b} P(y \mid e, b)\,P(b).\] Every
term involves only the observed distribution, so the causal effect is
identified entirely from observational data.

\section{The Big Picture}\label{the-big-picture}

The concepts developed in this chapter form the graphical foundation for
all subsequent identification and estimation theory. The chain of
reasoning runs from a qualitative causal graph all the way to a formula
for the interventional distribution:

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{chapter_02_files/figure-pdf/fig-big-picture-1.pdf}}

}

\caption{\label{fig-big-picture}The four-step pipeline from causal
assumptions to identification formula.}

\end{figure}%

The logical chain in compact form:
\[\text{structural assumptions} \;\Longrightarrow\; \text{DAG} \;\Longrightarrow\; \text{d-separation} \;\Longrightarrow\; \text{conditional independences} \;\Longrightarrow\; \text{identification formulas}.\]

\section{Summary}\label{summary-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A DAG encodes the qualitative causal structure of a data-generating
  mechanism without committing to functional forms or error
  distributions.
\item
  The three elementary path patterns --- chain, fork, and collider ---
  determine when conditioning on a middle node blocks or opens a path.
  Chains and forks are \emph{open by default} and blocked by
  conditioning; colliders are \emph{closed by default} and opened by
  conditioning.
\item
  The d-separation criterion is a graphical rule: \(X\) and \(Y\) are
  d-separated by \(\mathbf{S}\) exactly when every path between them is
  blocked by \(\mathbf{S}\). Under the Markov property, this graphical
  statement implies a corresponding conditional independence in the
  distribution.
\item
  The Markov factorization \(p = \prod_i p(x_i \mid \Pa(x_i))\) is the
  formal bridge between the graph and the joint distribution, and is the
  starting point for all identification derivations.
\item
  Collider bias (Berkson 1946) is one of the most common errors in
  applied causal inference. Conditioning on a descendant of a collider
  opens the collider just as conditioning on the collider itself does.
\item
  D-separation provides a graphical criterion for reading off
  conditional independence implications of a DAG. Under the Markov
  property, these imply corresponding conditional independences in the
  observed distribution. The IV DAG analysis illustrates this directly:
  the claim that \(Z\) is a valid instrument is encoded as d-separation
  statements in the graph, yet the core assumptions of exogeneity and
  exclusion are substantive and not fully verifiable from observational
  data alone.
\item
  \textbf{A practical workflow.} To analyze a DAG, proceed in four
  steps: identify the graph structure, determine which paths are open or
  blocked, translate d-separation statements into conditional
  independences under the Markov property, and then interpret those
  independences in light of the causal question.
\end{enumerate}

\section{Problems}\label{problems-1}

\textbf{1. Warm-up: a single collider.} Consider the DAG
\(X \to Y \leftarrow Z\), where \(X\) and \(Z\) have no other
connections.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Identify the structural role of \(Y\) on the path
  \(X \to Y \leftarrow Z\).
\item
  Is \(X \indep Z\)? Apply the d-separation criterion to the only path
  between \(X\) and \(Z\).
\item
  Is \(X \indep Z \mid Y\)? Explain what happens to the path when \(Y\)
  is conditioned on.
\end{enumerate}

\textbf{2. d-Separation practice.} Consider the DAG: \(A \to B \to D\),
\(A \to C \to D\), \(B \to E\), \(C \to E\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  List all paths between \(A\) and \(E\). (\emph{Hint}: there are four
  paths in total; two pass through \(D\).)
\item
  For each path, identify the role (chain, fork, collider) of each
  intermediate node.
\item
  Does \(\{B, C\}\) d-separate \(A\) and \(E\)?
\item
  Does \(\{D\}\) d-separate \(B\) and \(C\)? What type of node is \(D\)
  on the path \(B \to D \leftarrow C\)?
\end{enumerate}

\textbf{3. Berkson's bias.} Suppose \(X\) and \(Y\) are independent
standard normal variables, and let \(S = \mathbf{1}[X + Y > 0]\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Verify analytically that \(\mathrm{Cov}(X, Y \mid S{=}1) < 0\).
\item
  Draw the DAG for \((X, Y, S)\) and identify \(S\) as a collider.
\item
  Explain in one sentence why restricting the analysis to the subsample
  with \(S=1\) biases estimates of any association between \(X\) and
  \(Y\).
\end{enumerate}

\textbf{4. Markov factorization and collider activation.} Consider the
DAG with edges \(A \to E\), \(A \to W\), \(F \to E\), \(E \to W\), where
\(A\) = ability, \(F\) = family income, \(E\) = education, \(W\) =
wages.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Write down the Markov factorization \(p(a, f, e, w)\).
\item
  Is \((F \indep W)_{\Gcal}\)? List all paths between \(F\) and \(W\).
\item
  Is \((F \indep W \mid E)_{\Gcal}\)? Identify the role of \(E\) on each
  path.
\item
  A researcher regresses \(W\) on \(E\) and \(F\), omitting \(A\). Is
  the coefficient on \(E\) a causal effect? Explain using the graph.
\end{enumerate}

\textbf{5. Theorem proof for the collider.} Consider the collider
\(A \to M \leftarrow B\) with Markov factorization
\(p(a, m, b) = p(a)\,p(b)\,p(m \mid a, b)\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  By marginalizing over \(M\), show that \(A \indep B\) in the joint
  distribution.
\item
  Show that conditioning on \(M\) breaks this independence.
\item
  Explain in one sentence why parts (a) and (b) together are consistent
  with \textbf{?@thm-dsep}.
\end{enumerate}

\textbf{6. Terminology check.} Consider the DAG with edges \(U \to X\),
\(U \to Z\), \(X \to W\), \(Z \to W\), \(W \to Y\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Identify the parents, children, ancestors, descendants, and
  non-descendants of node \(W\).
\item
  List all pairs of adjacent nodes.
\item
  Which pairs of nodes are connected by a directed path?
\item
  Write the Markov factorization \(p(u, x, z, w, y)\).
\end{enumerate}

\textbf{7. Markov factorization and local Markov property.} Consider the
DAG with edges \(X_1 \to X_2\), \(X_1 \to X_3\), \(X_2 \to X_4\),
\(X_3 \to X_4\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Write the joint density \(p(x_1, x_2, x_3, x_4)\) implied by the
  Markov factorization.
\item
  State the local Markov property for each of the four nodes.
\item
  Is \((X_2 \indep X_3)_{\Gcal}\)? Is
  \((X_2 \indep X_3 \mid X_1)_{\Gcal}\)?
\end{enumerate}

\textbf{8. Toy proof: conditional independence in the fork.} Consider
the fork \(X_1 \leftarrow X_2 \to X_3\) with Markov factorization
\(p(x_1, x_2, x_3) = p(x_2)\,p(x_1 \mid x_2)\,p(x_3 \mid x_2)\).

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Show directly that \(X_1 \indep X_3 \mid X_2\).
\item
  Is \(X_1 \indep X_3\) marginally?
\item
  Explain why conditioning on the common cause \(X_2\) removes the
  association between \(X_1\) and \(X_3\).
\end{enumerate}

\textbf{9. d-Separation in the practice DAG.} Refer to the eight-node
DAG in the practice example above. For each query, state whether it is
true or false and justify by listing all relevant paths.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  \(X_1 \indep Y\)
\item
  \(X_1 \indep Y \mid W\)
\item
  \(T \indep M_2 \mid M_1\)
\item
  Does conditioning on \(C\) induce collider bias between \(X_1\) and
  \(M_2\)?
\item
  Does conditioning on \(D\) (a descendant of \(C\)) open the path
  \(X_1 \to C \leftarrow M_2\)?
\end{enumerate}

\section*{References}\label{references-1}
\addcontentsline{toc}{section}{References}

\markright{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-berkson1946limitations}
Berkson, Joseph. 1946. {``Limitations of the Application of Fourfold
Table Analysis to Hospital Data.''} \emph{Biometrics Bulletin} 2 (3):
47--53.

\bibitem[\citeproctext]{ref-lauritzen1996graphical}
Lauritzen, Steffen L. 1996. \emph{Graphical Models}. Oxford University
Press.

\bibitem[\citeproctext]{ref-richardson2014ace}
Richardson, Thomas S., and James M. Robins. 2014. \emph{{ACE} Bounds;
Single World Intervention Graphs ({SWIGs}) and Identification of Causal
Effects}. University of Washington.

\bibitem[\citeproctext]{ref-shachter1998bayesball}
Shachter, Ross D. 1998. {``Bayes-Ball: The Rational Pastime (for
Determining Irrelevance and Requisite Information in Belief Networks and
Influence Diagrams).''} \emph{Proceedings of the Fourteenth Conference
on Uncertainty in Artificial Intelligence (UAI)}, 480--87.

\end{CSLReferences}


\backmatter


\end{document}
