<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Instrumental Variables – Theory and Methods in Causal Inference</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_08.html" rel="next">
<link href="./chapter_06.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    tags: 'ams',
    macros: {
      doop:   ["\\operatorname{do}"],
      indep:  ["\\perp\\!\\!\\!\\perp"],
      nindep: ["\\not\\!\\perp\\!\\!\\!\\perp"],
      E:      ["\\mathbb{E}"],
      Gcal:   ["\\mathcal{G}"],
      Pa:     ["\\mathrm{Pa}"],
      De:     ["\\mathrm{De}"],
      An:     ["\\mathrm{An}"],
      Nd:     ["\\mathrm{Nd}"],
      pto:    ["\\overset{p}{\\to}"],
      expit:  ["\\operatorname{expit}"]
    }
  }
};
</script>
<style>
.quarto-download-btn {
  background-color: #1e3864 !important;
  color: white !important;
  border: none !important;
  padding: 6px 14px !important;
  border-radius: 6px !important;
  font-weight: 600 !important;
  font-size: 0.85rem !important;
}
.quarto-download-btn:hover {
  background-color: #2e72b8 !important;
  color: white !important;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_04.html">Identification</a></li><li class="breadcrumb-item"><a href="./chapter_07.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Theory and Methods in Causal Inference</a> 
        <div class="sidebar-tools-main">
    <a href="./Theory-and-Methods-in-Causal-Inference.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">DAGs and d-Separation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Do-Calculus and Identification Criteria</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Identification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Potential Outcomes and Adjustment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mediation and Front-Door Identification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sensitivity Analysis and Partial Identification</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating Equations and Influence Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Doubly Robust Estimation and Semiparametric Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Flexible Nuisance Estimation, Orthogonal Scores, and Cross-Fitting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Graphical Intuition for Conditional Independence and d-Separation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Single World Intervention Graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_C.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Pathwise Differentiability and Efficient Influence Functions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-why" id="toc-sec-why" class="nav-link active" data-scroll-target="#sec-why"><span class="header-section-number">7.1</span> Why Instrumental Variables?</a>
  <ul class="collapse">
  <li><a href="#the-endogeneity-problem" id="toc-the-endogeneity-problem" class="nav-link" data-scroll-target="#the-endogeneity-problem"><span class="header-section-number">7.1.1</span> The Endogeneity Problem</a></li>
  <li><a href="#the-iv-idea" id="toc-the-iv-idea" class="nav-link" data-scroll-target="#the-iv-idea"><span class="header-section-number">7.1.2</span> The IV Idea</a></li>
  </ul></li>
  <li><a href="#sec-assumptions" id="toc-sec-assumptions" class="nav-link" data-scroll-target="#sec-assumptions"><span class="header-section-number">7.2</span> Graphical Setup and Core Assumptions</a>
  <ul class="collapse">
  <li><a href="#the-iv-dag" id="toc-the-iv-dag" class="nav-link" data-scroll-target="#the-iv-dag"><span class="header-section-number">7.2.1</span> The IV DAG</a></li>
  <li><a href="#the-three-assumptions-in-three-languages" id="toc-the-three-assumptions-in-three-languages" class="nav-link" data-scroll-target="#the-three-assumptions-in-three-languages"><span class="header-section-number">7.2.2</span> The Three Assumptions in Three Languages</a></li>
  <li><a href="#relevance" id="toc-relevance" class="nav-link" data-scroll-target="#relevance"><span class="header-section-number">7.2.3</span> Relevance</a></li>
  <li><a href="#exogeneity" id="toc-exogeneity" class="nav-link" data-scroll-target="#exogeneity"><span class="header-section-number">7.2.4</span> Exogeneity</a></li>
  <li><a href="#exclusion" id="toc-exclusion" class="nav-link" data-scroll-target="#exclusion"><span class="header-section-number">7.2.5</span> Exclusion</a></li>
  </ul></li>
  <li><a href="#sec-linear" id="toc-sec-linear" class="nav-link" data-scroll-target="#sec-linear"><span class="header-section-number">7.3</span> Identification in the Linear Homogeneous-Effect Model</a>
  <ul class="collapse">
  <li><a href="#the-linear-structural-model" id="toc-the-linear-structural-model" class="nav-link" data-scroll-target="#the-linear-structural-model"><span class="header-section-number">7.3.1</span> The Linear Structural Model</a></li>
  <li><a href="#the-ols-bias" id="toc-the-ols-bias" class="nav-link" data-scroll-target="#the-ols-bias"><span class="header-section-number">7.3.2</span> The OLS Bias</a></li>
  <li><a href="#derivation-of-the-wald-estimand" id="toc-derivation-of-the-wald-estimand" class="nav-link" data-scroll-target="#derivation-of-the-wald-estimand"><span class="header-section-number">7.3.3</span> Derivation of the Wald Estimand</a></li>
  </ul></li>
  <li><a href="#sec-why-matter" id="toc-sec-why-matter" class="nav-link" data-scroll-target="#sec-why-matter"><span class="header-section-number">7.4</span> Why the IV Assumptions Matter</a></li>
  <li><a href="#sec-lab" id="toc-sec-lab" class="nav-link" data-scroll-target="#sec-lab"><span class="header-section-number">7.5</span> Lab: OLS vs.&nbsp;IV Across Instrument Strengths</a></li>
  <li><a href="#sec-overid" id="toc-sec-overid" class="nav-link" data-scroll-target="#sec-overid"><span class="header-section-number">7.6</span> Multiple Instruments and Overidentification</a></li>
  <li><a href="#sec-late" id="toc-sec-late" class="nav-link" data-scroll-target="#sec-late"><span class="header-section-number">7.7</span> Heterogeneous Treatment Effects and the LATE Framework</a>
  <ul class="collapse">
  <li><a href="#compliance-types" id="toc-compliance-types" class="nav-link" data-scroll-target="#compliance-types"><span class="header-section-number">7.7.1</span> Compliance Types</a></li>
  <li><a href="#the-monotonicity-assumption" id="toc-the-monotonicity-assumption" class="nav-link" data-scroll-target="#the-monotonicity-assumption"><span class="header-section-number">7.7.2</span> The Monotonicity Assumption</a></li>
  <li><a href="#the-late-theorem" id="toc-the-late-theorem" class="nav-link" data-scroll-target="#the-late-theorem"><span class="header-section-number">7.7.3</span> The LATE Theorem</a></li>
  </ul></li>
  <li><a href="#sec-interpret" id="toc-sec-interpret" class="nav-link" data-scroll-target="#sec-interpret"><span class="header-section-number">7.8</span> Interpreting IV Estimands</a>
  <ul class="collapse">
  <li><a href="#what-the-two-frameworks-say" id="toc-what-the-two-frameworks-say" class="nav-link" data-scroll-target="#what-the-two-frameworks-say"><span class="header-section-number">7.8.1</span> What the Two Frameworks Say</a></li>
  <li><a href="#when-does-late-equal-ate" id="toc-when-does-late-equal-ate" class="nav-link" data-scroll-target="#when-does-late-equal-ate"><span class="header-section-number">7.8.2</span> When Does LATE Equal ATE?</a></li>
  <li><a href="#different-instruments-different-estimands" id="toc-different-instruments-different-estimands" class="nav-link" data-scroll-target="#different-instruments-different-estimands"><span class="header-section-number">7.8.3</span> Different Instruments, Different Estimands</a></li>
  <li><a href="#the-policy-relevance-of-late" id="toc-the-policy-relevance-of-late" class="nav-link" data-scroll-target="#the-policy-relevance-of-late"><span class="header-section-number">7.8.4</span> The Policy Relevance of LATE</a></li>
  </ul></li>
  <li><a href="#sec-practical" id="toc-sec-practical" class="nav-link" data-scroll-target="#sec-practical"><span class="header-section-number">7.9</span> Practical Guidance on Defending an IV Design</a></li>
  <li><a href="#sec-kipp" id="toc-sec-kipp" class="nav-link" data-scroll-target="#sec-kipp"><span class="header-section-number">7.10</span> Applied Example: Charter School Lotteries and the KIPP Lynn Study</a></li>
  <li><a href="#sec-compare" id="toc-sec-compare" class="nav-link" data-scroll-target="#sec-compare"><span class="header-section-number">7.11</span> IV versus Back-Door Adjustment</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">7.12</span> Chapter Summary</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems"><span class="header-section-number">7.13</span> Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_04.html">Identification</a></li><li class="breadcrumb-item"><a href="./chapter_07.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this chapter, students should be able to:</p>
<ol type="1">
<li>Diagnose the endogeneity problem: explain why an unobserved confounder makes back-door adjustment fail, and describe how an instrumental variable provides an alternative identification route.</li>
<li>State the three IV assumptions — relevance, exogeneity, and exclusion — in the DAG/do-calculus, structural-equation, and potential-outcomes languages, and explain which are testable and which require institutional justification.</li>
<li>Follow how the IV assumptions identify the Wald estimand, and interpret the reduced form and first stage as its two observable components.</li>
<li>Explain what the Wald estimand identifies when treatment effects are heterogeneous — the Local Average Treatment Effect for compliers — why that estimand depends on the choice of instrument, and when it coincides with the ATE.</li>
<li>Compare IV and back-door adjustment on the assumptions each requires, the estimand each identifies, and the ways each can fail.</li>
</ol>
</div>
</div>
<section id="sec-why" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-why"><span class="header-section-number">7.1</span> Why Instrumental Variables?</h2>
<p>Chapter 6 showed how causal effects can be identified when all confounders are observed and can be blocked by conditioning on <span class="math inline">\(X\)</span>. When some confounders are unobserved, back-door adjustment fails. This chapter develops instrumental variables (IV) as an alternative identification strategy: rather than blocking the confounding path <span class="math inline">\(T \leftarrow U \to Y\)</span>, IV exploits an external variable <span class="math inline">\(Z\)</span> whose effect on <span class="math inline">\(T\)</span> is free of confounding by <span class="math inline">\(U\)</span>. This chapter asks what IV identifies and under what assumptions; Chapter 13 asks how that estimand is computed and tested in practice.</p>
<section id="the-endogeneity-problem" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="the-endogeneity-problem"><span class="header-section-number">7.1.1</span> The Endogeneity Problem</h3>
<p>Unconfoundedness <span class="math inline">\((Y(0), Y(1)) \indep T \mid X\)</span> requires that every variable affecting both treatment and outcome is observed and included in <span class="math inline">\(X\)</span>. In many empirical settings this is implausible: in labor economics, unobserved ability or motivation affects both schooling decisions and wages; in epidemiology, unobserved health behaviors affect both treatment uptake and outcomes. Whenever an unobserved confounder <span class="math inline">\(U\)</span> creates a back-door path <span class="math inline">\(T \leftarrow U \to Y\)</span>, the adjustment formula fails: <span class="math display">\[\int f(y \mid t, x)\, p(x)\, dx \;\neq\; f(y \mid \doop(T{=}t)).\]</span> The gap is the <em>endogeneity bias</em>. We need a different identification strategy.</p>
</section>
<section id="the-iv-idea" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="the-iv-idea"><span class="header-section-number">7.1.2</span> The IV Idea</h3>
<p>An <em>instrumental variable</em> <span class="math inline">\(Z\)</span> is an observed variable that: (1) <em>moves</em> treatment <span class="math inline">\(T\)</span> (relevance); (2) <em>does so exogenously</em> — <span class="math inline">\(Z\)</span> is unrelated to the unobserved confounder <span class="math inline">\(U\)</span> (exogeneity); (3) <em>affects <span class="math inline">\(Y\)</span> only through <span class="math inline">\(T\)</span></em> — <span class="math inline">\(Z\)</span> has no direct path to <span class="math inline">\(Y\)</span> (exclusion). Under these three conditions, the variation in <span class="math inline">\(T\)</span> induced by <span class="math inline">\(Z\)</span> is free of confounding by <span class="math inline">\(U\)</span>, so the ratio of the <span class="math inline">\(Z\)</span>-induced variation in <span class="math inline">\(Y\)</span> to the <span class="math inline">\(Z\)</span>-induced variation in <span class="math inline">\(T\)</span> becomes a meaningful target for identification.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Returns to Schooling
</div>
</div>
<div class="callout-body-container callout-body">
<p>A researcher wants to estimate the causal effect of years of schooling <span class="math inline">\(T\)</span> on log wages <span class="math inline">\(Y\)</span>. Unobserved ability <span class="math inline">\(U\)</span> raises both schooling and wages, so OLS is biased upward. No set of observed covariates <span class="math inline">\(X\)</span> fully captures ability. An instrumental variable <span class="math inline">\(Z\)</span> that shifts schooling for reasons unrelated to ability — such as proximity to a school or a policy change in compulsory attendance laws — provides a way to isolate the causal effect of schooling on wages.</p>
</div>
</div>
<p>IV does not eliminate the confounding path <span class="math inline">\(T \leftarrow U \to Y\)</span>, nor does it make treatment as-if randomly assigned for the full population. Instead, IV <em>avoids</em> confounding rather than controlling for it — a distinction that matters both for interpreting what is identified (the LATE for compliers, not the ATE) and for understanding which assumption does the heaviest lifting (exclusion, not unconfoundedness).</p>
</section>
</section>
<section id="sec-assumptions" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-assumptions"><span class="header-section-number">7.2</span> Graphical Setup and Core Assumptions</h2>
<section id="the-iv-dag" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="the-iv-dag"><span class="header-section-number">7.2.1</span> The IV DAG</h3>
<p>The causal structure for a basic IV model with covariates <span class="math inline">\(X\)</span> is:</p>
<figure style="text-align:center;margin:1.5em auto;" class="figure">
<svg viewbox="0 0 440 180" width="100%" style="max-width:440px;font-family:sans-serif;font-size:13px;">
  <defs>
    <marker id="ba7" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#2E74B6"></path>
    </marker>
    <marker id="ra7" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#C00"></path>
    </marker>
    <marker id="ga7" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#1A7A3A"></path>
    </marker>
  </defs>
  <!-- Z -->
  <circle cx="60" cy="85" r="24" fill="#EEF4FB" stroke="#2E74B6" stroke-width="2"></circle>
  <text x="60" y="91" text-anchor="middle" fill="#2E74B6" font-weight="bold">Z</text>
  <!-- T -->
  <circle cx="200" cy="85" r="24" fill="#EEF4FB" stroke="#2E74B6" stroke-width="2"></circle>
  <text x="200" y="91" text-anchor="middle" fill="#2E74B6" font-weight="bold">T</text>
  <!-- Y -->
  <circle cx="340" cy="85" r="24" fill="#EEF4FB" stroke="#2E74B6" stroke-width="2"></circle>
  <text x="340" y="91" text-anchor="middle" fill="#2E74B6" font-weight="bold">Y</text>
  <!-- X -->
  <circle cx="200" cy="155" r="24" fill="#EEF7EE" stroke="#1A7A3A" stroke-width="2"></circle>
  <text x="200" y="161" text-anchor="middle" fill="#1A7A3A" font-weight="bold">X</text>
  <!-- U -->
  <circle cx="300" cy="25" r="22" fill="#FFF0F0" stroke="#C00" stroke-width="1.8" stroke-dasharray="5,3"></circle>
  <text x="300" y="31" text-anchor="middle" fill="#C00">U</text>
  <!-- Z→T (1) -->
  <line x1="84" y1="85" x2="174" y2="85" stroke="#2E74B6" stroke-width="2" marker-end="url(#ba7)"></line>
  <text x="129" y="78" text-anchor="middle" fill="#2E74B6" font-size="11">(1)</text>
  <!-- T→Y -->
  <line x1="224" y1="85" x2="314" y2="85" stroke="#2E74B6" stroke-width="2" marker-end="url(#ba7)"></line>
  <!-- X→T -->
  <line x1="200" y1="131" x2="200" y2="111" stroke="#1A7A3A" stroke-width="1.5" marker-end="url(#ga7)"></line>
  <!-- X→Y -->
  <line x1="222" y1="140" x2="323" y2="103" stroke="#1A7A3A" stroke-width="1.5" marker-end="url(#ga7)"></line>
  <!-- X→Z -->
  <line x1="178" y1="140" x2="78" y2="100" stroke="#1A7A3A" stroke-width="1.5" marker-end="url(#ga7)"></line>
  <!-- U→T -->
  <line x1="283" y1="42" x2="216" y2="67" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3" marker-end="url(#ra7)"></line>
  <!-- U→Y -->
  <line x1="311" y1="43" x2="332" y2="63" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3" marker-end="url(#ra7)"></line>
</svg>
<figcaption>The basic IV DAG with covariates $X$ and unobserved confounder $U$. Blue arrows: causal effects. Dashed red: confounding paths. Green: observed covariate effects. The label (1) on $Z \to T$ marks the relevance assumption. The absence of a $Z \to Y$ arrow encodes exclusion.</figcaption>
</figure>
<p>The three IV assumptions correspond to three distinct features of this DAG: (1) <strong>Relevance</strong>: there is a directed path <span class="math inline">\(Z \to T\)</span>; (2) <strong>Exogeneity</strong>: conditional on <span class="math inline">\(X\)</span>, the DAG implies <span class="math inline">\(Z \indep U \mid X\)</span> by d-separation; (3) <strong>Exclusion</strong>: every directed path from <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span> in <span class="math inline">\(\mathcal{G}\)</span> passes through <span class="math inline">\(T\)</span> — there is no direct edge <span class="math inline">\(Z \to Y\)</span>.</p>
<p>The distinction between exogeneity and exclusion is fundamental. Exogeneity says the instrument is not confounded with latent causes of the outcome. Exclusion says the instrument has no causal channel to the outcome except through treatment. A randomized encouragement may be exogenous by design, yet still violate exclusion if the encouragement changes outcomes through information, motivation, or stigma apart from the treatment itself.</p>
</section>
<section id="the-three-assumptions-in-three-languages" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="the-three-assumptions-in-three-languages"><span class="header-section-number">7.2.2</span> The Three Assumptions in Three Languages</h3>
<p>The same three assumptions can be expressed in three causal languages. These are parallel formulations, not literally identical statements: each highlights a different aspect of the design. The graphical formulation is most useful for causal design; the structural formulation is most useful for deriving moment restrictions; the potential-outcomes formulation prepares the ground for the LATE framework. The assumptions are ordered <em>relevance <span class="math inline">\(\to\)</span> exogeneity <span class="math inline">\(\to\)</span> exclusion</em>, reflecting the natural sequence in which a researcher assesses them.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Assumption</strong></th>
<th><strong>Potential outcomes</strong></th>
<th><strong>Structural / econometric</strong></th>
<th><strong>Do-calculus / DAG</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Relevance</strong></td>
<td><span class="math inline">\(P(T_i(1) \neq T_i(0)) &gt; 0\)</span></td>
<td><span class="math inline">\(\pi \neq 0\)</span> in <span class="math inline">\(T = \pi Z + \delta^\top X + \eta\)</span></td>
<td><span class="math inline">\(Z \to T\)</span> in <span class="math inline">\(\mathcal{G}\)</span> (no d-separation)</td>
</tr>
<tr class="even">
<td><strong>Exogeneity</strong></td>
<td><span class="math inline">\(Z \indep (Y(0), Y(1), T(0), T(1)) \mid X\)</span></td>
<td><span class="math inline">\(\E[\varepsilon \mid Z, X] = 0\)</span></td>
<td><span class="math inline">\(Z \indep U \mid X\)</span></td>
</tr>
<tr class="odd">
<td><strong>Exclusion</strong></td>
<td><span class="math inline">\(Y_i(t, z) = Y_i(t, z')\)</span> for all <span class="math inline">\(z, z'\)</span></td>
<td><span class="math inline">\(Z\)</span> absent from structural equation for <span class="math inline">\(Y\)</span></td>
<td><span class="math inline">\(f(y \mid x, \doop(T{=}t), z) = f(y \mid x, \doop(T{=}t))\)</span></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Three Languages, One Identification Argument
</div>
</div>
<div class="callout-body-container callout-body">
<p>These three formulations are aligned but not literally identical. The graphical statement encodes causal structure. The potential-outcomes statement encodes counterfactual independence. The structural formulation encodes moment orthogonality. In a well-specified IV model they support the same identification argument, but they are not interchangeable symbols.</p>
<p><em>Relevance</em> is about the <span class="math inline">\(Z \to T\)</span> link — <span class="math inline">\(Z\)</span> must genuinely move <span class="math inline">\(T\)</span>. <em>Exogeneity</em> is about the absence of omitted common causes linking <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span>. <em>Exclusion</em> is about the absence of any direct causal path <span class="math inline">\(Z \to Y\)</span> that bypasses <span class="math inline">\(T\)</span>.</p>
</div>
</div>
<p><strong>Why the do-calculus formulation is preferred.</strong> The exclusion restriction in the do-calculus column reads: <span class="math display">\[f(y \mid x, \doop(T{=}t), z) = f(y \mid x, \doop(T{=}t)).\]</span> This is a statement about the <em>interventional</em> density — the distribution of <span class="math inline">\(Y\)</span> after we have <em>set</em> <span class="math inline">\(T = t\)</span> by do-surgery. The do-operator makes it impossible to confuse this with the observational statement <span class="math inline">\(f(y \mid x, T{=}t, z) = f(y \mid x, T{=}t)\)</span>, which is a much weaker condition.</p>
</section>
<section id="relevance" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="relevance"><span class="header-section-number">7.2.3</span> Relevance</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Relevance
</div>
</div>
<div class="callout-body-container callout-body">
<p>The instrument <span class="math inline">\(Z\)</span> is <strong>relevant</strong> if it has a non-zero causal effect on the treatment <span class="math inline">\(T\)</span> within at least some stratum of covariates <span class="math inline">\(X\)</span>: <span class="math inline">\(P(T \mid \doop(Z{=}z), X{=}x)\)</span> varies with <span class="math inline">\(z\)</span> for some <span class="math inline">\(x\)</span>. In the linear first-stage model <span class="math inline">\(T = \pi Z + \delta^\top X + \eta\)</span>, this reduces to <span class="math inline">\(\pi \neq 0\)</span>.</p>
</div>
</div>
<p>Graphically, relevance means <span class="math inline">\(Z\)</span> and <span class="math inline">\(T\)</span> are not d-separated in <span class="math inline">\(\mathcal{G}\)</span>. The conditional covariance <span class="math inline">\(\mathrm{Cov}(Z, T \mid X)\)</span> and the first-stage <span class="math inline">\(F\)</span>-statistic are empirical diagnostics for the observable association; the causal claim that <span class="math inline">\(Z\)</span> shifts <span class="math inline">\(T\)</span> is design-based.</p>
</section>
<section id="exogeneity" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="exogeneity"><span class="header-section-number">7.2.4</span> Exogeneity</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Exogeneity
</div>
</div>
<div class="callout-body-container callout-body">
<p>The instrument <span class="math inline">\(Z\)</span> is <strong>exogenous</strong> given covariates <span class="math inline">\(X\)</span> if there is no open back-door path from <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span> through unobserved causes: <span class="math inline">\(Z \indep U \mid X\)</span> in <span class="math inline">\(\mathcal{G}\)</span> by d-separation.</p>
</div>
</div>
<p>In the structural linear model, the same requirement appears as <span class="math inline">\(\E[Z\varepsilon \mid X] = 0\)</span>, because the structural residual <span class="math inline">\(\varepsilon\)</span> is a function of <span class="math inline">\(U\)</span>. This moment condition is a <em>consequence</em> of the graphical assumption, not a definition of exogeneity. A researcher who adopts the moment condition as a primitive has no guarantee that <span class="math inline">\(Z\)</span> is free of back-door paths to the outcome.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Quarter of Birth <span class="citation" data-cites="angrist1991does">(<a href="#ref-angrist1991does" role="doc-biblioref">Angrist and Krueger 1991</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="angrist1991does">Angrist and Krueger (<a href="#ref-angrist1991does" role="doc-biblioref">1991</a>)</span> used quarter of birth as an instrument for schooling to estimate the return to education. Exogeneity requires no open back-door path from quarter of birth to wages through unobserved variables such as ability or family background; birth timing is largely outside parental control. <span class="citation" data-cites="bound1995problems">Bound et al. (<a href="#ref-bound1995problems" role="doc-biblioref">1995</a>)</span> later raised concerns about weak first stages in some specifications.</p>
</div>
</div>
<p>Exogeneity is untestable: the unobserved confounder <span class="math inline">\(U\)</span> is, by definition, unobserved.</p>
</section>
<section id="exclusion" class="level3" data-number="7.2.5">
<h3 data-number="7.2.5" class="anchored" data-anchor-id="exclusion"><span class="header-section-number">7.2.5</span> Exclusion</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Exclusion Restriction
</div>
</div>
<div class="callout-body-container callout-body">
<p>The instrument <span class="math inline">\(Z\)</span> satisfies the <strong>exclusion restriction</strong> if it affects the outcome <span class="math inline">\(Y\)</span> <em>only</em> through its effect on the treatment <span class="math inline">\(T\)</span>. In do-calculus terms: <span class="math display">\[f(y \mid x, \doop(T{=}t), z) = f(y \mid x, \doop(T{=}t)) \quad \text{for all } z.\]</span> In potential outcomes terms: <span class="math inline">\(Y_i(t, z) = Y_i(t, z')\)</span> for all <span class="math inline">\(z \neq z'\)</span>.</p>
</div>
</div>
<p>Exclusion is a <em>causal</em> restriction, not a conditional-correlation restriction. Adding a direct arrow <span class="math inline">\(Z \to Y\)</span> to the DAG is exactly the formal counterpart of exclusion failing. In the mutilated graph <span class="math inline">\(\mathcal{G}_{\overline{T}}\)</span>, the path <span class="math inline">\(Z \to Y\)</span> would remain open. Rule 1 of the do-calculus, which would allow removing <span class="math inline">\(Z\)</span> from the density of <span class="math inline">\(Y\)</span> given <span class="math inline">\(\doop(T{=}t)\)</span>, no longer applies.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Why Exclusion Is the Hardest Assumption
</div>
</div>
<div class="callout-body-container callout-body">
<p>Relevance can be tested. Exogeneity can sometimes be defended by design. But exclusion — that <span class="math inline">\(Z\)</span> has <em>no direct effect</em> on <span class="math inline">\(Y\)</span> whatsoever — is:</p>
<ul>
<li><strong>Untestable</strong> in just-identified models.</li>
<li><strong>Easy to violate in practice.</strong> An instrument that “moves treatment” often also moves other inputs. If <span class="math inline">\(Z\)</span> is distance to a hospital (instrument for treatment uptake), it may also directly affect health outcomes through travel time in emergencies.</li>
<li><strong>Consequential.</strong> Even a small direct effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(Y\)</span> can cause substantial bias in the Wald estimand, especially when the first stage is weak (derived in <a href="#sec-why-matter" class="quarto-xref"><span>Section 7.4</span></a>).</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Three Assumptions Are Necessary but Not Sufficient
</div>
</div>
<div class="callout-body-container callout-body">
<p>The three IV assumptions are necessary but not sufficient for <em>point</em> identification of any causal estimand <span class="citation" data-cites="hernan2006instruments levis2024nonparametric">(<a href="#ref-hernan2006instruments" role="doc-biblioref">Hernán and Robins 2006</a>; <a href="#ref-levis2024nonparametric" role="doc-biblioref">Levis et al. 2024</a>)</span>. A fourth <em>structural assumption</em> on the counterfactual distribution of treatment response or treatment effect heterogeneity is required. The choice of fourth assumption determines which causal quantity the Wald estimand identifies: constant treatment effects (<a href="chapter_08.html#sec-linear" class="quarto-xref"><span>Section 8.7</span></a>), under which the Wald estimand identifies the ATE; or monotonicity (<a href="#sec-late" class="quarto-xref"><span>Section 7.7</span></a>), under which it identifies the LATE for compliers.</p>
<p>Strikingly, across these different identification schemes the same conditional Wald formula <span class="math inline">\(\mathrm{Cov}(Z, Y \mid X)/\mathrm{Cov}(Z, T \mid X)\)</span> appears as the identifying expression in many cases — but its causal target changes. The three core IV assumptions are all expressible within the graphical language; the fourth assumption, by contrast, lies <em>outside</em> the graphical language in every case.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Same Observables, Different ATEs
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(Z, T \in \{0,1\}\)</span> with <span class="math inline">\(\E[T \mid Z{=}1] - \E[T \mid Z{=}0] = 0.2\)</span> and <span class="math inline">\(\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0] = 0.1\)</span>, giving Wald ratio <span class="math inline">\(= 0.5\)</span>. Both DGPs share the same compliance structure: <span class="math inline">\(P(\text{co}) = 0.2\)</span>, <span class="math inline">\(P(\text{at}) = 0.4\)</span>, <span class="math inline">\(P(\text{nt}) = 0.4\)</span>.</p>
<p><strong>DGP A (constant effects):</strong> <span class="math inline">\(\tau_i = 0.5\)</span> for all units. <span class="math inline">\(\text{ATE} = 0.5\)</span>. Wald ratio <span class="math inline">\(= 0.5\)</span>.</p>
<p><strong>DGP B (heterogeneous effects + monotonicity):</strong> <span class="math inline">\(\tau_{\text{co}} = 0.5\)</span>, <span class="math inline">\(\tau_{\text{at}} = \tau_{\text{nt}} = 0\)</span>. <span class="math inline">\(\text{ATE} = 0.2 \times 0.5 = 0.1\)</span>. Wald ratio <span class="math inline">\(= 0.5\)</span>.</p>
<p>Both DGPs produce the same first stage, reduced form, and Wald ratio. Yet the ATE is <span class="math inline">\(0.5\)</span> under DGP A and <span class="math inline">\(0.1\)</span> under DGP B — a fivefold difference. No amount of data can distinguish them without a fourth structural assumption.</p>
</div>
</div>
</section>
</section>
<section id="sec-linear" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-linear"><span class="header-section-number">7.3</span> Identification in the Linear Homogeneous-Effect Model</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Framework 1: Constant Treatment Effect and Linear Structure
</div>
</div>
<div class="callout-body-container callout-body">
<p>This section works within a linear structural model in which the treatment effect is the <em>same</em> for every unit: <span class="math inline">\(Y_i(t) - Y_i(t') = \beta(t-t')\)</span> for all <span class="math inline">\(i, t, t'\)</span>. Under this assumption, IV identifies the single parameter <span class="math inline">\(\beta\)</span>, which equals the ATE, the ATT, and the LATE simultaneously: <span class="math inline">\(\beta = \text{ATE} = \text{ATT} = \text{LATE}\)</span>.</p>
</div>
</div>
<section id="the-linear-structural-model" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="the-linear-structural-model"><span class="header-section-number">7.3.1</span> The Linear Structural Model</h3>
<p>Consider the linear structural model: <span id="eq-outcome"><span class="math display">\[Y = \alpha + \beta T + \gamma^\top X + \varepsilon, \tag{7.1}\]</span></span> <span id="eq-firststage"><span class="math display">\[T = \pi Z + \delta^\top X + \eta, \tag{7.2}\]</span></span> where <span class="math inline">\(\varepsilon\)</span> and <span class="math inline">\(\eta\)</span> are structural errors with <span class="math inline">\(\mathrm{Cov}(\varepsilon, \eta) = \rho\sigma\tau \neq 0\)</span>. The non-zero covariance is the source of endogeneity: OLS applied to <a href="#eq-outcome" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> gives a biased estimator of <span class="math inline">\(\beta\)</span>. The <em>reduced form</em> substitutes <a href="#eq-firststage" class="quarto-xref">Equation&nbsp;<span>7.2</span></a> into <a href="#eq-outcome" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>: <span class="math display">\[Y = \alpha + \beta\pi Z + (\beta\delta + \gamma)^\top X + (\beta\eta + \varepsilon).\]</span> The reduced-form coefficient on <span class="math inline">\(Z\)</span> is <span class="math inline">\(\beta\pi\)</span>: the total effect of the instrument on the outcome. Dividing by the first-stage coefficient <span class="math inline">\(\pi\)</span> recovers <span class="math inline">\(\beta\)</span>, provided <span class="math inline">\(\pi \neq 0\)</span>.</p>
</section>
<section id="the-ols-bias" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="the-ols-bias"><span class="header-section-number">7.3.2</span> The OLS Bias</h3>
<p>The probability limit of the OLS estimator is: <span class="math display">\[\mathrm{plim}\; \hat\beta_{\mathrm{OLS}} = \beta + \frac{\mathrm{Cov}(T, \varepsilon)}{\mathrm{Var}(T)} = \beta + \frac{\rho\sigma\tau}{\pi^2 \mathrm{Var}(Z) + \tau^2}.\]</span> The bias is zero only if <span class="math inline">\(\rho = 0\)</span> (no unobserved confounding) or if the instrument perfectly determines <span class="math inline">\(T\)</span>. The direction of the bias depends on the sign of <span class="math inline">\(\rho\)</span>.</p>
</section>
<section id="derivation-of-the-wald-estimand" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="derivation-of-the-wald-estimand"><span class="header-section-number">7.3.3</span> Derivation of the Wald Estimand</h3>
<p>The derivation has three ingredients: the first stage (how much <span class="math inline">\(Z\)</span> moves <span class="math inline">\(T\)</span>), the reduced form (how much <span class="math inline">\(Z\)</span> moves <span class="math inline">\(Y\)</span>), and the exclusion restriction (any effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(Y\)</span> must operate through <span class="math inline">\(T\)</span>).</p>
<ol type="1">
<li><strong>Exogeneity</strong> (<span class="math inline">\(Z \indep U \mid X\)</span>) implies <span class="math inline">\(\E[\varepsilon \mid Z, X] = 0\)</span>.</li>
<li><strong>Exclusion</strong> (no <span class="math inline">\(Z\)</span> term in the outcome equation) combined with exogeneity yields the moment condition <span class="math inline">\(\E[\varepsilon \cdot Z \mid X] = 0\)</span>.</li>
<li>Multiplying <a href="#eq-outcome" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> by <span class="math inline">\((Z - \E[Z \mid X])\)</span> and applying step 2: <span class="math inline">\(\mathrm{Cov}(Y, Z \mid X) = \beta \cdot \mathrm{Cov}(T, Z \mid X)\)</span>, which is the <strong>reduced-form decomposition</strong>: the <span class="math inline">\(Z\)</span>–<span class="math inline">\(Y\)</span> covariance is entirely attributable to the causal path <span class="math inline">\(Z \to T \to Y\)</span>.</li>
<li><strong>Relevance</strong> (<span class="math inline">\(\mathrm{Cov}(Z, T \mid X) \neq 0\)</span>) ensures the denominator is non-zero:</li>
</ol>
<p><span id="eq-wald-cov"><span class="math display">\[\beta = \frac{\mathrm{Cov}(Y,\, Z \mid X)}{\mathrm{Cov}(T,\, Z \mid X)}. \tag{7.3}\]</span></span></p>
<p>In the binary instrument case (<span class="math inline">\(Z \in \{0,1\}\)</span>) without covariates, this simplifies to the <strong>Wald estimand</strong>:</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Wald Estimand
</div>
</div>
<div class="callout-body-container callout-body">
<p><span id="eq-wald"><span class="math display">\[\beta = \frac{\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0]}{\E[T \mid Z{=}1] - \E[T \mid Z{=}0]}. \tag{7.4}\]</span></span></p>
<p>The numerator is the <em>reduced form</em>: the total effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(Y\)</span>. The denominator is the <em>first stage</em>: the effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(T\)</span>. The exclusion restriction guarantees the entire reduced form operates through <span class="math inline">\(T\)</span>; dividing by the first stage strips out the <span class="math inline">\(Z \to T\)</span> piece.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Estimation Deferred
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Wald estimand is an identification result: it expresses <span class="math inline">\(\beta\)</span> as a ratio of observable quantities. Estimation — how to consistently estimate this ratio from a finite sample, including the correct treatment of standard errors — is taken up in Chapter 13.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Returns to Schooling <span class="citation" data-cites="angrist1991does">(<a href="#ref-angrist1991does" role="doc-biblioref">Angrist and Krueger 1991</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the Mincer earnings equation <span class="math inline">\(\log W = \alpha + \beta S + \gamma^\top X + \varepsilon\)</span>, where <span class="math inline">\(S\)</span> is years of schooling and <span class="math inline">\(W\)</span> is wages, OLS is biased upward because unobserved ability <span class="math inline">\(U\)</span> raises both <span class="math inline">\(S\)</span> and <span class="math inline">\(W\)</span>. <span class="citation" data-cites="angrist1991does">Angrist and Krueger (<a href="#ref-angrist1991does" role="doc-biblioref">1991</a>)</span> use quarter of birth as <span class="math inline">\(Z\)</span>: proximity to mandatory school-leaving age at different birth quarters generates exogenous variation in completed schooling. The IV estimate of the return to schooling is approximately <span class="math inline">\(0.08\)</span>–<span class="math inline">\(0.10\)</span> per year.</p>
</div>
</div>
</section>
</section>
<section id="sec-why-matter" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-why-matter"><span class="header-section-number">7.4</span> Why the IV Assumptions Matter</h2>
<p>Each assumption is load-bearing, and each failure mode produces a distinct, quantifiable distortion of the Wald estimand.</p>
<p><strong>When relevance fails.</strong> If <span class="math inline">\(\pi = 0\)</span>, the Wald estimand is undefined. When <span class="math inline">\(\pi\)</span> is small but nonzero, the instrument is <em>weak</em>. The estimator’s variance diverges as <span class="math inline">\(\pi \to 0\)</span>, and finite-sample bias pulls the IV estimate toward the OLS estimate at a rate proportional to <span class="math inline">\(1/F\)</span>, where <span class="math inline">\(F\)</span> is the first-stage <span class="math inline">\(F\)</span>-statistic.</p>
<p><strong>When exclusion fails.</strong> If <span class="math inline">\(Y = \alpha + \beta T + \delta Z + \gamma^\top X + \varepsilon\)</span> with <span class="math inline">\(\delta \neq 0\)</span>, the Wald estimand converges to <span class="math inline">\(\beta + \delta/\pi\)</span>. The bias <span class="math inline">\(\delta/\pi\)</span> is amplified by a weak first stage: a small direct effect combined with a weak instrument can produce large bias. This is why a weak instrument with a plausible exclusion violation is not “nearly valid” — it may be severely misleading.</p>
<p><strong>When exogeneity fails.</strong> If <span class="math inline">\(\mathrm{Cov}(Z, \varepsilon \mid X) \neq 0\)</span>, the Wald estimand converges to <span class="math inline">\(\beta + \mathrm{Cov}(\varepsilon, Z)/\mathrm{Cov}(T, Z)\)</span>. Again the bias is amplified by weak instruments.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Assumption</strong></th>
<th><strong>Directly testable?</strong></th>
<th><strong>Basis for assessment</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Relevance</td>
<td>Association testable; causal claim design-based</td>
<td>First-stage <span class="math inline">\(F\)</span>-statistic; the causal <span class="math inline">\(Z \to T\)</span> link rests on the design</td>
</tr>
<tr class="even">
<td>Exogeneity</td>
<td>No</td>
<td>Institutional knowledge; randomization (if available); placebo regressions on pre-determined outcomes</td>
</tr>
<tr class="odd">
<td>Exclusion</td>
<td>No in just-identified case; partially in overidentified case</td>
<td>Institutional argument; overidentification test (<span class="math inline">\(J\)</span>-test, Chapter 13) checks mutual consistency but cannot confirm all instruments are valid <span class="citation" data-cites="kitagawa2015test">(<a href="#ref-kitagawa2015test" role="doc-biblioref">Kitagawa 2015</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="sec-lab" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sec-lab"><span class="header-section-number">7.5</span> Lab: OLS vs.&nbsp;IV Across Instrument Strengths</h2>
<p>This lab verifies the bias formulas numerically and traces the bias–variance tradeoff across the full range of instrument strength. It studies estimator behavior <em>conditional</em> on the IV assumptions being true; it does not address whether a proposed instrument is valid in an applied study.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>DGP for Lab 7
</div>
</div>
<div class="callout-body-container callout-body">
<p>The simulation implements the linear structural model of <a href="chapter_08.html#sec-linear" class="quarto-xref"><span>Section 8.7</span></a> with no covariates <span class="math inline">\(X\)</span>. Each replication draws <span class="math inline">\(n = 500\)</span> observations from: <span class="math display">\[Y_i = \beta T_i + \varepsilon_i, \qquad T_i = \pi Z_i + \eta_i,\]</span> with <span class="math inline">\(Z_i \overset{\mathrm{i.i.d.}}{\sim} N(0,1)\)</span> and structural errors: <span class="math display">\[\eta_i = U_i, \qquad \varepsilon_i = \rho U_i + \sqrt{1-\rho^2}\,\xi_i, \qquad U_i, \xi_i \overset{\mathrm{i.i.d.}}{\sim} N(0,1).\]</span> Fixed parameters: <span class="math inline">\(\beta = 1\)</span> (true causal effect), <span class="math inline">\(\rho = 0.8\)</span> (strong positive endogeneity). The first-stage coefficient <span class="math inline">\(\pi\)</span> is varied across eight values <span class="math inline">\(\pi \in \{0, 0.10, 0.15, 0.20, 0.30, 0.50, 1.00, 2.00\}\)</span>. The expected first-stage <span class="math inline">\(F\)</span>-statistic is approximately <span class="math inline">\(n\pi^2 = 500\pi^2\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Potential Outcomes Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The potential outcome is <span class="math inline">\(Y_i(t) = \beta t + \varepsilon_i\)</span>, so the individual treatment effect is constant: <span class="math inline">\(Y_i(t) - Y_i(t') = \beta(t-t')\)</span> for all <span class="math inline">\(i\)</span>. This is Framework 1: <span class="math inline">\(\beta\)</span> is simultaneously the ATE, ATT, and LATE.</p>
<p>The shared factor <span class="math inline">\(U_i\)</span> creates confounding: <span class="math inline">\(\mathrm{Cov}(Y_i(t), T_i) = \mathrm{Cov}(\varepsilon_i, \eta_i) = \rho \neq 0\)</span>, so unconfoundedness fails. The instrument <span class="math inline">\(Z_i\)</span> is drawn independently of <span class="math inline">\(U_i\)</span>, so <span class="math inline">\(Z_i \indep \varepsilon_i\)</span> (exogeneity); <span class="math inline">\(Z_i\)</span> does not appear in <span class="math inline">\(Y_i(t)\)</span> (exclusion); and <span class="math inline">\(Z_i\)</span> moves <span class="math inline">\(T_i\)</span> through <span class="math inline">\(\pi\)</span> (relevance). All three IV assumptions hold exactly by construction.</p>
</div>
</div>
<p><strong>Estimators.</strong> OLS regresses <span class="math inline">\(Y\)</span> on <span class="math inline">\(T\)</span>: <span class="math inline">\(\hat\beta_{\mathrm{OLS}} = \mathrm{Cov}(Y, T)/\mathrm{Var}(T)\)</span>, converging to <span class="math inline">\(1 + 0.8/(\pi^2+1)\)</span>. IV uses the Wald estimator: <span class="math inline">\(\hat\beta_{\mathrm{IV}} = \mathrm{Cov}(Y, Z)/\mathrm{Cov}(T, Z)\)</span>, consistent for <span class="math inline">\(\beta\)</span> for any <span class="math inline">\(\pi \neq 0\)</span>.</p>
<p><strong>Results</strong> (<span class="math inline">\(n = 500\)</span>, <span class="math inline">\(B = 2{,}000\)</span> replications, seed 2024):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\pi\)</span></th>
<th><span class="math inline">\(F\)</span></th>
<th>Theory bias</th>
<th>OLS mean</th>
<th>OLS RMSE</th>
<th>IV mean</th>
<th>IV RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.00</td>
<td>1</td>
<td>+0.800</td>
<td>1.801</td>
<td>0.802</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>0.10</td>
<td>6</td>
<td>+0.792</td>
<td>1.791</td>
<td>0.792</td>
<td>0.872</td>
<td>4.393</td>
</tr>
<tr class="odd">
<td>0.15</td>
<td>13</td>
<td>+0.782</td>
<td>1.782</td>
<td>0.783</td>
<td>0.764</td>
<td>6.491</td>
</tr>
<tr class="even">
<td>0.20</td>
<td>21</td>
<td>+0.769</td>
<td>1.769</td>
<td>0.770</td>
<td>0.940</td>
<td>0.385</td>
</tr>
<tr class="odd">
<td>0.30</td>
<td>46</td>
<td>+0.734</td>
<td>1.735</td>
<td>0.735</td>
<td>0.975</td>
<td>0.165</td>
</tr>
<tr class="even">
<td>0.50</td>
<td>127</td>
<td>+0.640</td>
<td>1.639</td>
<td>0.640</td>
<td>0.996</td>
<td>0.091</td>
</tr>
<tr class="odd">
<td>1.00</td>
<td>500</td>
<td>+0.400</td>
<td>1.401</td>
<td>0.402</td>
<td>0.999</td>
<td>0.045</td>
</tr>
<tr class="even">
<td>2.00</td>
<td>2006</td>
<td>+0.160</td>
<td>1.160</td>
<td>0.161</td>
<td>1.000</td>
<td>0.022</td>
</tr>
</tbody>
</table>
<p><strong>Lesson 1: The OLS bias formula is exact.</strong> The theory bias <span class="math inline">\(0.8/(\pi^2+1)\)</span> matches the simulated OLS bias to four decimal places across all eight values of <span class="math inline">\(\pi\)</span>. OLS is biased in the direction of <span class="math inline">\(\rho\)</span> at every value of <span class="math inline">\(\pi\)</span>, including <span class="math inline">\(\pi = 0\)</span>.</p>
<p><strong>Lesson 2: IV is consistent but has catastrophically heavy tails when the instrument is weak.</strong> At <span class="math inline">\(\pi = 0.10\)</span> (<span class="math inline">\(F \approx 6\)</span>) and <span class="math inline">\(\pi = 0.15\)</span> (<span class="math inline">\(F \approx 13\)</span>), the IV <em>mean</em> is far from the true value. The IV <em>median</em> is <span class="math inline">\(\approx 1.01\)</span> at both values, confirming consistency — the mean is dragged off by a small fraction of replications in which the first stage is near zero. Standard deviations of <span class="math inline">\(4.4\)</span> and <span class="math inline">\(6.5\)</span> make these estimates useless.</p>
<p><strong>Lesson 3: The RMSE crossover occurs near <span class="math inline">\(F \approx 20\)</span>.</strong> IV first beats OLS on RMSE at <span class="math inline">\(\pi = 0.20\)</span> (<span class="math inline">\(F \approx 21\)</span>): <span class="math inline">\(0.385 &lt; 0.770\)</span>. The Staiger–Stock rule of thumb (<span class="math inline">\(F \geq 10\)</span>) is slightly too lenient: at <span class="math inline">\(F \approx 13\)</span>, IV RMSE is still <span class="math inline">\(6.5\)</span>, nearly <span class="math inline">\(8\times\)</span> OLS. A more conservative threshold of <span class="math inline">\(F \geq 20\)</span>–<span class="math inline">\(25\)</span> is needed.</p>
<p><strong>Lesson 4: A strong instrument eliminates both problems.</strong> At <span class="math inline">\(\pi = 1.00\)</span> (<span class="math inline">\(F \approx 500\)</span>), IV RMSE <span class="math inline">\(= 0.045\)</span> while OLS RMSE <span class="math inline">\(= 0.402\)</span> — a <strong>9-fold</strong> improvement from IV. OLS efficiency is illusory: its small variance is offset by a large, persistent bias.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>RMSE Cannot Be the Only Criterion
</div>
</div>
<div class="callout-body-container callout-body">
<p>OLS has lower RMSE than IV for <span class="math inline">\(\pi &lt; 0.20\)</span> in this DGP. This does not vindicate OLS. An estimator with RMSE <span class="math inline">\(= 0.78\)</span> because it is biased by <span class="math inline">\(0.80\)</span> is useless for causal inference: the bias is systematic and does not shrink with sample size. As <span class="math inline">\(n \to \infty\)</span>, IV RMSE shrinks to zero while OLS RMSE stays at <span class="math inline">\(0.80\)</span>. The RMSE comparison is only meaningful in finite samples — it quantifies when a weak instrument is so unreliable that IV is not yet practically useful, but that is an argument for finding a stronger instrument, not for using OLS.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: The First-Stage <span class="math inline">\(F\)</span>-Statistic as a Diagnostic
</div>
</div>
<div class="callout-body-container callout-body">
<p>The formula <span class="math inline">\(F \approx n\pi^2\)</span> gives first-stage <span class="math inline">\(F\)</span>-statistics matching the simulation throughout. The <span class="citation" data-cites="bound1995problems">Bound et al. (<a href="#ref-bound1995problems" role="doc-biblioref">1995</a>)</span> threshold of <span class="math inline">\(F \geq 10\)</span> is widely used in practice and corresponds roughly to IV RMSE within a factor of two of the strong-instrument limit. This simulation suggests that threshold may understate the problem when endogeneity is strong (<span class="math inline">\(\rho = 0.8\)</span>): at <span class="math inline">\(F = 13\)</span> the IV RMSE is <span class="math inline">\(6.5\)</span>, far above any useful threshold. A researcher should report the first-stage <span class="math inline">\(F\)</span> alongside any IV estimate, and treat values below <span class="math inline">\(20\)</span>–<span class="math inline">\(25\)</span> with particular caution.</p>
</div>
</div>
</section>
<section id="sec-overid" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sec-overid"><span class="header-section-number">7.6</span> Multiple Instruments and Overidentification</h2>
<p>When there are exactly as many instruments as endogenous variables (<span class="math inline">\(q = p\)</span>), the model is <em>just-identified</em>. When <span class="math inline">\(q &gt; p\)</span>, the model is <em>overidentified</em>: the extra instruments impose additional moment restrictions that are testable. Under the homogeneous-effect linear model, every valid instrument must imply the same structural coefficient <span class="math inline">\(\beta\)</span>, so those extra restrictions are testable. Under heterogeneous treatment effects, valid instruments can legitimately identify <em>different</em> LATEs because they shift treatment for different complier populations.</p>
<p>The <strong>order condition</strong> (<span class="math inline">\(q \geq p\)</span>, counting requirement) and the <strong>rank condition</strong> (instruments are linearly independent in the first stage) are both necessary for identification. The Sargan–Hansen <span class="math inline">\(J\)</span>-test <span class="citation" data-cites="sargan1958estimation hansen1982large">(<a href="#ref-sargan1958estimation" role="doc-biblioref">Sargan 1958</a>; <a href="#ref-hansen1982large" role="doc-biblioref">Hansen 1982</a>)</span> formalizes the mutual-consistency check; rejection indicates at least one instrument either violates exogeneity or exclusion, or identifies a different LATE, but does not localize which. The test statistic and asymptotic distribution are derived in Chapter 13.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What Overidentification Does Not Do
</div>
</div>
<div class="callout-body-container callout-body">
<p>Passing the <span class="math inline">\(J\)</span>-test does not confirm that any instrument is valid. It only shows that the sample moment conditions are mutually compatible — a weaker conclusion than validity. Multiple invalid instruments can agree with one another if they share the same violation; consistent instruments are not necessarily valid ones. Overidentification is an opportunity for a consistency check, not a substitute for the institutional argument that makes a design credible.</p>
</div>
</div>
</section>
<section id="sec-late" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="sec-late"><span class="header-section-number">7.7</span> Heterogeneous Treatment Effects and the LATE Framework</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Framework 2: Heterogeneous Treatment Effects
</div>
</div>
<div class="callout-body-container callout-body">
<p>We now drop homogeneity and allow <span class="math inline">\(\tau_i = Y_i(1) - Y_i(0)\)</span> to vary across units. Throughout this section we work in the binary instrument, binary treatment setting (<span class="math inline">\(Z, T \in \{0,1\}\)</span>). In this setting, the Wald ratio generally no longer identifies the ATE. Instead, under an additional assumption of monotonicity, it identifies the <em>Local Average Treatment Effect</em> (LATE): the average treatment effect for the subpopulation whose treatment status is changed by the instrument.</p>
</div>
</div>
<section id="compliance-types" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="compliance-types"><span class="header-section-number">7.7.1</span> Compliance Types</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Compliance Types <span class="citation" data-cites="angrist1996identification">(<a href="#ref-angrist1996identification" role="doc-biblioref">Angrist et al. 1996</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>For binary <span class="math inline">\(Z, T \in \{0,1\}\)</span>, the four compliance types are defined by the pair of potential treatment decisions <span class="math inline">\((T_i(0), T_i(1))\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Compliance type</strong></th>
<th><span class="math inline">\(T_i(0)\)</span></th>
<th><span class="math inline">\(T_i(1)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Complier</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Always-taker</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Never-taker</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Defier</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>A <strong>complier</strong> takes treatment if and only if the instrument is switched on. An <strong>always-taker</strong> takes treatment regardless of <span class="math inline">\(Z\)</span>. A <strong>never-taker</strong> never takes treatment. A <strong>defier</strong> does the opposite of what the instrument suggests.</p>
</div>
</div>
<p>The instrument <span class="math inline">\(Z\)</span> only shifts treatment for <em>compliers</em>: always-takers and never-takers have the same treatment status regardless of <span class="math inline">\(Z\)</span>, so they contribute nothing to the denominator <span class="math inline">\(\E[T \mid Z{=}1] - \E[T \mid Z{=}0]\)</span>.</p>
</section>
<section id="the-monotonicity-assumption" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="the-monotonicity-assumption"><span class="header-section-number">7.7.2</span> The Monotonicity Assumption</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Monotonicity <span class="citation" data-cites="imbens1994identification">(<a href="#ref-imbens1994identification" role="doc-biblioref">Angrist and Imbens 1994</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The treatment assignment is <strong>monotone in</strong> <span class="math inline">\(Z\)</span> if <span class="math inline">\(T_i(1) \geq T_i(0)\)</span> for all <span class="math inline">\(i\)</span>. Equivalently: there are no defiers in the population.</p>
</div>
</div>
<p>Monotonicity is not a generic law of causal inference. It is a design-specific claim about how this particular instrument changes treatment behavior. Switching the instrument from 0 to 1 may induce some units to take treatment (compliers) and leave others unaffected (always-takers or never-takers), but it should not reverse anyone’s treatment decision.</p>
</section>
<section id="the-late-theorem" class="level3" data-number="7.7.3">
<h3 data-number="7.7.3" class="anchored" data-anchor-id="the-late-theorem"><span class="header-section-number">7.7.3</span> The LATE Theorem</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: LATE Theorem <span class="citation" data-cites="imbens1994identification">(<a href="#ref-imbens1994identification" role="doc-biblioref">Angrist and Imbens 1994</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose: (1) <em>Exogeneity (PO form):</em> <span class="math inline">\(Z \indep (Y(0), Y(1), T(0), T(1))\)</span>; (2) <em>Exclusion:</em> <span class="math inline">\(Y_i(t, z) = Y_i(t)\)</span> for all <span class="math inline">\(z\)</span>; (3) <em>Relevance:</em> <span class="math inline">\(\E[T(1) - T(0)] \neq 0\)</span>; (4) <em>Monotonicity:</em> <span class="math inline">\(T_i(1) \geq T_i(0)\)</span> for all <span class="math inline">\(i\)</span>. Then the Wald estimand identifies the <strong>Local Average Treatment Effect</strong> (LATE): <span class="math display">\[\frac{\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0]}{\E[T \mid Z{=}1] - \E[T \mid Z{=}0]} = \E[Y(1) - Y(0) \mid T_i(1) &gt; T_i(0)] \equiv \tau_{\mathrm{LATE}}.\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Denominator.</strong> By consistency for <span class="math inline">\(T\)</span> and exogeneity (<span class="math inline">\(Z \indep (T(0), T(1))\)</span>): <span class="math display">\[\E[T \mid Z{=}1] - \E[T \mid Z{=}0] = \E[T(1)] - \E[T(0)] = \E[T(1) - T(0)].\]</span> Monotonicity (no defiers) gives <span class="math inline">\(\E[T(1) - T(0)] = P(\text{complier})\)</span>, since always-takers contribute <span class="math inline">\(1-1=0\)</span> and never-takers contribute <span class="math inline">\(0-0=0\)</span>: <span class="math inline">\(\E[T \mid Z{=}1] - \E[T \mid Z{=}0] = P(\text{complier})\)</span>.</p>
<p><strong>Numerator.</strong> By consistency, exclusion, and exogeneity: <span class="math display">\[\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0] = \E[Y(T(1))] - \E[Y(T(0))] = \sum_c P(c)\,\E[Y(T_c(1)) - Y(T_c(0)) \mid \text{type}=c].\]</span> For always-takers: <span class="math inline">\(T(1) = T(0) = 1\)</span>, contribution <span class="math inline">\(= 0\)</span>. For never-takers: <span class="math inline">\(T(1) = T(0) = 0\)</span>, contribution <span class="math inline">\(= 0\)</span>. For compliers: <span class="math inline">\(T(1) = 1\)</span>, <span class="math inline">\(T(0) = 0\)</span>, so <span class="math inline">\(Y(T(1)) - Y(T(0)) = Y(1) - Y(0)\)</span>. No defiers by monotonicity. Therefore: <span class="math display">\[\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0] = P(\text{complier})\,\E[Y(1) - Y(0) \mid \text{complier}].\]</span></p>
<p><strong>Ratio.</strong> Dividing numerator by denominator: <span class="math inline">\(\tau_{\mathrm{LATE}} = \E[Y(1) - Y(0) \mid \text{complier}]\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: The Two Senses of “Local”
</div>
</div>
<div class="callout-body-container callout-body">
<p>The LATE is local in two senses: it is local to the complier group defined by <em>this</em> instrument, and local to the <em>particular instrument</em> that defines that group. A different instrument, even for the same treatment, will generally select a different complier population and identify a different LATE. This is developed in <a href="#sec-interpret" class="quarto-xref"><span>Section 7.8</span></a>.</p>
</div>
</div>
</section>
</section>
<section id="sec-interpret" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="sec-interpret"><span class="header-section-number">7.8</span> Interpreting IV Estimands</h2>
<section id="what-the-two-frameworks-say" class="level3" data-number="7.8.1">
<h3 data-number="7.8.1" class="anchored" data-anchor-id="what-the-two-frameworks-say"><span class="header-section-number">7.8.1</span> What the Two Frameworks Say</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Framework 1</strong> (linear, homogeneous)</th>
<th><strong>Framework 2</strong> (heterogeneous effects)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Key assumption</td>
<td><span class="math inline">\(\tau_i = \beta\)</span> for all <span class="math inline">\(i\)</span></td>
<td>Monotonicity; no defiers</td>
</tr>
<tr class="even">
<td>What IV identifies</td>
<td><span class="math inline">\(\beta = \text{ATE} = \text{ATT} = \text{LATE}\)</span></td>
<td><span class="math inline">\(\tau_{\mathrm{LATE}} = \E[\tau_i \mid \text{complier}]\)</span></td>
</tr>
<tr class="odd">
<td>Estimand depends on instrument?</td>
<td>No (same <span class="math inline">\(\beta\)</span> regardless of <span class="math inline">\(Z\)</span>)</td>
<td>Yes (different <span class="math inline">\(Z\)</span> <span class="math inline">\(\Rightarrow\)</span> different compliers <span class="math inline">\(\Rightarrow\)</span> different LATE)</td>
</tr>
<tr class="even">
<td>Required for ATE?</td>
<td>Yes, automatically</td>
<td>Only if all units are compliers or effects homogeneous</td>
</tr>
</tbody>
</table>
<p>Framework 1 is a special case of Framework 2: when <span class="math inline">\(\tau_i = \beta\)</span> for all <span class="math inline">\(i\)</span>, the LATE equals the ATE equals <span class="math inline">\(\beta\)</span>. In applied work, the default interpretation of the Wald estimand is the LATE; the ATE interpretation requires the additional homogeneity argument of Framework 1.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Same Formula, Different Estimand
</div>
</div>
<div class="callout-body-container callout-body">
<p>Across a range of fourth assumptions, the conditional Wald formula <span class="math inline">\(\mathrm{Cov}(Z, Y \mid X)/\mathrm{Cov}(Z, T \mid X)\)</span> serves as the identifying expression in many cases <span class="citation" data-cites="levis2024nonparametric">(<a href="#ref-levis2024nonparametric" role="doc-biblioref">Levis et al. 2024</a>)</span>. Two researchers using the same instrument and computing the same Wald ratio may be consistently estimating different causal quantities if they maintain different structural assumptions. The data alone cannot resolve which estimand the Wald ratio identifies; that determination requires the researcher to commit to a structural assumption about treatment response.</p>
</div>
</div>
</section>
<section id="when-does-late-equal-ate" class="level3" data-number="7.8.2">
<h3 data-number="7.8.2" class="anchored" data-anchor-id="when-does-late-equal-ate"><span class="header-section-number">7.8.2</span> When Does LATE Equal ATE?</h3>
<p>LATE equals ATE only under additional structure, most notably treatment-effect homogeneity. To see this, decompose the ATE by compliance type: <span class="math display">\[\text{ATE} = P(\text{co})\,\E[\tau_i \mid \text{co}] + P(\text{at})\,\E[\tau_i \mid \text{at}] + P(\text{nt})\,\E[\tau_i \mid \text{nt}].\]</span> The LATE equals only the first term divided by its probability weight. ATE and LATE coincide if and only if: (1) mean treatment effects are equal across compliance types, or (2) everyone is a complier, or (3) the average effects for always-takers and never-takers happen to equal the LATE — an untestable coincidence.</p>
</section>
<section id="different-instruments-different-estimands" class="level3" data-number="7.8.3">
<h3 data-number="7.8.3" class="anchored" data-anchor-id="different-instruments-different-estimands"><span class="header-section-number">7.8.3</span> Different Instruments, Different Estimands</h3>
<p>Because the LATE is specific to the complier population, and different instruments select different complier populations, two valid instruments for the same treatment can legitimately identify different LATEs. This is informative about treatment effect heterogeneity, not a contradiction.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Compulsory Schooling Laws vs.&nbsp;Distance to College <span class="citation" data-cites="angrist1991does card1995using">(<a href="#ref-angrist1991does" role="doc-biblioref">Angrist and Krueger 1991</a>; <a href="#ref-card1995using" role="doc-biblioref">Card 1995</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Compulsory schooling laws <span class="citation" data-cites="angrist1991does">(<a href="#ref-angrist1991does" role="doc-biblioref">Angrist and Krueger 1991</a>)</span> identify the return to schooling for students at the margin of dropping out — typically lower-income students. Distance to the nearest college <span class="citation" data-cites="card1995using">(<a href="#ref-card1995using" role="doc-biblioref">Card 1995</a>)</span> identifies the return for students deterred by geographic distance — again, disproportionately lower-income. Both instruments are valid; the LATEs can legitimately differ even if both are valid.</p>
</div>
</div>
</section>
<section id="the-policy-relevance-of-late" class="level3" data-number="7.8.4">
<h3 data-number="7.8.4" class="anchored" data-anchor-id="the-policy-relevance-of-late"><span class="header-section-number">7.8.4</span> The Policy Relevance of LATE</h3>
<p>For many policy questions, the LATE is exactly the right estimand. If a policy is designed to encourage a subset of the population to take treatment, then the effect on compliers (those who respond to the encouragement) is precisely what the policy-maker wants to know. When the ATE over the full population is required, IV alone is insufficient under heterogeneous effects; additional assumptions or a second instrument are needed to extrapolate from the LATE to the ATE.</p>
</section>
</section>
<section id="sec-practical" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="sec-practical"><span class="header-section-number">7.9</span> Practical Guidance on Defending an IV Design</h2>
<p>A researcher proposing an instrument should be able to answer five questions explicitly:</p>
<ol type="1">
<li><strong>What exactly is the instrument?</strong> Specify <span class="math inline">\(Z\)</span> precisely: its source of variation, the level at which it varies, and the population to which it applies.</li>
<li><strong>Why does it shift treatment?</strong> Articulate the causal mechanism by which <span class="math inline">\(Z\)</span> moves <span class="math inline">\(T\)</span>. The first-stage <span class="math inline">\(F\)</span>-statistic is a diagnostic for instrument strength, not a substitute for a causal account of the <span class="math inline">\(Z \to T\)</span> link.</li>
<li><strong>Why is it as-if random relative to latent outcome determinants?</strong> The most credible sources are designed randomization (lotteries, randomized encouragement), natural experiments, and shift-share designs <span class="citation" data-cites="bartik1991benefits goldsmith2020bartik">(<a href="#ref-bartik1991benefits" role="doc-biblioref">Bartik 1991</a>; <a href="#ref-goldsmith2020bartik" role="doc-biblioref">Goldsmith-Pinkham et al. 2020</a>)</span>. Placebo regressions on pre-determined outcomes provide partial evidence.</li>
<li><strong>Why can it affect the outcome only through treatment?</strong> Exclusion is untestable in just-identified models. A useful diagnostic: how large would the direct effect <span class="math inline">\(\delta\)</span> have to be, relative to <span class="math inline">\(\pi\)</span>, to overturn the estimated causal effect? When the first stage is weak, the answer is: not very large.</li>
<li><strong>What population margin does it shift?</strong> Identify the complier population. This determines the LATE that is being identified and governs the external validity of the estimates.</li>
</ol>
</section>
<section id="sec-kipp" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="sec-kipp"><span class="header-section-number">7.10</span> Applied Example: Charter School Lotteries and the KIPP Lynn Study</h2>
<p>This example illustrates a canonical randomized-encouragement IV design. The lottery randomizes <em>offer status</em> <span class="math inline">\(Z\)</span>, not actual treatment <span class="math inline">\(S\)</span> (years of KIPP attendance). Winning the lottery does not force a student to attend KIPP, and losing does not make later attendance impossible. Thus the lottery offer is the instrument and actual attendance is the endogenous treatment.</p>
<p><strong>Setting.</strong> KIPP (Knowledge Is Power Program) schools follow a “No Excuses” model: extended school days, longer academic year, selective teacher hiring, and strict behavioral norms. KIPP Academy Lynn was substantially oversubscribed beginning in 2005. Massachusetts law requires oversubscribed charter schools to select students by lottery, so the school conducted randomized admissions lotteries from 2005 through 2008. The outcome <span class="math inline">\(Y_{igt}\)</span> is the student’s standardized score on the Massachusetts MCAS, normalized to mean zero and standard deviation one within each subject–grade–year cell statewide.</p>
<p><strong>Mapping the three assumptions <span class="citation" data-cites="angrist2012benefits">(<a href="#ref-angrist2012benefits" role="doc-biblioref">Angrist et al. 2012</a>)</span>.</strong></p>
<p><em>Relevance.</em> Lottery winners were offered a seat and about 80% accepted; losers rarely enrolled elsewhere at KIPP. The first-stage regression yields a coefficient of approximately <span class="math inline">\(1.2\)</span>: lottery winners had spent about 1.2 more years at KIPP than lottery losers at the time of each MCAS exam. The first-stage <span class="math inline">\(F\)</span>-statistic is far above conventional thresholds.</p>
<p><em>Exogeneity.</em> Offer status was determined by randomly drawn lottery-sequence numbers, so independence holds by design. A joint test of covariate balance yields <span class="math inline">\(p = 0.615\)</span>, consistent with no pre-lottery differences.</p>
<p><em>Exclusion.</em> The offer merely provides access to a school; it does not itself deliver instruction. One potential violation is a discouragement effect: losing the lottery might demoralize students. The authors address this by noting that scores of lottery losers are typical of demographically comparable students in Lynn, inconsistent with large discouragement effects. Random assignment of the instrument does not, by itself, imply exclusion — it only guarantees exogeneity.</p>
<p><strong>First stage, reduced form, and 2SLS.</strong> The model is just-identified (one excluded instrument per endogenous variable), so the 2SLS estimator of <span class="math inline">\(\theta\)</span> (effect per year at KIPP) equals the ratio of the reduced-form coefficient on <span class="math inline">\(Z_i\)</span> to the first-stage coefficient <span class="math inline">\(\pi\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Subject</strong></th>
<th><strong>First stage</strong></th>
<th><strong>Reduced form</strong></th>
<th><strong>2SLS</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Math</td>
<td>1.221 (0.068)</td>
<td>0.430 (0.067)</td>
<td>0.352 (0.053)</td>
</tr>
<tr class="even">
<td>ELA</td>
<td>1.228 (0.068)</td>
<td>0.164 (0.073)</td>
<td>0.133 (0.059)</td>
</tr>
</tbody>
</table>
<p><em>Standard errors clustered at the student level. <span class="math inline">\(N = 833\)</span> student-by-test observations.</em></p>
<p>Each year at KIPP raises math scores by approximately <span class="math inline">\(0.35\sigma\)</span> and ELA scores by approximately <span class="math inline">\(0.13\sigma\)</span>. The reduced-form estimate for math (<span class="math inline">\(0.43\sigma\)</span>) is larger than the 2SLS estimate (<span class="math inline">\(0.35\sigma\)</span>) because the first stage exceeds 1: lottery winners accumulated somewhat more than one additional year at KIPP per unit of follow-up time.</p>
<p><strong>LATE interpretation.</strong> The 2SLS estimand <span class="math inline">\(\theta\)</span> is not the effect of KIPP on all students in Lynn, nor on all applicants — it is the average per-year treatment effect for the <em>lottery compliers</em>. Compliance is partial in both directions: some lottery winners do not enroll and some lottery losers eventually find entry.</p>
<p><strong>Treatment effect heterogeneity.</strong> Reading gains (<span class="math inline">\(\approx 0.13\sigma\)</span> overall) are driven almost entirely by students classified as having limited English proficiency (LEP, <span class="math inline">\(\approx 0.43\sigma\)</span>) and special education needs (SPED, <span class="math inline">\(\approx 0.27\sigma\)</span>); non-LEP, non-SPED students show negligible ELA gains. Math effects are large and positive across all subgroups but are largest for LEP and lower-achieving students. This connects directly to <a href="#sec-interpret" class="quarto-xref"><span>Section 7.8</span></a>: different instruments would identify distinct subpopulation LATEs; the overall 2SLS estimate is a weighted average of subgroup LATEs with weights proportional to each subgroup’s share of the complier population.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Lottery Design and Assumption Credibility <span class="citation" data-cites="angrist2009mostly">(<a href="#ref-angrist2009mostly" role="doc-biblioref">Angrist and Pischke 2009</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Instruments derived from <em>designed</em> randomization — lotteries, random assignment, randomized encouragement — provide the most transparent basis for the exogeneity assumption. Exogeneity within the applicant sample, conditional on application cohort, is not merely plausible — it follows from the randomization protocol. This is why lottery-based IV designs occupy a privileged position in the program evaluation literature. The exclusion restriction still requires institutional argument.</p>
</div>
</div>
</section>
<section id="sec-compare" class="level2" data-number="7.11">
<h2 data-number="7.11" class="anchored" data-anchor-id="sec-compare"><span class="header-section-number">7.11</span> IV versus Back-Door Adjustment</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Dimension</strong></th>
<th><strong>Back-door / propensity score</strong></th>
<th><strong>Instrumental variables</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Core assumption</td>
<td>All confounders observed: <span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span></td>
<td>Valid instrument: relevance, exogeneity, exclusion</td>
</tr>
<tr class="even">
<td>Unobserved confounders</td>
<td>Fatal: back-door adjustment fails</td>
<td>Permitted: IV routes around <span class="math inline">\(U\)</span></td>
</tr>
<tr class="odd">
<td>Estimand</td>
<td>ATE, ATT, or ATC; all coincide under homogeneity</td>
<td>LATE (compliers only); reduces to common <span class="math inline">\(\beta\)</span> under homogeneous effects</td>
</tr>
<tr class="even">
<td>Testability</td>
<td>Unconfoundedness is untestable; overlap is testable</td>
<td>Relevance testable; exogeneity and exclusion untestable (just-identified)</td>
</tr>
<tr class="odd">
<td>Main threat</td>
<td>Unmeasured confounder</td>
<td>Exclusion restriction violation</td>
</tr>
<tr class="even">
<td>Identifies ATE?</td>
<td>Yes, under strong ignorability</td>
<td>Only under homogeneous effects</td>
</tr>
</tbody>
</table>
<p><strong>Complementary failure modes.</strong> Back-door adjustment fails when <span class="math inline">\(X\)</span> does not capture all confounders. IV fails when the exclusion restriction is violated: the bias in the Wald estimand is <span class="math inline">\(\delta/\pi\)</span>, amplified by weak instruments. The two failures are orthogonal: back-door adjustment requires many observed covariates but tolerates no unobserved ones, while IV tolerates unobserved confounders but requires an instrument with no direct effect on the outcome.</p>
<p><strong>When both strategies are available.</strong> The <span class="citation" data-cites="hausman1978specification">Hausman (<a href="#ref-hausman1978specification" role="doc-biblioref">1978</a>)</span> endogeneity test compares OLS and IV: under the null that <span class="math inline">\(T\)</span> is exogenous given <span class="math inline">\(X\)</span>, both are consistent, and a large discrepancy is evidence of endogeneity. Under the null, an appropriately scaled quadratic form in <span class="math inline">\(\hat\beta_{\mathrm{IV}} - \hat\beta_{\mathrm{OLS}}\)</span> is asymptotically <span class="math inline">\(\chi^2_p\)</span>. Disagreement does not by itself tell us which method is wrong: the two strategies typically target different estimands (ATE vs.&nbsp;LATE), and disagreement can arise from legitimate effect heterogeneity rather than failure of either assumption.</p>
</section>
<section id="chapter-summary" class="level2" data-number="7.12">
<h2 data-number="7.12" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">7.12</span> Chapter Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Symbol</strong></th>
<th><strong>Meaning</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Z\)</span></td>
<td>Instrument</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\pi\)</span></td>
<td>First-stage coefficient: <span class="math inline">\(\E[\partial T/\partial Z]\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\rho\)</span></td>
<td>Endogeneity: <span class="math inline">\(\mathrm{Cov}(\varepsilon, \eta)/(\sigma\tau)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\tau_{\mathrm{LATE}}\)</span></td>
<td><span class="math inline">\(\E[Y(1) - Y(0) \mid T_i(1) &gt; T_i(0)]\)</span></td>
</tr>
<tr class="odd">
<td>Wald estimand</td>
<td><span class="math inline">\((\E[Y\mid Z{=}1]-\E[Y\mid Z{=}0])/(\E[T\mid Z{=}1]-\E[T\mid Z{=}0])\)</span></td>
</tr>
<tr class="even">
<td>Reduced form</td>
<td>Total effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(Y\)</span></td>
</tr>
<tr class="odd">
<td>First stage</td>
<td>Effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(T\)</span></td>
</tr>
</tbody>
</table>
<ol type="1">
<li><strong>IV identifies effects from exogenous treatment variation.</strong> When back-door adjustment fails because an unobserved <span class="math inline">\(U\)</span> creates a path <span class="math inline">\(T \leftarrow U \to Y\)</span>, a valid instrument <span class="math inline">\(Z\)</span> identifies the causal effect by exploiting only the component of treatment variation that <span class="math inline">\(Z\)</span> induces. IV does not block the confounding path — it avoids it.</li>
<li><strong>Three assumptions, ordered by testability.</strong> Relevance can be assessed with the first-stage <span class="math inline">\(F\)</span>-statistic (though the <span class="math inline">\(F\)</span>-statistic is a sample diagnostic). Exogeneity and exclusion must be defended by institutional knowledge, design logic, and causal structure. Each violated assumption produces a distinct, quantifiable bias, amplified by weak instruments.</li>
<li><strong>Framework 1: homogeneous-effect SEM <span class="math inline">\(\Rightarrow\)</span> Wald identifies <span class="math inline">\(\beta\)</span>.</strong> Under constant treatment effects and the linear structural model, the Wald estimand identifies <span class="math inline">\(\beta = \text{ATE} = \text{ATT} = \text{LATE}\)</span>.</li>
<li><strong>Framework 2: heterogeneity + monotonicity <span class="math inline">\(\Rightarrow\)</span> Wald identifies LATE.</strong> Under heterogeneous treatment effects and monotonicity, the Wald estimand identifies the average treatment effect for <em>compliers</em> only — those whose treatment status changes with the instrument, a latent subgroup defined by <span class="math inline">\((T(0), T(1))\)</span>.</li>
<li><strong>Different instruments identify different effects.</strong> The LATE depends on the instrument through the complier population it selects. This is informative about treatment effect heterogeneity, not a contradiction. LATE equals ATE only under additional structure.</li>
<li><strong>IV versus back-door adjustment.</strong> Complementary failure modes: back-door fails when confounders are unobserved; IV fails when the exclusion restriction is violated or the instrument is not truly exogenous.</li>
<li><strong>Estimation deferred to Chapter 13.</strong> This chapter establishes what IV identifies and under what assumptions. How the Wald ratio is estimated from finite data — reduced-form regression, two-stage least squares, asymptotic inference, and overidentification tests — is the subject of Chapter 13.</li>
</ol>
</section>
<section id="problems" class="level2" data-number="7.13">
<h2 data-number="7.13" class="anchored" data-anchor-id="problems"><span class="header-section-number">7.13</span> Problems</h2>
<p><strong>1. The three IV assumptions in three languages.</strong> Consider the DAG: <span class="math inline">\(\{Z \to T,\; T \to Y,\; U \to T,\; U \to Y,\; X \to T,\; X \to Y,\; X \to Z\}\)</span> with <span class="math inline">\(U\)</span> unobserved.</p>
<ol type="a">
<li>List all back-door paths from <span class="math inline">\(T\)</span> to <span class="math inline">\(Y\)</span>. Does <span class="math inline">\(X\)</span> alone satisfy the back-door criterion? Explain.</li>
<li>Verify the three IV assumptions using d-separation: (i) Relevance: show <span class="math inline">\(Z\)</span> and <span class="math inline">\(T\)</span> are not d-separated in <span class="math inline">\(\mathcal{G}\)</span>. (ii) Exogeneity: show <span class="math inline">\(Z \indep U \mid X\)</span> in <span class="math inline">\(\mathcal{G}\)</span>. (iii) Exclusion: show <span class="math inline">\(Y \indep Z \mid T, X\)</span> in <span class="math inline">\(\mathcal{G}_{\overline{T}}\)</span>.</li>
<li>Now add the arrow <span class="math inline">\(Z \to Y\)</span> to the DAG. Which IV assumption is violated? Show explicitly which step of the Wald derivation in <a href="chapter_08.html#sec-linear" class="quarto-xref"><span>Section 8.7</span></a> breaks down.</li>
<li>Translate each of the three IV assumptions into the structural language: write the equations for <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span> and identify which coefficient restriction corresponds to each assumption.</li>
</ol>
<p><strong>2. Bias under assumption violations.</strong> Let <span class="math inline">\(Y = \beta T + \varepsilon\)</span> and <span class="math inline">\(T = \pi Z + \eta\)</span> with <span class="math inline">\(\E[\varepsilon \mid Z] = 0\)</span> and <span class="math inline">\(\pi \neq 0\)</span>.</p>
<ol type="a">
<li>Starting from <span class="math inline">\(\E[Y \mid Z{=}1] - \E[Y \mid Z{=}0]\)</span>, substitute the structural equation for <span class="math inline">\(Y\)</span> and simplify. What role does exogeneity play?</li>
<li>Show that <span class="math inline">\(\E[T \mid Z{=}1] - \E[T \mid Z{=}0] = \pi\)</span> in the linear first-stage model.</li>
<li>Derive the Wald estimand and confirm it equals <span class="math inline">\(\beta\)</span>.</li>
<li>Now suppose the exclusion restriction fails and <span class="math inline">\(Y = \beta T + \delta Z + \varepsilon\)</span> with <span class="math inline">\(\delta \neq 0\)</span>. Derive the probability limit of the Wald estimator and confirm the bias formula from <a href="#sec-why-matter" class="quarto-xref"><span>Section 7.4</span></a>.</li>
<li>Suppose instead that exogeneity fails: <span class="math inline">\(\E[\varepsilon \mid Z] = cZ\)</span> for some constant <span class="math inline">\(c \neq 0\)</span>. Derive the probability limit of the Wald estimator and express the bias in terms of <span class="math inline">\(c\)</span> and <span class="math inline">\(\pi\)</span>. Compare the structure of this bias with the exclusion violation bias.</li>
</ol>
<p><strong>3. Order, rank, and the limits of overidentification.</strong> Consider a model with one endogenous variable <span class="math inline">\(T\)</span> and two instruments <span class="math inline">\(Z_1\)</span> and <span class="math inline">\(Z_2\)</span>, both satisfying exogeneity and exclusion.</p>
<ol type="a">
<li>State the order condition and verify it is satisfied.</li>
<li>State the rank condition. What would it mean geometrically if the rank condition failed — i.e., if <span class="math inline">\(Z_1\)</span> and <span class="math inline">\(Z_2\)</span> were perfectly collinear in the first-stage regression?</li>
<li>Explain intuitively why having two valid instruments rather than one should improve estimation precision.</li>
<li>Now suppose <span class="math inline">\(Z_1\)</span> is valid but <span class="math inline">\(Z_2\)</span> violates the exclusion restriction. Under what conditions does the Sargan–Hansen <span class="math inline">\(J\)</span>-test have power to detect <span class="math inline">\(Z_2\)</span>’s invalidity? Under what conditions does the test fail?</li>
<li>Why does passing the <span class="math inline">\(J\)</span>-test not confirm that both <span class="math inline">\(Z_1\)</span> and <span class="math inline">\(Z_2\)</span> are valid? Give a concrete example in which both instruments are invalid and the <span class="math inline">\(J\)</span>-test has no power.</li>
</ol>
<p><strong>4. Compliance types and the LATE.</strong> In a binary instrument, binary treatment study, suppose the population has: 30% compliers with average treatment effect <span class="math inline">\(\tau_c = 6\)</span>; 25% always-takers with <span class="math inline">\(\tau_a = 3\)</span>; 45% never-takers with <span class="math inline">\(\tau_n = 1\)</span>; no defiers.</p>
<ol type="a">
<li>Compute <span class="math inline">\(P(\text{complier}) = \E[T \mid Z{=}1] - \E[T \mid Z{=}0]\)</span>.</li>
<li>Compute the ATE as a weighted average of <span class="math inline">\(\tau_c\)</span>, <span class="math inline">\(\tau_a\)</span>, <span class="math inline">\(\tau_n\)</span> with appropriate weights.</li>
<li>The Wald estimand equals <span class="math inline">\(\tau_c = 6\)</span>. By how much does this overstate the ATE, and why?</li>
<li>A second study uses a different binary instrument <span class="math inline">\(Z'\)</span> with a complier population of 50% and a LATE of 2. Is this contradictory? What can you infer about the relative treatment effect in the two complier populations?</li>
<li>Explain, using compliance type language, why the denominator of the Wald estimand equals <span class="math inline">\(P(\text{complier})\)</span>.</li>
</ol>
<p><strong>5. The exclusion restriction: plausibility and violations.</strong> Evaluate the exclusion restriction for each proposed instrument. For each, state (i) whether the restriction is plausible and why; (ii) a specific mechanism by which it could be violated; and (iii) whether the violation would bias the IV estimate upward or downward.</p>
<ol type="a">
<li><strong>Instrument</strong>: rainfall in the home region of a politician, used as an instrument for government infrastructure spending. <strong>Outcome</strong>: local economic growth.</li>
<li><strong>Instrument</strong>: distance to the nearest hospital, used as an instrument for hospital admission. <strong>Outcome</strong>: 30-day mortality.</li>
<li><strong>Instrument</strong>: a randomly assigned financial incentive to enroll in a health screening program. <strong>Outcome</strong>: health status two years later.</li>
<li><strong>Instrument</strong>: lottery number in the Vietnam-era draft lottery, used as an instrument for military service. <strong>Outcome</strong>: lifetime earnings. [<em>This is the Angrist (1990) study; discuss why this instrument is widely regarded as satisfying the exclusion restriction.</em>]</li>
</ol>
<p><strong>6. IV versus back-door adjustment.</strong> A researcher studies the effect of job training (<span class="math inline">\(T\)</span>) on earnings (<span class="math inline">\(Y\)</span>). Two strategies are available: (A) a rich set of pre-treatment covariates <span class="math inline">\(X\)</span> and a propensity-score estimator; (B) a lottery that randomly selected units to be <em>offered</em> training (not required to attend), used as instrument <span class="math inline">\(Z\)</span>.</p>
<ol type="a">
<li>Under what assumption does strategy (A) identify the ATE? What specific unobserved variable would most plausibly violate this assumption?</li>
<li>Strategy (B) identifies a LATE. Describe the complier population in words. Is the LATE likely to be larger or smaller than the ATE in this setting? Explain.</li>
<li>Both strategies are implemented and yield estimates of $1,800 and $2,400 per year, respectively. Describe a Hausman-type test that uses both estimates. Under what null hypothesis does the test have an approximate <span class="math inline">\(\chi^2\)</span> distribution?</li>
<li>If the two estimates differ significantly, which strategy would you trust more and why? What additional evidence would help distinguish the two explanations (endogeneity bias in (A) versus LATE <span class="math inline">\(\neq\)</span> ATE in (B))?</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-angrist2012benefits" class="csl-entry" role="listitem">
Angrist, Joshua D., Susan M. Dynarski, Thomas J. Kane, Parag A. Pathak, and Christopher R. Walters. 2012. <span>“Who Benefits from <span>KIPP</span>?”</span> <em>Journal of Policy Analysis and Management</em> 31 (4): 837–60.
</div>
<div id="ref-imbens1994identification" class="csl-entry" role="listitem">
Angrist, Joshua D., and Guido W. Imbens. 1994. <span>“Identification and Estimation of Local Average Treatment Effects.”</span> <em>Econometrica</em> 62 (2): 467–75.
</div>
<div id="ref-angrist1996identification" class="csl-entry" role="listitem">
Angrist, Joshua D., Guido W. Imbens, and Donald B. Rubin. 1996. <span>“Identification of Causal Effects Using Instrumental Variables.”</span> <em>Journal of the American Statistical Association</em> 91 (434): 444–55.
</div>
<div id="ref-angrist1991does" class="csl-entry" role="listitem">
Angrist, Joshua D., and Alan B. Krueger. 1991. <span>“Does Compulsory School Attendance Affect Schooling and Earnings?”</span> <em>Quarterly Journal of Economics</em> 106 (4): 979–1014.
</div>
<div id="ref-angrist2009mostly" class="csl-entry" role="listitem">
Angrist, Joshua D., and Jörn-Steffen Pischke. 2009. <em>Mostly Harmless Econometrics: An Empiricist’s Companion</em>. Princeton University Press.
</div>
<div id="ref-bartik1991benefits" class="csl-entry" role="listitem">
Bartik, Timothy J. 1991. <em>Who Benefits from State and Local Economic Development Policies?</em> W.&nbsp;E.&nbsp;Upjohn Institute for Employment Research.
</div>
<div id="ref-bound1995problems" class="csl-entry" role="listitem">
Bound, John, David A. Jaeger, and Regina M. Baker. 1995. <span>“Problems with Instrumental Variables Estimation When the Correlation Between the Instruments and the Endogenous Explanatory Variable Is Weak.”</span> <em>Journal of the American Statistical Association</em> 90 (430): 443–50.
</div>
<div id="ref-card1995using" class="csl-entry" role="listitem">
Card, David. 1995. <span>“Using Geographic Variation in College Proximity to Estimate the Return to Schooling.”</span> In <em>Aspects of Labour Market Behaviour: Essays in Honour of <span>John Vanderkamp</span></em>, edited by Louis N. Christofides, E. Kenneth Grant, and Robert Swidinsky. University of Toronto Press.
</div>
<div id="ref-goldsmith2020bartik" class="csl-entry" role="listitem">
Goldsmith-Pinkham, Paul, Isaac Sorkin, and Henry Swift. 2020. <span>“Bartik Instruments: What, When, Why, and How.”</span> <em>American Economic Review</em> 110 (8): 2586–624.
</div>
<div id="ref-hansen1982large" class="csl-entry" role="listitem">
Hansen, Lars Peter. 1982. <span>“Large Sample Properties of Generalized Method of Moments Estimators.”</span> <em>Econometrica</em> 50 (4): 1029–54. <a href="https://doi.org/10.2307/1912775">https://doi.org/10.2307/1912775</a>.
</div>
<div id="ref-hausman1978specification" class="csl-entry" role="listitem">
Hausman, Jerry A. 1978. <span>“Specification Tests in Econometrics.”</span> <em>Econometrica</em> 46 (6): 1251–71.
</div>
<div id="ref-hernan2006instruments" class="csl-entry" role="listitem">
Hernán, Miguel A., and James M. Robins. 2006. <span>“Instruments for Causal Inference: An Epidemiologist’s Dream?”</span> <em>Epidemiology</em> 17 (4): 360–72.
</div>
<div id="ref-kitagawa2015test" class="csl-entry" role="listitem">
Kitagawa, Toru. 2015. <span>“A Test for Instrument Validity.”</span> <em>Econometrica</em> 83 (5): 2043–63. <a href="https://doi.org/10.3982/ECTA11974">https://doi.org/10.3982/ECTA11974</a>.
</div>
<div id="ref-levis2024nonparametric" class="csl-entry" role="listitem">
Levis, Alexander W., Edward H. Kennedy, and Luke Keele. 2024. <span>“Nonparametric Identification and Efficient Estimation of Causal Effects with Instrumental Variables.”</span> <em>arXiv Preprint arXiv:2402.09332</em>.
</div>
<div id="ref-sargan1958estimation" class="csl-entry" role="listitem">
Sargan, John D. 1958. <span>“The Estimation of Economic Relationships Using Instrumental Variables.”</span> <em>Econometrica</em> 26 (3): 393–415. <a href="https://doi.org/10.2307/1907619">https://doi.org/10.2307/1907619</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_06.html" class="pagination-link" aria-label="Propensity Score Methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_08.html" class="pagination-link" aria-label="Mediation and Front-Door Identification">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mediation and Front-Door Identification</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>