<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Propensity Score Methods – Theory and Methods in Causal Inference</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_07.html" rel="next">
<link href="./chapter_05.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    tags: 'ams',
    macros: {
      doop:   ["\\operatorname{do}"],
      indep:  ["\\perp\\!\\!\\!\\perp"],
      nindep: ["\\not\\!\\perp\\!\\!\\!\\perp"],
      E:      ["\\mathbb{E}"],
      Gcal:   ["\\mathcal{G}"],
      Pa:     ["\\mathrm{Pa}"],
      De:     ["\\mathrm{De}"],
      An:     ["\\mathrm{An}"],
      Nd:     ["\\mathrm{Nd}"],
      pto:    ["\\overset{p}{\\to}"],
      expit:  ["\\operatorname{expit}"]
    }
  }
};
</script>
<style>
.quarto-download-btn {
  background-color: #1e3864 !important;
  color: white !important;
  border: none !important;
  padding: 6px 14px !important;
  border-radius: 6px !important;
  font-weight: 600 !important;
  font-size: 0.85rem !important;
}
.quarto-download-btn:hover {
  background-color: #2e72b8 !important;
  color: white !important;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Theory and Methods in Causal Inference</a> 
        <div class="sidebar-tools-main">
    <a href="./Theory-and-Methods-in-Causal-Inference.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">DAGs and d-Separation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Do-Calculus and Identification Criteria</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Potential Outcomes and Adjustment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mediation and Front-Door Identification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Estimating Equations and Influence Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Doubly Robust Estimation and Semiparametric Efficiency</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Flexible Nuisance Estimation, Orthogonal Scores, and Cross-Fitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Graphical Intuition for Conditional Independence and d-Separation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Single World Intervention Graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_C.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Pathwise Differentiability and Efficient Influence Functions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-curse" id="toc-sec-curse" class="nav-link active" data-scroll-target="#sec-curse"><span class="header-section-number">6.1</span> Motivation: The Curse of Dimensionality</a></li>
  <li><a href="#sec-ps" id="toc-sec-ps" class="nav-link" data-scroll-target="#sec-ps"><span class="header-section-number">6.2</span> The Propensity Score</a>
  <ul class="collapse">
  <li><a href="#definition" id="toc-definition" class="nav-link" data-scroll-target="#definition"><span class="header-section-number">6.2.1</span> Definition</a></li>
  <li><a href="#the-balancing-property" id="toc-the-balancing-property" class="nav-link" data-scroll-target="#the-balancing-property"><span class="header-section-number">6.2.2</span> The Balancing Property</a></li>
  <li><a href="#the-propensity-score-theorem" id="toc-the-propensity-score-theorem" class="nav-link" data-scroll-target="#the-propensity-score-theorem"><span class="header-section-number">6.2.3</span> The Propensity Score Theorem</a></li>
  <li><a href="#the-propensity-score-is-the-coarsest-balancing-score" id="toc-the-propensity-score-is-the-coarsest-balancing-score" class="nav-link" data-scroll-target="#the-propensity-score-is-the-coarsest-balancing-score"><span class="header-section-number">6.2.4</span> The Propensity Score is the Coarsest Balancing Score</a></li>
  </ul></li>
  <li><a href="#sec-ps-estimation" id="toc-sec-ps-estimation" class="nav-link" data-scroll-target="#sec-ps-estimation"><span class="header-section-number">6.3</span> Estimation of the Propensity Score</a></li>
  <li><a href="#sec-matching" id="toc-sec-matching" class="nav-link" data-scroll-target="#sec-matching"><span class="header-section-number">6.4</span> Matching on the Propensity Score</a></li>
  <li><a href="#sec-ipw" id="toc-sec-ipw" class="nav-link" data-scroll-target="#sec-ipw"><span class="header-section-number">6.5</span> Inverse Probability Weighting</a>
  <ul class="collapse">
  <li><a href="#the-ipw-identification-formula" id="toc-the-ipw-identification-formula" class="nav-link" data-scroll-target="#the-ipw-identification-formula"><span class="header-section-number">6.5.1</span> The IPW Identification Formula</a></li>
  <li><a href="#the-horvitzthompson-and-hájek-estimators" id="toc-the-horvitzthompson-and-hájek-estimators" class="nav-link" data-scroll-target="#the-horvitzthompson-and-hájek-estimators"><span class="header-section-number">6.5.2</span> The Horvitz–Thompson and Hájek Estimators</a></li>
  </ul></li>
  <li><a href="#sec-overlap" id="toc-sec-overlap" class="nav-link" data-scroll-target="#sec-overlap"><span class="header-section-number">6.6</span> Overlap and Positivity</a>
  <ul class="collapse">
  <li><a href="#the-strict-overlap-condition" id="toc-the-strict-overlap-condition" class="nav-link" data-scroll-target="#the-strict-overlap-condition"><span class="header-section-number">6.6.1</span> The Strict Overlap Condition</a></li>
  <li><a href="#practical-consequences-of-near-violations" id="toc-practical-consequences-of-near-violations" class="nav-link" data-scroll-target="#practical-consequences-of-near-violations"><span class="header-section-number">6.6.2</span> Practical Consequences of Near-Violations</a></li>
  <li><a href="#trimming-strategies" id="toc-trimming-strategies" class="nav-link" data-scroll-target="#trimming-strategies"><span class="header-section-number">6.6.3</span> Trimming Strategies</a></li>
  </ul></li>
  <li><a href="#sec-lab" id="toc-sec-lab" class="nav-link" data-scroll-target="#sec-lab"><span class="header-section-number">6.7</span> Lab: Simulation Study of IPW and Matching Estimators</a>
  <ul class="collapse">
  <li><a href="#part-1-correctly-specified-propensity-score" id="toc-part-1-correctly-specified-propensity-score" class="nav-link" data-scroll-target="#part-1-correctly-specified-propensity-score"><span class="header-section-number">6.7.1</span> Part 1: Correctly Specified Propensity Score</a></li>
  <li><a href="#part-2-robustness-to-ps-model-misspecification" id="toc-part-2-robustness-to-ps-model-misspecification" class="nav-link" data-scroll-target="#part-2-robustness-to-ps-model-misspecification"><span class="header-section-number">6.7.2</span> Part 2: Robustness to PS Model Misspecification</a></li>
  </ul></li>
  <li><a href="#sec-limits" id="toc-sec-limits" class="nav-link" data-scroll-target="#sec-limits"><span class="header-section-number">6.8</span> The Limits of Propensity Score Methods</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.9</span> Summary</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems"><span class="header-section-number">6.10</span> Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this chapter, students should be able to:</p>
<ol type="1">
<li>Define the propensity score <span class="math inline">\(\pi(X) = P(T{=}1 \mid X)\)</span> and explain why it is a <em>balancing score</em>.</li>
<li>State and prove the Balancing Property (<span class="math inline">\(T \indep X \mid \pi(X)\)</span>) and the Propensity Score Theorem (strong ignorability given <span class="math inline">\(X\)</span> implies strong ignorability given <span class="math inline">\(\pi(X)\)</span>).</li>
<li>Describe standard methods for estimating the propensity score (logistic regression, machine learning) and the practical pitfalls of each.</li>
<li>Derive the IPW identification formula for the ATE and explain the role of the Horvitz–Thompson representation.</li>
<li>Distinguish the IPW estimator (targets ATE) from the nearest-neighbor matching estimator presented in this chapter (designed to target ATT).</li>
<li>Define strict overlap, describe the practical consequences of near-violations, and apply trimming strategies.</li>
<li>Articulate the fundamental limitation of propensity-score methods — the unconfoundedness assumption — and explain why this motivates instrumental variables (Chapter 7).</li>
</ol>
</div>
</div>
<section id="sec-curse" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-curse"><span class="header-section-number">6.1</span> Motivation: The Curse of Dimensionality</h2>
<p>Chapter 5 established that under strong ignorability, the ATE is identified by the back-door adjustment formula, and developed three estimation strategies: regression adjustment, standardization, and stratification. All three require, in practice, that we condition on a covariate vector <span class="math inline">\(X\)</span>. When <span class="math inline">\(X\)</span> is low-dimensional, this is feasible. When <span class="math inline">\(X\)</span> has many components, it is not.</p>
<p><strong>The problem.</strong> Stratification requires cells <span class="math inline">\(\{X = x\}\)</span> to contain both treated and control units. With <span class="math inline">\(p\)</span> binary covariates, there are <span class="math inline">\(2^p\)</span> cells. With <span class="math inline">\(p = 20\)</span>, that is over one million cells — most empty in any realistic sample. Regression adjustment imposes parametric structure to interpolate across cells, but extrapolation bias grows with dimension. The propensity score provides an elegant solution: rather than conditioning on the full vector <span class="math inline">\(X\)</span>, it is sufficient to condition on the scalar <span class="math inline">\(\pi(X) = P(T{=}1 \mid X)\)</span>.</p>
</section>
<section id="sec-ps" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-ps"><span class="header-section-number">6.2</span> The Propensity Score</h2>
<section id="definition" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="definition"><span class="header-section-number">6.2.1</span> Definition</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Propensity Score
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>propensity score</em> is the conditional probability of receiving treatment given the observed covariates: <span class="math display">\[\pi(X) \;=\; P(T{=}1 \mid X).\]</span></p>
</div>
</div>
<p>In a randomized experiment, <span class="math inline">\(\pi(X) = p\)</span> is constant (equal to the allocation probability), so there is nothing to estimate. In an observational study, <span class="math inline">\(\pi(X)\)</span> varies with <span class="math inline">\(X\)</span> and must be estimated from data.</p>
<p><strong>Connection to strong ignorability.</strong> Under strong ignorability <span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span>, the potential outcomes carry no further information about treatment assignment once <span class="math inline">\(X\)</span> is given: <span class="math display">\[P\bigl(T{=}1 \mid X,\, Y(0),\, Y(1)\bigr) = P(T{=}1 \mid X) = \pi(X).\]</span> This equality is a <em>consequence</em> of the ignorability assumption, not part of the definition of <span class="math inline">\(\pi(X)\)</span>.</p>
</section>
<section id="the-balancing-property" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="the-balancing-property"><span class="header-section-number">6.2.2</span> The Balancing Property</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: The Propensity Score is a Balancing Score
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="rosenbaum1983central">(Rosenbaum and Rubin 1983)</span> <span class="math inline">\(T \indep X \mid \pi(X)\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It suffices to show <span class="math inline">\(P(T{=}1 \mid X, \pi(X)) = P(T{=}1 \mid \pi(X))\)</span>. Since <span class="math inline">\(\pi(X)\)</span> is a deterministic function of <span class="math inline">\(X\)</span>, conditioning on both <span class="math inline">\(X\)</span> and <span class="math inline">\(\pi(X)\)</span> is the same as conditioning on <span class="math inline">\(X\)</span> alone: <span class="math display">\[P\bigl(T{=}1 \mid X, \pi(X)\bigr) = P(T{=}1 \mid X) = \pi(X) = P\bigl(T{=}1 \mid \pi(X)\bigr). \quad\square\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Covariate Balance and Design-Before-Analysis
</div>
</div>
<div class="callout-body-container callout-body">
<p>The balancing property implies <span class="math inline">\(f(X \mid T{=}1,\, \pi(x)) = f(X \mid T{=}0,\, \pi(x))\)</span>. Stratifying on a discretized <span class="math inline">\(\hat\pi(X)\)</span> and comparing covariate distributions within strata via standardized mean differences diagnoses whether the propensity score model achieves adequate balance, <em>without ever looking at <span class="math inline">\(Y\)</span></em>. Because the diagnostic does not involve the outcome, it cannot be used to “fish” for a preferred model specification, making the analysis more objective <span class="citation" data-cites="imbens2015causal">(Imbens and Rubin 2015)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Balancing Property is a statement about the <em>observed</em> covariate distribution. It says that within strata of <span class="math inline">\(\pi(X)\)</span>, the distribution of <span class="math inline">\(X\)</span> is the same in the treated and control groups. It does <em>not</em> say anything about unobserved confounders <span class="math inline">\(U\)</span>: if <span class="math inline">\(U\)</span> affects both <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span> and is not captured by <span class="math inline">\(X\)</span>, the balancing property fails to close the back-door path through <span class="math inline">\(U\)</span>.</p>
</div>
</div>
</section>
<section id="the-propensity-score-theorem" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="the-propensity-score-theorem"><span class="header-section-number">6.2.3</span> The Propensity Score Theorem</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: Propensity Score Theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="rosenbaum1983central">(Rosenbaum and Rubin 1983)</span> Suppose <span class="math inline">\((Y(0), Y(1)) \indep T \mid X\)</span>. Then for any balancing score <span class="math inline">\(b(X)\)</span>, <span class="math display">\[\bigl(Y(0),\, Y(1)\bigr) \;\indep\; T \;\Big|\; b(X).\]</span> In particular, taking <span class="math inline">\(b(X) = \pi(X)\)</span>: strong ignorability given <span class="math inline">\(X\)</span> implies strong ignorability given <span class="math inline">\(\pi(X)\)</span> alone, provided <span class="math inline">\(0 &lt; \pi(X) &lt; 1\)</span> almost surely.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We prove the result for <span class="math inline">\(b(X) = \pi(X)\)</span>. By the law of iterated expectations, for any <span class="math inline">\(t \in \{0,1\}\)</span>: <span class="math display">\[P\bigl(T{=}1 \mid Y(t),\, \pi(X)\bigr) = \E\bigl[P(T{=}1 \mid Y(t), X) \mid Y(t), \pi(X)\bigr].\]</span> By ignorability, <span class="math inline">\(T \indep Y(t) \mid X\)</span>, so <span class="math inline">\(P(T{=}1 \mid Y(t), X) = P(T{=}1 \mid X) = \pi(X)\)</span>. Therefore: <span class="math display">\[P\bigl(T{=}1 \mid Y(t),\, \pi(X)\bigr) = \E\bigl[\pi(X) \mid Y(t), \pi(X)\bigr] = \pi(X) = P(T{=}1 \mid \pi(X)).\]</span> Hence <span class="math inline">\(T \indep Y(t) \mid \pi(X)\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>The theorem gives an alternative identification formula: <span class="math display">\[\E[Y(t)] = \E\bigl[\E[Y \mid \pi(X),\, T{=}t]\bigr].\]</span> A common misconception is that the two conditional regressions <span class="math inline">\(\E[Y \mid \pi(X), T{=}t]\)</span> and <span class="math inline">\(\E[Y \mid X, T{=}t]\)</span> are equal. They are not: they are different functions and their pointwise values generally differ. The theorem guarantees only that their marginal expectations agree: <span class="math display">\[\E\bigl[\E[Y \mid \pi(X),\, T{=}t]\bigr] = \E\bigl[\E[Y \mid X,\, T{=}t]\bigr] = \E[Y(t)].\]</span></p>
</div>
</div>
</section>
<section id="the-propensity-score-is-the-coarsest-balancing-score" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="the-propensity-score-is-the-coarsest-balancing-score"><span class="header-section-number">6.2.4</span> The Propensity Score is the Coarsest Balancing Score</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lemma: The Propensity Score is the Coarsest Balancing Score
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="rosenbaum1983central">(Rosenbaum and Rubin 1983)</span> If <span class="math inline">\(b(X)\)</span> is any balancing score — that is, <span class="math inline">\(T \indep X \mid b(X)\)</span> — then <span class="math inline">\(\pi(X)\)</span> is a function of <span class="math inline">\(b(X)\)</span>: <span class="math inline">\(\pi(X) = g(b(X))\)</span> for some measurable function <span class="math inline">\(g\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since <span class="math inline">\(b(X)\)</span> is a balancing score, <span class="math inline">\(T \indep X \mid b(X)\)</span>, so <span class="math inline">\(P(T{=}1 \mid X,\, b(X)) = P(T{=}1 \mid b(X))\)</span>. But <span class="math inline">\(b(X)\)</span> is a function of <span class="math inline">\(X\)</span>: <span class="math display">\[\pi(X) = P(T{=}1 \mid X) = P\bigl(T{=}1 \mid X,\, b(X)\bigr) = P\bigl(T{=}1 \mid b(X)\bigr).\]</span> Hence <span class="math inline">\(\pi(X)\)</span> is a measurable function of <span class="math inline">\(b(X)\)</span> alone. <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
<p>The lemma says that <span class="math inline">\(\pi(X)\)</span> is the <em>smallest</em> sufficient statistic for <span class="math inline">\(T\)</span> among all functions of <span class="math inline">\(X\)</span>: any other balancing score retains at least as much information about <span class="math inline">\(X\)</span> as the propensity score does.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Dimension Reduction
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Propensity Score Theorem says that instead of adjusting for the full high-dimensional vector <span class="math inline">\(X\)</span>, it is sufficient to adjust for the scalar <span class="math inline">\(\pi(X)\)</span>. Identification of the ATE follows immediately: <span class="math display">\[\tau_{\mathrm{ATE}} = \E\bigl[\E[Y \mid T{=}1, \pi(X)] - \E[Y \mid T{=}0, \pi(X)]\bigr].\]</span></p>
</div>
</div>
</section>
</section>
<section id="sec-ps-estimation" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-ps-estimation"><span class="header-section-number">6.3</span> Estimation of the Propensity Score</h2>
<p>The true propensity score <span class="math inline">\(\pi(X) = P(T{=}1 \mid X)\)</span> is <em>unknown</em> in observational studies and must be estimated from the data.</p>
<p><strong>Logistic regression.</strong> The classical approach models <span class="math inline">\(\mathrm{logit}(\pi(X)) = X^\top \beta\)</span> and estimates <span class="math inline">\(\beta\)</span> by maximum likelihood. The fitted values <span class="math inline">\(\hat\pi(X_i) = \sigma(X_i^\top \hat\beta)\)</span> are used in place of the true propensity score.</p>
<p><strong>Machine learning estimators.</strong> When <span class="math inline">\(X\)</span> is high-dimensional or the true propensity score is nonlinear, machine learning methods — gradient boosted trees, random forests, regularized logistic regression (LASSO, ridge) — can estimate <span class="math inline">\(\pi(X)\)</span> more flexibly. A critical issue is <em>overfitting</em>: an estimator that perfectly separates treated and control units in-sample will produce estimated propensity scores near 0 or 1 everywhere, destroying overlap. Cross-fitting (Chapter 11) addresses this by estimating nuisance functions on held-out folds.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Propensity Score Estimation Is a Nuisance, Not the Goal
</div>
</div>
<div class="callout-body-container callout-body">
<p>The propensity score is estimated in order to construct a good estimator of <span class="math inline">\(\tau_{\mathrm{ATE}}\)</span>. Balancing tests diagnose whether the estimated score has achieved covariate balance, but they do <em>not</em> test whether unobserved confounders are balanced.</p>
</div>
</div>
</section>
<section id="sec-matching" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-matching"><span class="header-section-number">6.4</span> Matching on the Propensity Score</h2>
<p>The propensity score also motivates <em>matching</em>: for each treated unit <span class="math inline">\(i\)</span>, find a control unit <span class="math inline">\(j\)</span> with <span class="math inline">\(\hat\pi(X_j) \approx \hat\pi(X_i)\)</span>, and use <span class="math inline">\(Y_j\)</span> as a proxy for <span class="math inline">\(Y_i(0)\)</span> <span class="citation" data-cites="abadie2006large abadie2016matching">(Abadie and Imbens 2006, 2016)</span>. The resulting estimator of the ATT is: <span class="math display">\[\hat\tau_{\mathrm{ATT}} = \frac{1}{n_1}\sum_{i:\, T_i=1} \Bigl[Y_i - Y_{\hat\jmath(i)}\Bigr],\]</span> where <span class="math inline">\(\hat\jmath(i)\)</span> is the index of the matched control unit.</p>
<p><strong>One-to-one nearest neighbor matching.</strong> For each treated unit <span class="math inline">\(i\)</span>, find: <span class="math display">\[\hat\jmath(i) = \arg\min_{j:\, T_j=0} \bigl|\hat\pi(X_i) - \hat\pi(X_j)\bigr|.\]</span> Matching with replacement reduces bias (each control unit is available to every treated unit) but increases variance.</p>
<p><strong>Caliper matching.</strong> Restricts matches to pairs within a maximum distance <span class="math inline">\(\delta\)</span> on the propensity score scale. Treated units with no control match within the caliper are discarded, restricting the estimand to the subset of treated units with good overlap.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>Propensity score matching implicitly fits a nonparametric regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(\pi(X)\)</span> separately within each treatment arm. By the Propensity Score Theorem, <span class="math inline">\((Y(0), Y(1)) \indep T \mid \pi(X)\)</span>, so the conditional mean <span class="math inline">\(\E[Y(t) \mid \pi(X) = p]\)</span> is identified from observed data. Nearest-neighbor matching approximates this conditional mean at each observed <span class="math inline">\(\hat\pi(X_i)\)</span> by local constant regression on the scalar propensity score — feasible precisely because of the dimension reduction from <span class="math inline">\(X\)</span> to <span class="math inline">\(\pi(X)\)</span>.</p>
</div>
</div>
</section>
<section id="sec-ipw" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-ipw"><span class="header-section-number">6.5</span> Inverse Probability Weighting</h2>
<section id="the-ipw-identification-formula" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="the-ipw-identification-formula"><span class="header-section-number">6.5.1</span> The IPW Identification Formula</h3>
<p>Under strong ignorability, the ATE admits an alternative representation as an <em>inverse probability weighting</em> (IPW) formula: <span class="math display">\[\tau_{\mathrm{ATE}} = \E\!\left[\frac{T \cdot Y}{\pi(X)}\right] - \E\!\left[\frac{(1-T)\cdot Y}{1-\pi(X)}\right].\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: IPW Identification
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under strong ignorability (<span class="math inline">\((Y(0), Y(1)) \indep T \mid X\)</span> and <span class="math inline">\(0 &lt; \pi(X) &lt; 1\)</span>): <span class="math display">\[\E\!\left[\frac{T \cdot Y}{\pi(X)}\right] = \E[Y(1)].\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\E\!\left[\frac{TY}{\pi(X)}\right] = \E\!\left[\frac{TY(1)}{\pi(X)}\right] = \E\!\left[\E\!\left[\frac{TY(1)}{\pi(X)} \;\Big|\; X\right]\right] = \E\!\left[\frac{Y(1)}{\pi(X)}\, \E[T \mid X]\right] = \E\!\left[\frac{Y(1)}{\pi(X)}\, \pi(X)\right] = \E[Y(1)].\]</span> The first equality uses consistency (<span class="math inline">\(Y = Y(1)\)</span> when <span class="math inline">\(T{=}1\)</span>); the third uses ignorability (<span class="math inline">\(Y(1) \indep T \mid X\)</span>). <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
</section>
<section id="the-horvitzthompson-and-hájek-estimators" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="the-horvitzthompson-and-hájek-estimators"><span class="header-section-number">6.5.2</span> The Horvitz–Thompson and Hájek Estimators</h3>
<p>The <em>Horvitz–Thompson</em> (HT) IPW estimator: <span class="math display">\[\hat\tau_{\mathrm{IPW}} = \frac{1}{n}\sum_{i=1}^n \left[\frac{T_i Y_i}{\hat\pi(X_i)} - \frac{(1-T_i) Y_i}{1-\hat\pi(X_i)}\right].\]</span></p>
<p>This estimator is consistent when <span class="math inline">\(\hat\pi(X)\)</span> converges to <span class="math inline">\(\pi(X)\)</span>, but can be <em>inefficient</em> due to extreme weights. The <em>normalized</em> (Hájek) estimator divides by the sum of weights within each group and is often more stable: <span class="math display">\[\hat\tau_{\mathrm{HJ}} = \frac{\sum_i T_i Y_i / \hat\pi(X_i)}{\sum_i T_i / \hat\pi(X_i)} - \frac{\sum_i (1-T_i) Y_i / (1-\hat\pi(X_i))}{\sum_i (1-T_i) / (1-\hat\pi(X_i))}.\]</span></p>
<p>The efficient doubly-robust estimator (AIPW) of Chapter 10 combines the outcome model and the propensity score; under correct nuisance specification it achieves higher efficiency than either pure IPW or pure outcome regression alone.</p>
</section>
</section>
<section id="sec-overlap" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-overlap"><span class="header-section-number">6.6</span> Overlap and Positivity</h2>
<section id="the-strict-overlap-condition" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="the-strict-overlap-condition"><span class="header-section-number">6.6.1</span> The Strict Overlap Condition</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Strict Overlap (Positivity)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>strict overlap condition</em> requires: <span class="math display">\[0 &lt; \pi(X) &lt; 1 \quad \text{almost surely.}\]</span> Every unit has a positive probability of receiving either treatment or control, regardless of its covariate values.</p>
</div>
</div>
<p>Together with unconfoundedness, strict overlap constitutes <em>strong ignorability</em> <span class="citation" data-cites="rosenbaum1983central">(Rosenbaum and Rubin 1983)</span>.</p>
<p><strong>Why overlap is necessary.</strong> The identification formula requires that both <span class="math inline">\(\E[Y \mid T{=}1, X{=}x]\)</span> and <span class="math inline">\(\E[Y \mid T{=}0, X{=}x]\)</span> be defined for all <span class="math inline">\(x\)</span> in the support of <span class="math inline">\(X\)</span>. If <span class="math inline">\(\pi(x) = 0\)</span> for some <span class="math inline">\(x\)</span>, then no treated units exist with <span class="math inline">\(X = x\)</span>, so <span class="math inline">\(\E[Y \mid T{=}1, X{=}x]\)</span> is not estimable.</p>
</section>
<section id="practical-consequences-of-near-violations" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="practical-consequences-of-near-violations"><span class="header-section-number">6.6.2</span> Practical Consequences of Near-Violations</h3>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Near-Overlap Problems
</div>
</div>
<div class="callout-body-container callout-body">
<p>When <span class="math inline">\(\hat\pi(X_i)\)</span> is close to 0 or 1, the IPW weight <span class="math inline">\(1/\hat\pi(X_i)\)</span> or <span class="math inline">\(1/(1 - \hat\pi(X_i))\)</span> is very large. A small number of units with extreme weights can dominate the estimator, increasing variance dramatically.</p>
</div>
</div>
</section>
<section id="trimming-strategies" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="trimming-strategies"><span class="header-section-number">6.6.3</span> Trimming Strategies</h3>
<p><strong>Trimming by propensity score.</strong> Restrict the analysis to units with estimated propensity scores in <span class="math inline">\([\eta, 1-\eta]\)</span> for some small <span class="math inline">\(\eta &gt; 0\)</span>. The estimand changes to <span class="math inline">\(\tau_{\mathrm{trim}} = \E[Y(1) - Y(0) \mid \eta \le \pi(X) \le 1-\eta]\)</span>.</p>
<p><strong>Crump et al.&nbsp;(2009) rule.</strong> <span class="citation" data-cites="crump2009dealing">Crump et al. (2009)</span> derive the optimal trimming threshold minimizing the asymptotic variance of the trimmed ATE estimator. The rule <span class="math inline">\(\eta = 0.1\)</span> — trimming units with <span class="math inline">\(\pi(X) &lt; 0.1\)</span> or <span class="math inline">\(\pi(X) &gt; 0.9\)</span> — is a common default.</p>
<p><strong>ATT instead of ATE.</strong> When overlap fails at covariate values where <span class="math inline">\(\pi(X)\)</span> is near 1, re-targeting the estimand to <span class="math inline">\(\tau_{\mathrm{ATT}}\)</span> avoids the problem, since the ATT requires only <span class="math inline">\(\pi(X) &lt; 1\)</span> on the support of <span class="math inline">\(X\)</span> among the treated.</p>
</section>
</section>
<section id="sec-lab" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-lab"><span class="header-section-number">6.7</span> Lab: Simulation Study of IPW and Matching Estimators</h2>
<p>This lab compares five estimators on a five-covariate data-generating process with treatment-effect heterogeneity. With five continuous confounders, direct stratification is infeasible, making propensity-score methods the natural choice. The estimators span two estimands: the ATE (HT-ATE, HJ-ATE) and the ATT (HT-ATT, HJ-ATT, NNM).</p>
<section id="part-1-correctly-specified-propensity-score" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="part-1-correctly-specified-propensity-score"><span class="header-section-number">6.7.1</span> Part 1: Correctly Specified Propensity Score</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>DGP for Lab 6
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X_j \overset{\mathrm{i.i.d.}}{\sim} \mathrm{Normal}(0,1)\)</span> for <span class="math inline">\(j = 1, \ldots, 5\)</span>. The true propensity score is: <span id="eq-dgp-ps"><span class="math display">\[\pi(X) = \mathrm{expit}(-0.5 + 0.8X_1 + 0.5X_2 - 0.3X_3 + 0.2X_4 + 0.1X_5), \tag{6.1}\]</span></span> giving <span class="math inline">\(P(T{=}1) \approx 0.40\)</span>. The potential outcomes are: <span id="eq-dgp-po"><span class="math display">\[Y(t) = (1 + 0.5X_1)\cdot t + 8 + 0.8X_1 + 0.5X_2 + 0.4X_3 + 0.3X_4 + 0.2X_5 + \varepsilon, \quad \varepsilon \sim \mathrm{N}(0,1). \tag{6.2}\]</span></span></p>
<p>The CATE is <span class="math inline">\(\tau(X) = 1 + 0.5X_1\)</span>. Because <span class="math inline">\(\E[X_1] = 0\)</span>: <span class="math inline">\(\tau_{\mathrm{ATE}} = 1.000\)</span> (exact). Because <span class="math inline">\(\pi(X)\)</span> is increasing in <span class="math inline">\(X_1\)</span>, treated units have higher <span class="math inline">\(X_1\)</span> on average: <span class="math inline">\(\tau_{\mathrm{ATT}} \approx 1.199\)</span> (oracle run, <span class="math inline">\(n = 10^7\)</span>). The gap <span class="math inline">\(\approx 0.199\)</span> reflects a selection effect: units most likely to be treated also tend to have larger individual treatment effects. Strong ignorability holds by construction.</p>
</div>
</div>
<p><strong>Five estimators</strong> are compared under both true and estimated propensity scores. Under the estimated score, <span class="math inline">\(\hat\pi(X)\)</span> is obtained by correctly specified logistic regression of <span class="math inline">\(T\)</span> on <span class="math inline">\((X_1, \ldots, X_5)\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Estimator</strong></th>
<th><strong>Formula</strong></th>
<th><strong>Estimand</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HT-ATE</td>
<td><span class="math inline">\(\frac{1}{n}\sum_i \left[\frac{T_i Y_i}{\hat\pi(X_i)} - \frac{(1-T_i) Y_i}{1-\hat\pi(X_i)}\right]\)</span></td>
<td>ATE</td>
</tr>
<tr class="even">
<td>HJ-ATE</td>
<td>Hájek-normalized HT</td>
<td>ATE</td>
</tr>
<tr class="odd">
<td>HT-ATT</td>
<td><span class="math inline">\(\frac{1}{n_1}\sum_{T_i=1} Y_i - \frac{1}{n_1}\sum_{T_i=0}\frac{\hat\pi(X_i)}{1-\hat\pi(X_i)} Y_i\)</span></td>
<td>ATT</td>
</tr>
<tr class="even">
<td>HJ-ATT</td>
<td>Self-normalized version of HT-ATT (control arm only)</td>
<td>ATT</td>
</tr>
<tr class="odd">
<td>NNM</td>
<td><span class="math inline">\(\frac{1}{n_1}\sum_{T_i=1}[Y_i - Y_{\hat\jmath(i)}]\)</span>, 1:1 with replacement</td>
<td>ATT</td>
</tr>
</tbody>
</table>
<p><strong>Results.</strong> <span class="math inline">\(n = 1{,}000\)</span>, <span class="math inline">\(B = 2{,}000\)</span> replications, seed 42.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><strong>PS</strong></th>
<th><strong>Estimator</strong></th>
<th><strong>Estimand</strong></th>
<th><strong>Mean</strong></th>
<th><strong>Bias</strong></th>
<th><strong>SD</strong></th>
<th><strong>RMSE</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Known</td>
<td>HT-ATE</td>
<td>ATE</td>
<td>1.008</td>
<td>+0.008</td>
<td>0.626</td>
<td>0.626</td>
</tr>
<tr class="even">
<td>Known</td>
<td>HJ-ATE</td>
<td>ATE</td>
<td>1.003</td>
<td>+0.003</td>
<td>0.145</td>
<td>0.145</td>
</tr>
<tr class="odd">
<td>Known</td>
<td>HT-ATT</td>
<td>ATT</td>
<td>1.184</td>
<td>−0.016</td>
<td>0.725</td>
<td>0.725</td>
</tr>
<tr class="even">
<td>Known</td>
<td>HJ-ATT</td>
<td>ATT</td>
<td>1.203</td>
<td>+0.003</td>
<td>0.131</td>
<td>0.131</td>
</tr>
<tr class="odd">
<td>Known</td>
<td>NNM</td>
<td>ATT</td>
<td>1.207</td>
<td>+0.008</td>
<td>0.130</td>
<td>0.130</td>
</tr>
<tr class="even">
<td>Estimated</td>
<td>HT-ATE</td>
<td>ATE</td>
<td>0.998</td>
<td>−0.002</td>
<td>0.194</td>
<td>0.194</td>
</tr>
<tr class="odd">
<td>Estimated</td>
<td>HJ-ATE</td>
<td>ATE</td>
<td>1.002</td>
<td>+0.002</td>
<td>0.102</td>
<td>0.103</td>
</tr>
<tr class="even">
<td>Estimated</td>
<td>HT-ATT</td>
<td>ATT</td>
<td>1.202</td>
<td>+0.002</td>
<td>0.251</td>
<td>0.251</td>
</tr>
<tr class="odd">
<td>Estimated</td>
<td>HJ-ATT</td>
<td>ATT</td>
<td>1.202</td>
<td>+0.002</td>
<td>0.101</td>
<td>0.101</td>
</tr>
<tr class="even">
<td>Estimated</td>
<td>NNM</td>
<td>ATT</td>
<td>1.205</td>
<td>+0.006</td>
<td>0.121</td>
<td>0.121</td>
</tr>
</tbody>
</table>
<p>Five lessons stand out. <strong>1.</strong> Hájek normalization is essential when outcomes are non-centered: HT-ATE achieves SD <span class="math inline">\(= 0.626\)</span> vs.&nbsp;HJ-ATE SD <span class="math inline">\(= 0.145\)</span> — a 4.3-fold reduction. <strong>2.</strong> The same problem afflicts ATT: HT-ATT SD <span class="math inline">\(= 0.725\)</span> vs.&nbsp;HJ-ATT SD <span class="math inline">\(= 0.131\)</span> — a 5.5-fold reduction. <strong>3.</strong> HJ-ATT and NNM converge to the same ATT target with nearly identical efficiency (SD 0.131 vs.&nbsp;0.130 under known PS). <strong>4.</strong> The ATE–ATT gap of <span class="math inline">\(\approx 0.199\)</span> is a real difference in estimands, not a bias — declaring the estimand before looking at results is non-negotiable. <strong>5.</strong> Estimated PS collapses HT variance; HJ-ATT with estimated PS (SD <span class="math inline">\(= 0.101\)</span>) beats NNM (SD <span class="math inline">\(= 0.121\)</span>), illustrating the efficiency gain of a well-estimated score.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Estimand Must Be Chosen Before the Estimator
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this DGP, <span class="math inline">\(\tau_{\mathrm{ATE}} = 1.000\)</span> and <span class="math inline">\(\tau_{\mathrm{ATT}} \approx 1.199\)</span>. The gap arises because treatment-effect heterogeneity is correlated with propensity for treatment <span class="citation" data-cites="imbens2015causal">(Imbens and Rubin 2015)</span> — individuals often select into treatment partly because they anticipate larger benefits. A researcher who applies NNM and reports its output against the ATE benchmark of <span class="math inline">\(1.000\)</span> would conclude the estimator has <span class="math inline">\(20\%\)</span> bias; in fact it is unbiased for the correct target.</p>
</div>
</div>
</section>
<section id="part-2-robustness-to-ps-model-misspecification" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="part-2-robustness-to-ps-model-misspecification"><span class="header-section-number">6.7.2</span> Part 2: Robustness to PS Model Misspecification</h3>
<p>Part 1 used a correctly specified logistic propensity model. Part 2 introduces a <em>nonlinear</em> true propensity score: <span id="eq-dgp-ps2"><span class="math display">\[\pi^*(X) = \mathrm{expit}(-0.5 + 0.8X_1 + 0.5X_1^2 + 0.2X_4 + 0.1X_5), \tag{6.3}\]</span></span> with a U-shaped surface in <span class="math inline">\(X_1\)</span>. The true ATE remains <span class="math inline">\(1.000\)</span> (exact); the ATT changes to <span class="math inline">\(\approx 1.152\)</span>. The <em>estimated</em> PS is still a linear logistic regression that omits <span class="math inline">\(X_1^2\)</span> — misspecified.</p>
<p><strong>Results.</strong> True ATE <span class="math inline">\(= 1.000\)</span>; true ATT <span class="math inline">\(\approx 1.152\)</span>. <span class="math inline">\(n = 1{,}000\)</span>, <span class="math inline">\(B = 2{,}000\)</span> replications.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><strong>PS</strong></th>
<th><strong>Estimator</strong></th>
<th><strong>Estimand</strong></th>
<th><strong>Mean</strong></th>
<th><strong>Bias</strong></th>
<th><strong>SD</strong></th>
<th><strong>RMSE</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>True</td>
<td>HT-ATE</td>
<td>ATE</td>
<td>1.028</td>
<td>+0.028</td>
<td>0.824</td>
<td>0.825</td>
</tr>
<tr class="even">
<td>True</td>
<td>HJ-ATE</td>
<td>ATE</td>
<td>1.013</td>
<td>+0.013</td>
<td>0.152</td>
<td>0.152</td>
</tr>
<tr class="odd">
<td>True</td>
<td>HT-ATT</td>
<td>ATT</td>
<td>1.186</td>
<td>+0.034</td>
<td>1.333</td>
<td>1.333</td>
</tr>
<tr class="even">
<td>True</td>
<td>HJ-ATT</td>
<td>ATT</td>
<td>1.183</td>
<td>+0.031</td>
<td>0.212</td>
<td>0.215</td>
</tr>
<tr class="odd">
<td>True</td>
<td>NNM</td>
<td>ATT</td>
<td>1.178</td>
<td>+0.026</td>
<td>0.175</td>
<td>0.177</td>
</tr>
<tr class="even">
<td>Misspecified</td>
<td>HT-ATE</td>
<td>ATE</td>
<td>1.478</td>
<td>+0.478</td>
<td>0.147</td>
<td>0.501</td>
</tr>
<tr class="odd">
<td>Misspecified</td>
<td>HJ-ATE</td>
<td>ATE</td>
<td>0.861</td>
<td>−0.139</td>
<td>0.087</td>
<td>0.164</td>
</tr>
<tr class="even">
<td>Misspecified</td>
<td>HT-ATT</td>
<td>ATT</td>
<td>1.780</td>
<td>+0.628</td>
<td>0.162</td>
<td>0.649</td>
</tr>
<tr class="odd">
<td>Misspecified</td>
<td>HJ-ATT</td>
<td>ATT</td>
<td>1.306</td>
<td>+0.154</td>
<td>0.081</td>
<td>0.174</td>
</tr>
<tr class="even">
<td>Misspecified</td>
<td>NNM</td>
<td>ATT</td>
<td>1.172</td>
<td>+0.020</td>
<td>0.138</td>
<td>0.139</td>
</tr>
</tbody>
</table>
<p>Three lessons complete the picture. <strong>6.</strong> PS misspecification makes all IPW estimators inconsistent; Hájek normalization is a variance correction only — it cannot fix a structurally wrong model. Note also that HJ-ATE and HT-ATE have biases in <em>opposite directions</em> (<span class="math inline">\(-0.139\)</span> vs.&nbsp;<span class="math inline">\(+0.478\)</span>) because the two estimators respond differently to the systematic over/underestimation of the U-shaped score. <strong>7.</strong> NNM is substantially more robust: its bias under misspecification (<span class="math inline">\(+0.020\)</span>) is far smaller than any IPW estimator, because matching relies on local covariate similarity rather than a globally correct weighting function.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>IPW Needs a Correct PS Model; Matching Needs Covariate Balance
</div>
</div>
<div class="callout-body-container callout-body">
<p>IPW is a <em>model-dependent</em> estimator: consistency relies on correct PS specification. Matching is a <em>design-dependent</em> estimator: consistency relies on matched pairs being approximately balanced. This condition can hold even when the PS model is wrong, provided the estimated score still separates units well enough that close matches imply closeness on the full covariate vector. The cost is efficiency: when the PS model is correct, matching leaves variance on the table relative to IPW. Neither dominates unconditionally <span class="citation" data-cites="yang2016multilevel yang2023multiply">(Yang et al. 2016; Yang and Zhang 2023)</span>.</p>
</div>
</div>
<p><strong>Head-to-head comparison of HJ-ATT and NNM:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Estimator</strong></th>
<th><strong>Bias (Correct PS)</strong></th>
<th><strong>RMSE (Correct PS)</strong></th>
<th><strong>Bias (Misspecified PS)</strong></th>
<th><strong>RMSE (Misspecified PS)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HJ-ATT</td>
<td>+0.002</td>
<td>0.101</td>
<td>+0.154</td>
<td>0.174</td>
</tr>
<tr class="even">
<td>NNM</td>
<td>+0.006</td>
<td>0.121</td>
<td>+0.020</td>
<td>0.139</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-limits" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="sec-limits"><span class="header-section-number">6.8</span> The Limits of Propensity Score Methods</h2>
<p>Every result in this chapter — the Propensity Score Theorem, the IPW identification formula, the matching estimator — rests on the unconfoundedness assumption: <span class="math display">\[(Y(0),\, Y(1)) \;\indep\; T \;\Big|\; X.\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Design-Based vs.&nbsp;Model-Based Identification
</div>
</div>
<div class="callout-body-container callout-body">
<p>Randomization <em>guarantees</em> ignorability: by construction, no back-door paths exist. Propensity-score adjustment <em>assumes</em> ignorability: the analyst must argue from subject-matter knowledge that all confounders have been measured. This distinction is fundamental. No statistical test can confirm unconfoundedness from observed data alone (Chapter 5). Sensitivity analysis can quantify how large an unobserved confounder would have to be to overturn a conclusion, but cannot confirm the assumption.</p>
</div>
</div>
<p>When unobserved confounders are present, propensity score adjustment fails and an instrumental variable is needed to identify the causal effect. Instrumental variables take a different approach: instead of blocking the confounding path <span class="math inline">\(T \leftarrow U \to Y\)</span>, they isolate variation in <span class="math inline">\(T\)</span> induced by an external source <span class="math inline">\(Z\)</span> independent of <span class="math inline">\(U\)</span>. This is derived formally in Chapter 7.</p>
</section>
<section id="summary" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.9</span> Summary</h2>
<ol type="1">
<li><p><strong>The propensity score reduces dimension.</strong> Under unconfoundedness, <span class="math inline">\(\pi(X) = P(T{=}1 \mid X)\)</span> is a <em>balancing score</em>: <span class="math inline">\(T \indep X \mid \pi(X)\)</span>. Consequently, <span class="math inline">\((Y(0),Y(1)) \indep T \mid \pi(X)\)</span>, so identification requires adjustment for the scalar <span class="math inline">\(\pi(X)\)</span> alone.</p></li>
<li><p><strong>IPW identification.</strong> The ATE is identified as <span class="math inline">\(\E[TY/\pi(X)] - \E[(1-T)Y/(1-\pi(X))]\)</span> under strong ignorability. The Horvitz–Thompson IPW estimator is consistent but sensitive to extreme weights; the Hájek variant is often more stable. AIPW (Chapter 10) achieves higher efficiency under correct nuisance specification.</p></li>
<li><p><strong>The matching procedure in this chapter targets the ATT.</strong> The nearest-neighbor matching estimator finds control units with similar propensity scores to each treated unit. It differs fundamentally from IPW weighting in estimand and methodology, and is more robust to PS misspecification.</p></li>
<li><p><strong>Strict overlap is non-negotiable.</strong> The condition <span class="math inline">\(0 &lt; \pi(X) &lt; 1\)</span> a.s. is necessary for identification of the ATE. Near-violations create extreme IPW weights and large variance; trimming strategies address this at the cost of restricting the estimand.</p></li>
<li><p><strong>The fundamental limitation.</strong> Unconfoundedness <span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span> is a strong, untestable assumption. When unobserved confounders are present, propensity score adjustment fails and an instrumental variable is needed.</p></li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Design</strong></th>
<th><strong>Key assumption</strong></th>
<th><strong>Identified estimand</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Randomized experiment</td>
<td><span class="math inline">\((Y(0),Y(1)) \indep T\)</span> (by design)</td>
<td>ATE</td>
</tr>
<tr class="even">
<td>Propensity-score adjustment</td>
<td><span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span> (unconfoundedness)</td>
<td>ATE or ATT</td>
</tr>
<tr class="odd">
<td>Instrumental variables</td>
<td>Relevance, exogeneity, exclusion</td>
<td>LATE (compliers)</td>
</tr>
</tbody>
</table>
</section>
<section id="problems" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="problems"><span class="header-section-number">6.10</span> Problems</h2>
<p><strong>1. Propensity score and balancing.</strong> Suppose <span class="math inline">\(X = (X_1, X_2)\)</span>, where <span class="math inline">\(X_1\)</span> is binary and <span class="math inline">\(X_2\)</span> is continuous. The propensity score model is correctly specified as <span class="math inline">\(\mathrm{logit}(\pi(X)) = \beta_0 + \beta_1 X_1 + \beta_2 X_2\)</span>.</p>
<ol type="a">
<li>State and prove the Balancing Property <span class="math inline">\(T \indep X \mid \pi(X)\)</span>.</li>
<li>Two units <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> have <span class="math inline">\(X_i = (1, 2.3)\)</span> and <span class="math inline">\(X_j = (0, 3.5)\)</span> but <span class="math inline">\(\hat\pi(X_i) = \hat\pi(X_j) = 0.4\)</span>. If <span class="math inline">\(i\)</span> is treated and <span class="math inline">\(j\)</span> is control, explain why comparing <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(Y_j\)</span> is a valid approximation to the counterfactual comparison, and what assumption is required.</li>
<li>Explain why matching on <span class="math inline">\(\hat\pi(X)\)</span> is <em>not</em> the same as matching on <span class="math inline">\(X\)</span> directly. Under what conditions do they give the same answer?</li>
</ol>
<p><strong>2. ATE, ATT, and propensity score weighting.</strong> A dataset has <span class="math inline">\(n = 1000\)</span> observations with estimated propensity scores <span class="math inline">\(\hat\pi(X_i)\)</span> and <span class="math inline">\(n_1 = 400\)</span> treated units.</p>
<ol type="a">
<li>Write the Horvitz–Thompson IPW estimator of the ATE as a weighted sum of observed outcomes <span class="math inline">\(Y_i\)</span>. What weights do treated units receive? What weights do control units receive?</li>
<li>Derive an analogous IPW estimator for the ATT. (<em>Hint</em>: the ATT averages over the treated distribution; the denominator of the weight for control units should reflect this.)</li>
<li>Show that when the propensity score is constant (<span class="math inline">\(\pi(X) = p\)</span> for all units), the IPW estimator of the ATE reduces to the difference-in-means estimator. Under what experimental design does <span class="math inline">\(\pi(X) = 0.5\)</span> exactly?</li>
</ol>
<p><strong>3. Overlap.</strong> Let <span class="math inline">\(\pi(X)\)</span> be the true propensity score and suppose overlap fails at <span class="math inline">\(X = x_0\)</span>: <span class="math inline">\(\pi(x_0) = 1\)</span>.</p>
<ol type="a">
<li>For each of <span class="math inline">\(\tau_{\mathrm{ATE}}\)</span> and <span class="math inline">\(\tau_{\mathrm{ATT}}\)</span>, identify the exact formula that fails to be identified when <span class="math inline">\(\pi(x_0) = 1\)</span>, and explain why.</li>
<li>Suppose overlap fails only on a set <span class="math inline">\(\mathcal{S}\)</span> with <span class="math inline">\(P(X \in \mathcal{S}) = 0.15\)</span>. Define the <em>trimmed ATE</em> estimand. How does it differ from the ATE?</li>
<li>A researcher applies the Crump et al.&nbsp;(2009) rule with <span class="math inline">\(\eta = 0.1\)</span>, removing all units with <span class="math inline">\(\hat\pi(X_i) &lt; 0.1\)</span> or <span class="math inline">\(\hat\pi(X_i) &gt; 0.9\)</span>, removing 8% of the sample. (i) List two reasons the trimmed estimator may have lower variance than the untrimmed IPW estimator. (ii) What is the cost in terms of external validity?</li>
</ol>
<p><strong>4. Sensitivity analysis (conceptual).</strong> Suppose you estimate <span class="math inline">\(\hat\tau_{\mathrm{ATE}} = 3.2\)</span> using propensity-score methods, and a referee questions whether unconfoundedness holds.</p>
<ol type="a">
<li>Define what it means for <span class="math inline">\(U\)</span> to be a “hidden confounder” in the context of the DAG, and explain why its presence invalidates the IPW identification formula.</li>
<li>Explain in one paragraph what Rosenbaum-style sensitivity analysis would tell you about the robustness of your estimate to hidden confounding.</li>
<li>Suppose a sensitivity analysis shows that a confounder with an odds ratio of 2 for both treatment and outcome selection would be required to explain away your result. How would you interpret this finding? Does it confirm unconfoundedness?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_05.html" class="pagination-link" aria-label="Randomization and Back-Door Adjustment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_07.html" class="pagination-link" aria-label="Instrumental Variables">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>