<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Randomization and Back-Door Adjustment – Theory and Methods in Causal Inference</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_06.html" rel="next">
<link href="./chapter_04.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    tags: 'ams',
    macros: {
      doop:   ["\\operatorname{do}"],
      indep:  ["\\perp\\!\\!\\!\\perp"],
      nindep: ["\\not\\!\\perp\\!\\!\\!\\perp"],
      E:      ["\\mathbb{E}"],
      Gcal:   ["\\mathcal{G}"],
      Pa:     ["\\mathrm{Pa}"],
      De:     ["\\mathrm{De}"],
      An:     ["\\mathrm{An}"],
      Nd:     ["\\mathrm{Nd}"],
      pto:    ["\\overset{p}{\\to}"],
      expit:  ["\\operatorname{expit}"]
    }
  }
};
</script>
<style>
.quarto-download-btn {
  background-color: #1e3864 !important;
  color: white !important;
  border: none !important;
  padding: 6px 14px !important;
  border-radius: 6px !important;
  font-weight: 600 !important;
  font-size: 0.85rem !important;
}
.quarto-download-btn:hover {
  background-color: #2e72b8 !important;
  color: white !important;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_04.html">Identification</a></li><li class="breadcrumb-item"><a href="./chapter_05.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Theory and Methods in Causal Inference</a> 
        <div class="sidebar-tools-main">
    <a href="./Theory-and-Methods-in-Causal-Inference.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">DAGs and d-Separation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Do-Calculus and Identification Criteria</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Identification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Potential Outcomes and Adjustment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_05.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mediation and Front-Door Identification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sensitivity Analysis and Partial Identification</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Doubly Robust Estimation and Semiparametric Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Flexible Nuisance Estimation, Orthogonal Scores, and Cross-Fitting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Graphical Intuition for Conditional Independence and d-Separation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Single World Intervention Graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_C.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Pathwise Differentiability and Efficient Influence Functions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-rct" id="toc-sec-rct" class="nav-link active" data-scroll-target="#sec-rct"><span class="header-section-number">5.1</span> Randomized Experiments</a>
  <ul class="collapse">
  <li><a href="#the-do-calculus-of-randomization" id="toc-the-do-calculus-of-randomization" class="nav-link" data-scroll-target="#the-do-calculus-of-randomization"><span class="header-section-number">5.1.1</span> The Do-Calculus of Randomization</a></li>
  <li><a href="#estimation-of-the-ate-in-a-randomized-experiment" id="toc-estimation-of-the-ate-in-a-randomized-experiment" class="nav-link" data-scroll-target="#estimation-of-the-ate-in-a-randomized-experiment"><span class="header-section-number">5.1.2</span> Estimation of the ATE in a Randomized Experiment</a></li>
  <li><a href="#fishers-randomization-inference-vs.-neymans-repeated-sampling" id="toc-fishers-randomization-inference-vs.-neymans-repeated-sampling" class="nav-link" data-scroll-target="#fishers-randomization-inference-vs.-neymans-repeated-sampling"><span class="header-section-number">5.1.3</span> Fisher’s Randomization Inference vs.&nbsp;Neyman’s Repeated Sampling</a></li>
  </ul></li>
  <li><a href="#sec-ignorability" id="toc-sec-ignorability" class="nav-link" data-scroll-target="#sec-ignorability"><span class="header-section-number">5.2</span> Ignorability</a>
  <ul class="collapse">
  <li><a href="#two-routes-to-the-same-estimand" id="toc-two-routes-to-the-same-estimand" class="nav-link" data-scroll-target="#two-routes-to-the-same-estimand"><span class="header-section-number">5.2.1</span> Two Routes to the Same Estimand</a></li>
  <li><a href="#terminology" id="toc-terminology" class="nav-link" data-scroll-target="#terminology"><span class="header-section-number">5.2.2</span> Terminology</a></li>
  <li><a href="#three-languages-for-ignorability" id="toc-three-languages-for-ignorability" class="nav-link" data-scroll-target="#three-languages-for-ignorability"><span class="header-section-number">5.2.3</span> Three Languages for Ignorability</a></li>
  <li><a href="#what-ignorability-requires" id="toc-what-ignorability-requires" class="nav-link" data-scroll-target="#what-ignorability-requires"><span class="header-section-number">5.2.4</span> What Ignorability Requires</a></li>
  <li><a href="#sec-identification" id="toc-sec-identification" class="nav-link" data-scroll-target="#sec-identification"><span class="header-section-number">5.2.5</span> From Ignorability to Identification</a></li>
  <li><a href="#sec-pretreatment" id="toc-sec-pretreatment" class="nav-link" data-scroll-target="#sec-pretreatment"><span class="header-section-number">5.2.6</span> Which Variables to Condition On: The Pre-Treatment Requirement</a></li>
  </ul></li>
  <li><a href="#sec-regression" id="toc-sec-regression" class="nav-link" data-scroll-target="#sec-regression"><span class="header-section-number">5.3</span> Regression Adjustment and Standardization</a>
  <ul class="collapse">
  <li><a href="#the-common-three-step-logic" id="toc-the-common-three-step-logic" class="nav-link" data-scroll-target="#the-common-three-step-logic"><span class="header-section-number">5.3.1</span> The Common Three-Step Logic</a></li>
  <li><a href="#a-worked-example" id="toc-a-worked-example" class="nav-link" data-scroll-target="#a-worked-example"><span class="header-section-number">5.3.2</span> A Worked Example</a></li>
  <li><a href="#sec-standardization" id="toc-sec-standardization" class="nav-link" data-scroll-target="#sec-standardization"><span class="header-section-number">5.3.3</span> Standardization as a Special Case</a></li>
  <li><a href="#model-specification-and-what-can-go-wrong" id="toc-model-specification-and-what-can-go-wrong" class="nav-link" data-scroll-target="#model-specification-and-what-can-go-wrong"><span class="header-section-number">5.3.4</span> Model Specification and What Can Go Wrong</a></li>
  <li><a href="#regression-adjustment-in-randomized-experiments-lin-2013" id="toc-regression-adjustment-in-randomized-experiments-lin-2013" class="nav-link" data-scroll-target="#regression-adjustment-in-randomized-experiments-lin-2013"><span class="header-section-number">5.3.5</span> Regression Adjustment in Randomized Experiments: Lin (2013)</a></li>
  </ul></li>
  <li><a href="#sec-stratification" id="toc-sec-stratification" class="nav-link" data-scroll-target="#sec-stratification"><span class="header-section-number">5.4</span> Stratification</a></li>
  <li><a href="#sec-simpson" id="toc-sec-simpson" class="nav-link" data-scroll-target="#sec-simpson"><span class="header-section-number">5.5</span> Simpson’s Paradox</a>
  <ul class="collapse">
  <li><a href="#sec-simpson-collider" id="toc-sec-simpson-collider" class="nav-link" data-scroll-target="#sec-simpson-collider"><span class="header-section-number">5.5.1</span> When Should You <em>Not</em> Condition on <span class="math inline">\(X\)</span>?</a></li>
  </ul></li>
  <li><a href="#sec-lab" id="toc-sec-lab" class="nav-link" data-scroll-target="#sec-lab"><span class="header-section-number">5.6</span> Lab: Simulation Study of the Outcome Regression Estimator</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">5.7</span> Chapter Summary</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems"><span class="header-section-number">5.8</span> Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_04.html">Identification</a></li><li class="breadcrumb-item"><a href="./chapter_05.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Randomization and Back-Door Adjustment</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this chapter, students should be able to:</p>
<ol type="1">
<li>Explain in do-calculus terms why a randomized experiment makes <span class="math inline">\(f(y \mid \doop(T{=}t)) = f(y \mid T{=}t)\)</span>, and identify the graphical feature that produces this equality.</li>
<li>State the ignorability assumption in both potential-outcomes and graphical language, and distinguish weak from strong ignorability.</li>
<li>Apply the regression-adjusted estimator to reduce variance in a randomized experiment, and explain why consistency holds even under model misspecification.</li>
<li>Derive and compute the standardization (g-formula) estimator of the ATE from a contingency table or regression output.</li>
<li>Explain the method of stratification (subclassification) and describe when and why it removes confounding bias.</li>
<li>Identify Simpson’s paradox in a numerical example and resolve it using the back-door criterion.</li>
<li>Articulate why propensity score methods are needed when <span class="math inline">\(X\)</span> is high-dimensional, motivating Chapter 6.</li>
</ol>
</div>
</div>
<section id="sec-rct" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-rct"><span class="header-section-number">5.1</span> Randomized Experiments</h2>
<section id="the-do-calculus-of-randomization" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="the-do-calculus-of-randomization"><span class="header-section-number">5.1.1</span> The Do-Calculus of Randomization</h3>
<p>The defining feature of a randomized experiment is that the analyst <em>sets</em> the treatment for each unit, independently of all background variables. In do-calculus terms, the data come from the mutilated distribution <span class="math inline">\(f(y \mid \doop(T{=}t))\)</span> rather than the observational distribution <span class="math inline">\(f(y \mid T{=}t)\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Fundamental Equality of Randomized Experiments
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a completely randomized experiment, <span class="math inline">\(T\)</span> is assigned independently of all pre-treatment variables. In the DAG, this means there are <em>no arrows into <span class="math inline">\(T\)</span></em>: the treatment node has no parents. By Rule 2 of the do-calculus, with <span class="math inline">\(X = \varnothing\)</span>, <span class="math inline">\(Z = T\)</span>, <span class="math inline">\(W = \varnothing\)</span>, the graphical condition <span class="math inline">\((Y \indep T)_{\mathcal{G}_{\underline{T}}}\)</span> holds because <span class="math inline">\(T\)</span> is isolated in <span class="math inline">\(\mathcal{G}_{\underline{T}}\)</span> (no parents in <span class="math inline">\(\mathcal{G}\)</span>, and the outgoing edge <span class="math inline">\(T \to Y\)</span> is deleted). Rule 2 therefore gives: <span id="eq-fund-eq"><span class="math display">\[f\!\bigl(y \mid \doop(T{=}t)\bigr) = f(y \mid T{=}t). \tag{5.1}\]</span></span> In a randomized experiment, observing <span class="math inline">\(T = t\)</span> is the same as intervening to set <span class="math inline">\(T = t\)</span>.</p>
</div>
</div>
<p><strong>What the equality assumes beyond the graph.</strong> The fundamental equality <a href="#eq-fund-eq" class="quarto-xref">Equation&nbsp;<span>5.1</span></a> relies on more than deletion of arrows into <span class="math inline">\(T\)</span>. Two further conditions are needed. First, SUTVA (no interference and no hidden treatment versions), which licenses the consistency equation <span class="math inline">\(Y_i = Y_i(T_i)\)</span>. Second, the realized treatment must equal the assigned treatment for every unit (full compliance); when this fails, <span class="math inline">\(f(y \mid T{=}t)\)</span> describes outcomes among those who <em>actually</em> received <span class="math inline">\(t\)</span> rather than those who were <em>assigned</em> <span class="math inline">\(t\)</span>. When compliance fails, the intent-to-treat versus per-protocol distinction becomes substantive (Chapters 7 and 13).</p>
<p><strong>Graphical argument.</strong> In the observational DAG, arrows into <span class="math inline">\(T\)</span> from observed covariates <span class="math inline">\(X\)</span> and unobserved confounders <span class="math inline">\(U\)</span> create back-door paths from <span class="math inline">\(T\)</span> to <span class="math inline">\(Y\)</span>. Randomization <em>physically</em> severs these arrows: assignment is determined by a coin flip, not by <span class="math inline">\(X\)</span> or <span class="math inline">\(U\)</span>. The mutilated graph <span class="math inline">\(\mathcal{G}_{\overline{T}}\)</span> is, in a randomized experiment, the <em>actual</em> data-generating graph. There are no back-door paths to block, because none exist.</p>
<figure style="text-align:center;margin:1.5em auto;" class="figure">
<svg viewbox="0 0 520 190" width="100%" style="max-width:520px;font-family:sans-serif;font-size:13px;">
  <defs>
    <marker id="ba" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#2E74B6"></path>
    </marker>
    <marker id="ra" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#C00"></path>
    </marker>
    <marker id="ga" markerwidth="7" markerheight="7" refx="5" refy="3" orient="auto">
      <path d="M0,0 L0,6 L7,3 z" fill="#1A7A3A"></path>
    </marker>
  </defs>
  <!-- LEFT: Observational DAG -->
  <circle cx="52" cy="90" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="52" y="95" text-anchor="middle" fill="#2E74B6" font-weight="bold">T</text>
  <circle cx="152" cy="90" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="152" y="95" text-anchor="middle" fill="#2E74B6" font-weight="bold">Y</text>
  <circle cx="102" cy="38" r="20" fill="#FFF0F0" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3"></circle>
  <text x="102" y="43" text-anchor="middle" fill="#C00">U</text>
  <circle cx="102" cy="142" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="102" y="147" text-anchor="middle" fill="#2E74B6">X</text>
  <line x1="86" y1="50" x2="65" y2="75" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3" marker-end="url(#ra)"></line>
  <line x1="118" y1="50" x2="139" y2="75" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3" marker-end="url(#ra)"></line>
  <line x1="89" y1="133" x2="66" y2="107" stroke="#2E74B6" stroke-width="1.5" marker-end="url(#ba)"></line>
  <line x1="115" y1="133" x2="138" y2="107" stroke="#2E74B6" stroke-width="1.5" marker-end="url(#ba)"></line>
  <line x1="72" y1="90" x2="130" y2="90" stroke="#2E74B6" stroke-width="1.5" marker-end="url(#ba)"></line>
  <text x="102" y="178" text-anchor="middle" fill="#444" font-style="italic" font-size="11">Observational DAG</text>
  <!-- Arrow between panels -->
  <text x="200" y="97" text-anchor="middle" font-size="20" fill="#555">→</text>
  <text x="200" y="112" text-anchor="middle" fill="#555" font-size="10">randomize</text>
  <!-- RIGHT: Randomized DAG -->
  <rect x="238" y="72" width="40" height="36" rx="5" fill="#E8F7EA" stroke="#1A7A3A" stroke-width="1.5"></rect>
  <text x="258" y="87" text-anchor="middle" fill="#1A7A3A" font-size="10">coin</text>
  <text x="258" y="101" text-anchor="middle" fill="#1A7A3A" font-size="10">flip</text>
  <circle cx="342" cy="90" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="342" y="95" text-anchor="middle" fill="#2E74B6" font-weight="bold">T</text>
  <circle cx="442" cy="90" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="442" y="95" text-anchor="middle" fill="#2E74B6" font-weight="bold">Y</text>
  <circle cx="392" cy="38" r="20" fill="#FFF0F0" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3"></circle>
  <text x="392" y="43" text-anchor="middle" fill="#C00">U</text>
  <circle cx="392" cy="142" r="20" fill="#EEF4FB" stroke="#2E74B6" stroke-width="1.5"></circle>
  <text x="392" y="147" text-anchor="middle" fill="#2E74B6">X</text>
  <!-- Severed arrows (faded) -->
  <line x1="376" y1="50" x2="355" y2="75" stroke="#ccc" stroke-width="1.5" stroke-dasharray="5,3"></line>
  <text x="365" y="62" text-anchor="middle" fill="#C00" font-weight="bold" font-size="14">×</text>
  <line x1="379" y1="133" x2="356" y2="107" stroke="#ccc" stroke-width="1.5" stroke-dasharray="5,3"></line>
  <text x="367" y="120" text-anchor="middle" fill="#C00" font-weight="bold" font-size="14">×</text>
  <!-- Active arrows -->
  <line x1="278" y1="90" x2="320" y2="90" stroke="#1A7A3A" stroke-width="1.5" marker-end="url(#ga)"></line>
  <line x1="362" y1="90" x2="420" y2="90" stroke="#2E74B6" stroke-width="1.5" marker-end="url(#ba)"></line>
  <line x1="408" y1="50" x2="429" y2="75" stroke="#C00" stroke-width="1.5" stroke-dasharray="5,3" marker-end="url(#ra)"></line>
  <line x1="405" y1="133" x2="428" y2="107" stroke="#2E74B6" stroke-width="1.5" marker-end="url(#ba)"></line>
  <text x="392" y="178" text-anchor="middle" fill="#444" font-style="italic" font-size="11">Randomized DAG (𝒢<tspan font-size="8" dy="3">T̄</tspan>)</text>
</svg>
<figcaption>Randomization as graph surgery. <strong>Left</strong>: in the observational DAG, both $U$ and $X$ have arrows into $T$, creating back-door paths. <strong>Right</strong>: randomization severs all arrows into $T$ (marked ×) and replaces them with an exogenous coin flip. The mutilated graph $\mathcal{G}_{\overline{T}}$ has no back-door paths.</figcaption>
</figure>
<p><strong>Potential outcomes statement.</strong> In the potential outcomes language, randomization implies <span class="math inline">\((Y(0), Y(1)) \indep T\)</span> unconditionally — no covariate adjustment is needed. This is the strongest possible version of ignorability.</p>
</section>
<section id="estimation-of-the-ate-in-a-randomized-experiment" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="estimation-of-the-ate-in-a-randomized-experiment"><span class="header-section-number">5.1.2</span> Estimation of the ATE in a Randomized Experiment</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lemma: Identification under Complete Randomization
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under complete randomization, <span class="math inline">\(\E[Y(t)] = \E[Y \mid T{=}t]\)</span>, <span class="math inline">\(t \in \{0,1\}\)</span>.</p>
</div>
</div>
<p><em>Proof.</em> By the PO–do equivalence, <span class="math inline">\(\E[Y(t)] = \E[Y \mid \doop(T{=}t)]\)</span>. The treatment node has no parents, so <a href="#eq-fund-eq" class="quarto-xref">Equation&nbsp;<span>5.1</span></a> gives <span class="math inline">\(f(y \mid \doop(T{=}t)) = f(y \mid T{=}t)\)</span>. <span class="math inline">\(\square\)</span></p>
<p>Under complete randomization, the ATE is estimated by the <em>difference-in-means</em> (DIM) estimator: <span class="math display">\[\hat\tau_{\mathrm{DIM}} = \bar Y_1 - \bar Y_0 = \frac{1}{n_1}\sum_{i:\, T_i=1} Y_i - \frac{1}{n_0}\sum_{i:\, T_i=0} Y_i.\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: Neyman’s Theorem for the Difference-in-Means Estimator
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under complete randomization, let <span class="math inline">\(\mathcal{F}_N = \{(Y_i(0), Y_i(1))\}\)</span> be the potential outcomes (fixed), and let expectations be over the randomization distribution. Define the finite-population variances <span class="math inline">\(S_t^2 = \frac{1}{n-1}\sum_i (Y_i(t) - \bar Y(t))^2\)</span>, cross-variance <span class="math inline">\(S_{01} = \frac{1}{n-1}\sum_i (Y_i(0)-\bar Y(0))(Y_i(1)-\bar Y(1))\)</span>, and effect variance <span class="math inline">\(S_\tau^2 = \frac{1}{n-1}\sum_i (\tau_i - \bar\tau_n)^2\)</span>. Then:</p>
<ol type="1">
<li><strong>Unbiasedness.</strong> <span class="math inline">\(\E[\hat\tau_{\mathrm{DIM}} \mid \mathcal{F}_N] = \bar Y(1) - \bar Y(0) = \bar\tau_n\)</span>.</li>
<li><strong>Design variance.</strong> <span id="eq-neyman-variance"><span class="math display">\[\mathrm{Var}(\hat\tau_{\mathrm{DIM}} \mid \mathcal{F}_N) = \frac{S_1^2}{n_1} + \frac{S_0^2}{n_0} - \frac{S_\tau^2}{n}. \tag{5.2}\]</span></span></li>
<li><strong>Conservative variance estimator.</strong> The within-arm sample variance estimator <span class="math inline">\(\hat V = \hat S_1^2/n_1 + \hat S_0^2/n_0\)</span> satisfies <span class="math inline">\(\E[\hat V \mid \mathcal{F}_N] - \mathrm{Var}(\hat\tau_{\mathrm{DIM}} \mid \mathcal{F}_N) = S_\tau^2/n \geq 0\)</span>. It is exact when the unit-level treatment effects <span class="math inline">\(\tau_i\)</span> are constant.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof of Neyman’s Theorem
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Throughout we condition on <span class="math inline">\(\mathcal{F}_N\)</span>. Under CRE, <span class="math inline">\(\E[T_i \mid \mathcal{F}_N] = n_1/n\)</span> for all <span class="math inline">\(i\)</span>, and: <span class="math display">\[\mathrm{Cov}(T_i, T_j \mid \mathcal{F}_N) = \begin{cases} f_1(1-f_1) &amp; i = j, \\ -f_1(1-f_1)/(n-1) &amp; i \neq j, \end{cases}\]</span> where <span class="math inline">\(f_1 = n_1/n\)</span>. The <span class="math inline">\(i \neq j\)</span> expression follows from sampling <span class="math inline">\(n_1\)</span> units without replacement.</p>
<p><strong>(i) Unbiasedness.</strong> <span class="math inline">\(\E[n_1^{-1}\sum_i T_i Y_i(1) \mid \mathcal{F}_N] = \bar Y(1)\)</span> by <span class="math inline">\(\E[T_i \mid \mathcal{F}_N] = n_1/n\)</span>; the control arm is symmetric.</p>
<p><strong>(ii) Variance.</strong> Writing <span class="math inline">\(Z_i(t) = Y_i(t) - \bar Y(t)\)</span> and using the covariance formula: <span class="math display">\[\mathrm{Var}\!\left(\frac{1}{n_1}\sum_i T_i Y_i(1)\right) = \frac{f_1(1-f_1)}{n_1^2}\cdot\frac{n}{n-1}\sum_i Z_i(1)^2 = \frac{n_0}{n_1 n} S_1^2,\]</span> and the cross-arm covariance yields <span class="math inline">\(-S_{01}/n\)</span>. Combining gives the first form of <a href="#eq-neyman-variance" class="quarto-xref">Equation&nbsp;<span>5.2</span></a>. Rearranging using <span class="math inline">\(n_0/(n_1 n) = 1/n_1 - 1/n\)</span> gives the second form.</p>
<p><strong>(iii) Conservatism.</strong> By finite-population sampling theory, <span class="math inline">\(\E[\hat S_t^2 \mid \mathcal{F}_N] = S_t^2\)</span>. Therefore <span class="math inline">\(\E[\hat V \mid \mathcal{F}_N] = S_1^2/n_1 + S_0^2/n_0\)</span>, and subtracting <a href="#eq-neyman-variance" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> gives <span class="math inline">\(S_\tau^2/n \geq 0\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Why the Conservatism Cannot Be Removed
</div>
</div>
<div class="callout-body-container callout-body">
<p>The correction term <span class="math inline">\(S_\tau^2/n\)</span> depends on the unit-level effect variance. Computing <span class="math inline">\(S_\tau^2\)</span> requires both <span class="math inline">\(Y_i(0)\)</span> and <span class="math inline">\(Y_i(1)\)</span> for every unit — precisely what the fundamental problem of causal inference forbids. The estimator <span class="math inline">\(\hat V\)</span> is not merely pragmatic; it is the sharpest variance estimator based on observed data alone without further modelling assumptions.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Superpopulation Variance as a Corollary
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under i.i.d. superpopulation draws with arm variances <span class="math inline">\((\sigma_0^2, \sigma_1^2)\)</span>, the total variance has two phases: randomization variance (given <span class="math inline">\(\mathcal{F}_N\)</span>) and sampling variance (over draws of <span class="math inline">\(\mathcal{F}_N\)</span>). The law of total variance gives: <span id="eq-dim-var-superpop"><span class="math display">\[\mathrm{Var}(\hat\tau_{\mathrm{DIM}}) = \frac{\sigma_1^2}{n_1} + \frac{\sigma_0^2}{n_0}. \tag{5.3}\]</span></span> The Neyman correction <span class="math inline">\(S_\tau^2/n\)</span> in <a href="#eq-neyman-variance" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> is exactly cancelled by the sampling variance of <span class="math inline">\(\bar\tau_n\)</span> when averaging over superpopulation draws. See <span class="citation" data-cites="ding2023first">Ding (<a href="references.html#ref-ding2023first" role="doc-biblioref">2024</a>)</span> for a complete treatment.</p>
</div>
</div>
</section>
<section id="fishers-randomization-inference-vs.-neymans-repeated-sampling" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="fishers-randomization-inference-vs.-neymans-repeated-sampling"><span class="header-section-number">5.1.3</span> Fisher’s Randomization Inference vs.&nbsp;Neyman’s Repeated Sampling</h3>
<p>Fisher’s framework tests the <em>sharp null</em> <span class="math inline">\(Y_i(1) = Y_i(0)\)</span> for all <span class="math inline">\(i\)</span>: under this null, every missing potential outcome is known, making the exact randomization distribution of any test statistic computable over all <span class="math inline">\(\binom{n}{n_1}\)</span> assignments. Neyman’s framework studies the repeated-sampling behavior of estimators like <span class="math inline">\(\hat\tau_{\mathrm{DIM}}\)</span> for average causal effects.</p>
<p>Fisher’s approach is aligned with exact hypothesis testing under a sharp null; Neyman’s is aligned with point estimation and uncertainty quantification. Both rely on the treatment assignment mechanism but answer different questions.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Randomization Licenses Inference Without Population Assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Randomization licenses causal inference <em>without any assumption about a population model</em>. In Fisher’s design-based framework, the potential outcomes <span class="math inline">\(\{Y_i(0), Y_i(1)\}\)</span> are fixed numbers; the only source of randomness is the assignment vector <span class="math inline">\(\mathbf{T}\)</span>, drawn uniformly from all <span class="math inline">\(\binom{n}{n_1}\)</span> possible assignments. Probability statements refer to this mechanism — not to repeated draws from a population. Units need not be a random sample; they can be a convenience sample, a census, or a targeted group. Observational methods, by contrast, must invoke either an i.i.d. sampling assumption or a superpopulation framework, because no analogous physical mechanism anchors probability statements.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Fisher’s Sharp Null — Unidentifiable Effects, Exactly Testable Hypothesis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Individual causal effects <span class="math inline">\(\tau_i = Y_i(1) - Y_i(0)\)</span> are unidentifiable for any unit. Yet the sharp null <span class="math inline">\(H_0: Y_i(1) = Y_i(0)\)</span> for all <span class="math inline">\(i\)</span> is exactly testable. The resolution: under <span class="math inline">\(H_0\)</span>, the sharp null completely specifies the joint potential outcome table — <span class="math inline">\(Y_i(1) = Y_i(0) = Y_i^{\mathrm{obs}}\)</span> regardless of assignment — so the full <span class="math inline">\(2n\)</span>-vector of potential outcomes is known, and the permutation distribution of any test statistic is computable from observed data with no estimation step.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Further Reading
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="ding2023first">Ding (<a href="references.html#ref-ding2023first" role="doc-biblioref">2024</a>)</span> provides a comprehensive graduate-level treatment of CRE, stratified experiments, and regression adjustment. <span class="citation" data-cites="li2017general">Li and Ding (<a href="references.html#ref-li2017general" role="doc-biblioref">2017</a>)</span> works out the asymptotic theory underlying confidence intervals for <span class="math inline">\(\hat\tau_{\mathrm{DIM}}\)</span> via a finite-population CLT requiring neither i.i.d. observations nor a superpopulation model. <span class="citation" data-cites="ding2016randomization">Ding et al. (<a href="references.html#ref-ding2016randomization" role="doc-biblioref">2016</a>)</span> develop randomization-based tests for treatment effect heterogeneity.</p>
</div>
</div>
</section>
</section>
<section id="sec-ignorability" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-ignorability"><span class="header-section-number">5.2</span> Ignorability</h2>
<section id="two-routes-to-the-same-estimand" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="two-routes-to-the-same-estimand"><span class="header-section-number">5.2.1</span> Two Routes to the Same Estimand</h3>
<p>Section <a href="#sec-rct" class="quarto-xref"><span>Section 5.1</span></a> established that randomization achieves <a href="#eq-fund-eq" class="quarto-xref">Equation&nbsp;<span>5.1</span></a> and that DIM is unbiased for the ATE without covariate adjustment. In observational studies, no such physical severance occurs: treatment is selected based on characteristics that may include unmeasured variables <span class="math inline">\(U\)</span> affecting the outcome.</p>
<p>Both settings target the same estimand — the ATE <span class="math inline">\(\E[Y(1) - Y(0)]\)</span> — but reach it by fundamentally different routes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Randomized experiment</strong></th>
<th><strong>Observational study</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>How ignorability arises</td>
<td>By design: researcher severs all arrows into <span class="math inline">\(T\)</span></td>
<td>By assumption: analyst asserts no unmeasured confounders</td>
</tr>
<tr class="even">
<td><span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span></td>
<td><em>Guaranteed</em> — holds unconditionally</td>
<td><em>Assumed</em> — requires <span class="math inline">\(X\)</span> to capture every confounder</td>
</tr>
<tr class="odd">
<td>Credibility</td>
<td>As strong as the randomization protocol</td>
<td>As strong as substantive knowledge of the DGP</td>
</tr>
<tr class="even">
<td>Testability</td>
<td>Can audit the assignment mechanism</td>
<td>Cannot be verified from data alone</td>
</tr>
<tr class="odd">
<td>Failure mode</td>
<td>Protocol violations, non-compliance</td>
<td>Any unmeasured variable affecting both <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span></td>
</tr>
</tbody>
</table>
<p>Statistical adjustment can <em>implement</em> ignorability once assumed, but cannot <em>create</em> it. No covariate adjustment — however flexible — can close a back-door path through an unmeasured variable. This is why a well-conducted RCT is considered more credible than even the most carefully adjusted observational study.</p>
</section>
<section id="terminology" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="terminology"><span class="header-section-number">5.2.2</span> Terminology</h3>
<p>Strong ignorability was defined in Chapter 4: joint unconfoundedness <span class="math inline">\((Y(0), Y(1)) \indep T \mid X\)</span> together with overlap <span class="math inline">\(0 &lt; P(T{=}1 \mid X) &lt; 1\)</span> a.s. <span class="citation" data-cites="rosenbaum1983central">(<a href="references.html#ref-rosenbaum1983central" role="doc-biblioref">Rosenbaum and Rubin 1983</a>)</span>. The pointwise (weak) form <span class="math inline">\(Y(t) \indep T \mid X\)</span> for each <span class="math inline">\(t\)</span> separately is what identification of <span class="math inline">\(\E[Y(t)]\)</span> actually uses. Equivalent names in the literature: <em>unconfoundedness</em>, <em>selection on observables</em>, <em>no unmeasured confounders</em>, <em>conditional exchangeability</em>.</p>
</section>
<section id="three-languages-for-ignorability" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="three-languages-for-ignorability"><span class="header-section-number">5.2.3</span> Three Languages for Ignorability</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Language</strong></th>
<th><strong>Statement of ignorability</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SEM</td>
<td>In <span class="math inline">\(Y = f_Y(T, X, U_Y)\)</span> with <span class="math inline">\(T = f_T(X, U_T)\)</span>, the exogenous factor <span class="math inline">\(U_Y\)</span> is independent of <span class="math inline">\(T\)</span> given <span class="math inline">\(X\)</span> — no unobserved common cause of <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span> remains after conditioning on <span class="math inline">\(X\)</span>.</td>
</tr>
<tr class="even">
<td>DAG / do-calculus</td>
<td><span class="math inline">\(X\)</span> satisfies the back-door criterion for <span class="math inline">\((T, Y)\)</span>: <span class="math inline">\(X\)</span> blocks all back-door paths and contains no descendant of <span class="math inline">\(T\)</span>.</td>
</tr>
<tr class="odd">
<td>Potential outcomes</td>
<td><span class="math inline">\(Y(t) \indep T \mid X\)</span> for <span class="math inline">\(t \in \{0,1\}\)</span> (weak ignorability).</td>
</tr>
</tbody>
</table>
<p>These three forms are closely aligned under NPSEM-IE semantics together with consistency and no interference.</p>
</section>
<section id="what-ignorability-requires" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="what-ignorability-requires"><span class="header-section-number">5.2.4</span> What Ignorability Requires</h3>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Ignorability Is Untestable from Observational Data
</div>
</div>
<div class="callout-body-container callout-body">
<p>No statistical test can confirm or refute unconfoundedness using observed data alone. If an unobserved variable <span class="math inline">\(U\)</span> affects both <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span>, the back-door path <span class="math inline">\(T \leftarrow U \to Y\)</span> is open, and conditioning on any set of observed variables cannot close it. Sensitivity analysis <span class="citation" data-cites="rosenbaum2002observational">(<a href="references.html#ref-rosenbaum2002observational" role="doc-biblioref">Rosenbaum 2002</a>)</span> can quantify how large such an unobserved confounder would have to be to overturn a conclusion, but cannot confirm the assumption itself.</p>
</div>
</div>
</section>
<section id="sec-identification" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="sec-identification"><span class="header-section-number">5.2.5</span> From Ignorability to Identification</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lemma: Identification of <span class="math inline">\(\E[Y(t)]\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose: (i) <em>weak ignorability</em> <span class="math inline">\(Y(t) \indep T \mid X\)</span>; (ii) <em>overlap</em> <span class="math inline">\(P(T{=}t \mid X{=}x) &gt; 0\)</span> a.s.; (iii) <em>consistency</em> <span class="math inline">\(Y = Y(T)\)</span>. Then: <span id="eq-ident-pot"><span class="math display">\[\E[Y(t)] = \E\bigl[\E[Y \mid T{=}t, X]\bigr] = \int \E[Y \mid T{=}t, X{=}x]\, p(x)\, dx. \tag{5.4}\]</span></span></p>
</div>
</div>
<p><em>Proof.</em> Apply the law of iterated expectations, then use each assumption in turn: <span class="math display">\[\E[Y(t)] \overset{\mathrm{LIE}}{=} \E[\E[Y(t) \mid X]] \overset{(i)}{=} \E[\E[Y(t) \mid T{=}t, X]] \overset{(iii)}{=} \E[\E[Y \mid T{=}t, X]]. \quad\square\]</span> Overlap (ii) guarantees <span class="math inline">\(\E[Y \mid T{=}t, X{=}x]\)</span> is well-defined everywhere in the support of <span class="math inline">\(X\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Two Languages, One Formula
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="quarto-unresolved-ref">?lem-ident</span> and the back-door theorem (Chapter 3) are two proofs of the same formula in different languages. The graphical proof applies Rules 2 and 3 to the mutilated graph; the potential-outcomes proof applies the law of iterated expectations to counterfactual variables. The bridge is the structural causal semantics: under NPSEM-IE, <span class="math inline">\(Y(t)\)</span> has the same distribution as <span class="math inline">\(Y\)</span> under <span class="math inline">\(\doop(T{=}t)\)</span> (Chapter 4). Consistency connects <span class="math inline">\(\E[Y(t) \mid T{=}t, X]\)</span> to the observed <span class="math inline">\(\E[Y \mid T{=}t, X]\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: Identification of the ATE and ATT
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under the same three assumptions: <span id="eq-backdoor"><span class="math display">\[\tau_{\mathrm{ATE}} = \int [\E(Y \mid T{=}1, X{=}x) - \E(Y \mid T{=}0, X{=}x)]\, p(x)\, dx, \tag{5.5}\]</span></span> <span id="eq-backdoor-att"><span class="math display">\[\tau_{\mathrm{ATT}} = \int [\E(Y \mid T{=}1, X{=}x) - \E(Y \mid T{=}0, X{=}x)]\, p(x \mid T{=}1)\, dx. \tag{5.6}\]</span></span></p>
</div>
</div>
<p><em>Proof.</em> Apply <span class="quarto-unresolved-ref">?lem-ident</span> separately to <span class="math inline">\(t=1\)</span> and <span class="math inline">\(t=0\)</span> and subtract. For the ATT, replace <span class="math inline">\(p(x)\)</span> by <span class="math inline">\(p(x \mid T{=}1)\)</span>. <span class="math inline">\(\square\)</span></p>
<p><strong>Assumption traceability.</strong> Each step in the proof invokes exactly one assumption:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Proof step</th>
<th>Assumption invoked</th>
<th>Failure mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\E[Y(t) \mid X] = \E[Y(t) \mid T{=}t, X]\)</span></td>
<td>Weak ignorability</td>
<td>Unmeasured confounder: <span class="math inline">\(Y(t)\)</span> depends on <span class="math inline">\(T\)</span> within <span class="math inline">\(X\)</span>-strata</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\E[Y \mid T{=}t, X{=}x]\)</span> is well-defined</td>
<td>Overlap</td>
<td>Empty stratum: no units with <span class="math inline">\(T{=}t\)</span> at <span class="math inline">\(x\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\E[Y(t) \mid T{=}t, X] = \E[Y \mid T{=}t, X]\)</span></td>
<td>Consistency</td>
<td>Interference or hidden treatment versions</td>
</tr>
</tbody>
</table>
<p>Overlap is <em>testable</em> from data (check support of <span class="math inline">\(X \mid T{=}1\)</span> vs.&nbsp;<span class="math inline">\(X \mid T{=}0\)</span>). Weak ignorability and consistency are not testable from data alone.</p>
</section>
<section id="sec-pretreatment" class="level3" data-number="5.2.6">
<h3 data-number="5.2.6" class="anchored" data-anchor-id="sec-pretreatment"><span class="header-section-number">5.2.6</span> Which Variables to Condition On: The Pre-Treatment Requirement</h3>
<p>Before estimating anything, there is a prior graphical question: <em>which variables should be in <span class="math inline">\(X\)</span>?</em> The answer is not “all available variables.” Conditioning on the wrong variable introduces bias.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Never Condition on a Post-Treatment Variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>A variable <span class="math inline">\(L\)</span> is <em>post-treatment</em> if <span class="math inline">\(T \to L\)</span> in the DAG. Including <span class="math inline">\(L\)</span> in <span class="math inline">\(X\)</span> can bias the estimated treatment effect through two mechanisms:</p>
<ol type="1">
<li><strong>Blocking a causal pathway.</strong> If <span class="math inline">\(L\)</span> is a mediator (<span class="math inline">\(T \to L \to Y\)</span>), conditioning on <span class="math inline">\(L\)</span> blocks part of the causal effect of <span class="math inline">\(T\)</span>. The result estimates a direct effect, not the total effect.</li>
<li><strong>Opening a collider path.</strong> If <span class="math inline">\(L\)</span> is a collider (<span class="math inline">\(T \to L \leftarrow U \to Y\)</span>), conditioning on <span class="math inline">\(L\)</span> opens a previously blocked path, creating a spurious <span class="math inline">\(T\)</span>–<span class="math inline">\(Y\)</span> association through the unobserved <span class="math inline">\(U\)</span>.</li>
</ol>
<p>In both cases, including <span class="math inline">\(L\)</span> violates Condition 1 of the back-door criterion: <em><span class="math inline">\(X\)</span> must contain no descendant of <span class="math inline">\(T\)</span></em>. The back-door criterion is not merely a sufficiency condition for identification — it is the correct filter for deciding which variables to include.</p>
</div>
</div>
<p>The practical rule: before running any regression, classify every candidate covariate as pre-treatment or post-treatment using the causal graph. Only pre-treatment variables satisfying the back-door criterion belong in <span class="math inline">\(X\)</span>.</p>
</section>
</section>
<section id="sec-regression" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-regression"><span class="header-section-number">5.3</span> Regression Adjustment and Standardization</h2>
<section id="the-common-three-step-logic" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="the-common-three-step-logic"><span class="header-section-number">5.3.1</span> The Common Three-Step Logic</h3>
<p>Both regression adjustment and standardization implement the same back-door formula <a href="#eq-backdoor" class="quarto-xref">Equation&nbsp;<span>5.5</span></a>. They differ only in how they estimate <span class="math inline">\(\mu(t, x) = \E[Y \mid T{=}t, X{=}x]\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Three-Step Recipe: Outcome Regression / G-Formula
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Estimate the outcome model.</strong> Fit a model for <span class="math inline">\(\mu(t,x) = \E[Y \mid T{=}t, X{=}x]\)</span> using observed data. Any regression method may be used: OLS, logistic regression, or a flexible nonparametric estimator.</p></li>
<li><p><strong>Predict both potential outcomes for every unit.</strong> For each unit <span class="math inline">\(i\)</span> — <em>regardless of treatment actually received</em> — compute: <span class="math display">\[\hat{Y}_i(1) = \hat\mu(1, X_i), \qquad \hat{Y}_i(0) = \hat\mu(0, X_i).\]</span> For a treated unit, <span class="math inline">\(\hat{Y}_i(0)\)</span> is the predicted outcome had that unit been assigned to control; for a control unit, <span class="math inline">\(\hat{Y}_i(1)\)</span> is the predicted outcome had that unit been treated.</p></li>
<li><p><strong>Average the individual treatment effect estimates.</strong> <span id="eq-or"><span class="math display">\[\hat\tau_{\mathrm{OR}} = \frac{1}{n}\sum_{i=1}^n [\hat\mu(1, X_i) - \hat\mu(0, X_i)]. \tag{5.7}\]</span></span> To estimate the ATT, average only over the <span class="math inline">\(n_1\)</span> treated units.</p></li>
</ol>
</div>
</div>
<p>This is the <em>outcome regression</em> (OR) or <em>G-computation</em> estimator <span class="citation" data-cites="robins1986new">(<a href="references.html#ref-robins1986new" role="doc-biblioref">Robins 1986</a>)</span>. Step 3 averages out <span class="math inline">\(X\)</span> using the empirical distribution — exactly what <a href="#eq-backdoor" class="quarto-xref">Equation&nbsp;<span>5.5</span></a> requires: <span class="math inline">\(\tau_{\mathrm{ATE}} = \int [\mu(1,x) - \mu(0,x)] p(x)\, dx\)</span>.</p>
</section>
<section id="a-worked-example" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="a-worked-example"><span class="header-section-number">5.3.2</span> A Worked Example</h3>
<p>Binary covariate <span class="math inline">\(X\)</span> (e.g., sex), continuous outcome <span class="math inline">\(Y\)</span> (e.g., earnings). High-<span class="math inline">\(X\)</span> units are overrepresented in the treated arm (70% treated vs.&nbsp;30% control).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Treated (<span class="math inline">\(T=1\)</span>)</th>
<th>Control (<span class="math inline">\(T=0\)</span>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td><span class="math inline">\(n=30\)</span>, <span class="math inline">\(\bar Y = 42\)</span></td>
<td><span class="math inline">\(n=70\)</span>, <span class="math inline">\(\bar Y = 35\)</span></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td><span class="math inline">\(n=70\)</span>, <span class="math inline">\(\bar Y = 58\)</span></td>
<td><span class="math inline">\(n=30\)</span>, <span class="math inline">\(\bar Y = 50\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>All</strong></td>
<td><span class="math inline">\(n=100\)</span>, <span class="math inline">\(\bar Y = 53.2\)</span></td>
<td><span class="math inline">\(n=100\)</span>, <span class="math inline">\(\bar Y = 38.5\)</span></td>
<td>Unadjusted diff = 14.7</td>
</tr>
</tbody>
</table>
<p><strong>Step 1.</strong> <span class="math inline">\(\hat\mu(1,0) = 42\)</span>, <span class="math inline">\(\hat\mu(1,1) = 58\)</span>, <span class="math inline">\(\hat\mu(0,0) = 35\)</span>, <span class="math inline">\(\hat\mu(0,1) = 50\)</span>.</p>
<p><strong>Step 2.</strong> Within-stratum effects: <span class="math inline">\(42 - 35 = 7\)</span> (for <span class="math inline">\(X{=}0\)</span>), <span class="math inline">\(58 - 50 = 8\)</span> (for <span class="math inline">\(X{=}1\)</span>).</p>
<p><strong>Step 3.</strong> Averaging over the <em>marginal</em> distribution of <span class="math inline">\(X\)</span>: 50% of the full sample has <span class="math inline">\(X{=}0\)</span>, 50% has <span class="math inline">\(X{=}1\)</span>: <span class="math display">\[\hat\tau_{\mathrm{ATE}} = 7 \times 0.5 + 8 \times 0.5 = 7.5.\]</span></p>
<p>After adjusting for <span class="math inline">\(X\)</span>, the estimated treatment effect is 7.5, not 14.7. The unadjusted comparison conflates the treatment effect with the higher baseline earnings of <span class="math inline">\(X{=}1\)</span> units who happen to be treated more often.</p>
</section>
<section id="sec-standardization" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sec-standardization"><span class="header-section-number">5.3.3</span> Standardization as a Special Case</h3>
<p>When <span class="math inline">\(X\)</span> is categorical, standardization computes <span class="math inline">\(\hat\mu(t,x)\)</span> as the within-cell sample mean — a fully saturated model: <span id="eq-std"><span class="math display">\[\hat\tau_{\mathrm{STD}} = \sum_{x \in \mathcal{X}} [\hat\mu(1,x) - \hat\mu(0,x)]\,\hat{p}(x). \tag{5.8}\]</span></span> This is <em>algebraically identical</em> to <a href="#eq-or" class="quarto-xref">Equation&nbsp;<span>5.7</span></a> when <span class="math inline">\(X\)</span> is categorical: standardization is regression adjustment with a saturated outcome model. The formula is also known as the <em>G-formula</em> <span class="citation" data-cites="robins1986new">(<a href="references.html#ref-robins1986new" role="doc-biblioref">Robins 1986</a>)</span> and as <em>direct standardization</em> in epidemiology.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Regression adjustment</strong></th>
<th><strong>Standardization</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>How <span class="math inline">\(\hat\mu(t,x)\)</span> is estimated</td>
<td>Parametric model: OLS, logistic, or flexible learner</td>
<td>Cell means: <span class="math inline">\(\bar Y\)</span> within <span class="math inline">\((T{=}t, X{=}x)\)</span></td>
</tr>
<tr class="even">
<td>Works when <span class="math inline">\(X\)</span> is</td>
<td>Continuous or high-dimensional</td>
<td>Discrete and low-dimensional</td>
</tr>
<tr class="odd">
<td>Bias if wrong</td>
<td>Model misspecification</td>
<td>Sparse cells (some <span class="math inline">\((t,x)\)</span> strata empty)</td>
</tr>
<tr class="even">
<td>Steps 2–3</td>
<td>Identical: predict both POs, average</td>
<td>Identical: predict both POs, average</td>
</tr>
</tbody>
</table>
</section>
<section id="model-specification-and-what-can-go-wrong" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="model-specification-and-what-can-go-wrong"><span class="header-section-number">5.3.4</span> Model Specification and What Can Go Wrong</h3>
<p>The OR estimator is consistent if and only if <span class="math inline">\(\hat\mu(t,x) \to \mu(t,x)\)</span> as <span class="math inline">\(n \to \infty\)</span> — i.e., if the outcome model is correctly specified.</p>
<p><strong>Misspecification bias.</strong> If the true <span class="math inline">\(\mu(t,x)\)</span> is nonlinear but a linear model is used, the estimated treatment effect absorbs the functional form error. Flexible machine learning estimators reduce this risk, at the cost of requiring cross-fitting to avoid overfitting bias (Chapter 11).</p>
<p><strong>Extrapolation.</strong> Step 2 predicts <span class="math inline">\(\hat{Y}_i(0)\)</span> for treated units whose covariate values may lie outside the support of the control group. The propensity score overlap condition (Chapter 6) formalizes when extrapolation is unavoidable.</p>
</section>
<section id="regression-adjustment-in-randomized-experiments-lin-2013" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="regression-adjustment-in-randomized-experiments-lin-2013"><span class="header-section-number">5.3.5</span> Regression Adjustment in Randomized Experiments: Lin (2013)</h3>
<p>In a <em>randomized</em> experiment, outcome regression can reduce variance even though adjustment is not needed for unbiasedness. The <em>regression-adjusted estimator</em> of <span class="citation" data-cites="lin2013agnostic">Lin (<a href="references.html#ref-lin2013agnostic" role="doc-biblioref">2013</a>)</span> fits the fully interacted OLS model: <span id="eq-lin-reg"><span class="math display">\[Y_i = \alpha + \beta T_i + \gamma^\top \tilde{X}_i + \delta^\top (T_i \cdot \tilde{X}_i) + \varepsilon_i, \tag{5.9}\]</span></span> where <span class="math inline">\(\tilde{X}_i = X_i - \bar{X}\)</span> are mean-centered covariates, and takes <span class="math inline">\(\hat\beta\)</span> as the ATE estimate.</p>
<p><strong>Why <span class="math inline">\(\hat\beta\)</span> equals the three-step OR estimator.</strong> The interacted regression <a href="#eq-lin-reg" class="quarto-xref">Equation&nbsp;<span>5.9</span></a> fits arm-specific linear models with centered covariates. Under centering, the OLS intercept equals the regression-adjusted estimator of <span class="math inline">\(\E[Y(t)]\)</span>, so <span class="math inline">\(\hat\beta = \hat\mu_{1,\mathrm{reg}} - \hat\mu_{0,\mathrm{reg}} = \hat\tau_{\mathrm{reg}}\)</span>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Theorem: Design-Consistency of the Regression-Adjusted Estimator <span class="citation" data-cites="lin2013agnostic">(<a href="references.html#ref-lin2013agnostic" role="doc-biblioref">Lin 2013</a>)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under complete randomization, <span class="math inline">\(\hat\beta\)</span> from the interacted regression <a href="#eq-lin-reg" class="quarto-xref">Equation&nbsp;<span>5.9</span></a> is consistent for <span class="math inline">\(\tau_{\mathrm{ATE}}\)</span> regardless of whether the linear model is correctly specified.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Proof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Work in the design-based framework of <span class="quarto-unresolved-ref">?thm-dim</span>: potential outcomes fixed, only <span class="math inline">\(\mathbf{T}\)</span> random. Let <span class="math inline">\(\mathbf{B}_1 = (\sum_i \mathbf{x}_i \mathbf{x}_i^\top)^{-1}\sum_i \mathbf{x}_i Y_i(1)\)</span> be the full-population OLS coefficient (fixed under randomization), and let <span class="math inline">\(e_i(1) = Y_i(1) - \mathbf{x}_i^\top \mathbf{B}_1\)</span>. By normal equations, <span class="math inline">\(\sum_i e_i(1) = 0\)</span> and <span class="math inline">\(\frac{1}{N}\sum_i \mathbf{x}_i^\top \mathbf{B}_1 = \bar Y(1)\)</span>.</p>
<p><strong>Linearization.</strong> A short algebraic manipulation using normal equations gives: <span id="eq-lin-linearization"><span class="math display">\[\hat\mu_{1,\mathrm{reg}} = \bar Y(1) + \frac{1}{N_1}\sum_{i=1}^N T_i e_i(1) + O_p(N^{-1}). \tag{5.10}\]</span></span> The remainder term <span class="math inline">\(R_N\)</span> is <span class="math inline">\(O_p(N^{-1})\)</span> because the covariate-balance gap is <span class="math inline">\(O_p(N^{-1/2})\)</span> by design, and <span class="math inline">\(\hat{\boldsymbol\beta}_1 - \mathbf{B}_1 = O_p(N^{-1/2})\)</span> by standard within-arm OLS theory.</p>
<p><strong>Consistency.</strong> Under CRE, each unit has <span class="math inline">\(\Pr(T_i=1 \mid \mathcal{F}_N) = N_1/N\)</span>, so <span class="math inline">\(\E[N_1^{-1}\sum_i T_i e_i(1) \mid \mathcal{F}_N] = 0\)</span> by <span class="math inline">\(\sum_i e_i(1) = 0\)</span>. The conditional variance is <span class="math inline">\(O(N^{-1})\)</span> by finite-population sampling theory; by Chebyshev, <span class="math inline">\(N_1^{-1}\sum_i T_i e_i(1) \to_p 0\)</span>. By <a href="#eq-lin-linearization" class="quarto-xref">Equation&nbsp;<span>5.10</span></a>, <span class="math inline">\(\hat\mu_{1,\mathrm{reg}} - \bar Y(1) \to_p 0\)</span>. Symmetrically, <span class="math inline">\(\hat\mu_{0,\mathrm{reg}} - \bar Y(0) \to_p 0\)</span>. Therefore <span class="math inline">\(\hat\beta \to_p \bar Y(1) - \bar Y(0) = \tau_{\mathrm{ATE}}\)</span>.</p>
<p>Crucially, the probability limit of <span class="math inline">\(\hat{\boldsymbol\beta}_1\)</span> never enters: consistency comes from the randomization distribution, not from correctness of the linear model. <span class="math inline">\(\square\)</span></p>
</div>
</div>
</div>
<p><strong>Byproduct: variance reduction.</strong> Equation <a href="#eq-lin-linearization" class="quarto-xref">Equation&nbsp;<span>5.10</span></a> shows that the regression estimator is approximately <span class="math inline">\(\bar\tau + N_1^{-1}\sum_i T_i e_i(1) - N_0^{-1}\sum_i (1-T_i) e_i(0)\)</span>. The variance reduction relative to DIM comes from replacing raw outcomes by residuals: when the linear model explains a meaningful share of <span class="math inline">\(Y_i(t)\)</span>’s variation, <span class="math inline">\(S_{e(t)}^2 &lt; S_{Y(t)}^2\)</span> and the design variance shrinks.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: The Role of the Regression Model in a Randomized Experiment
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a randomized experiment, the regression model serves <em>one purpose only</em>: variance reduction. It does not contribute to unbiasedness. DIM is already design-consistent; adding covariates reduces <span class="math inline">\(\mathrm{Var}(\hat\tau)\)</span> by absorbing residual variation in <span class="math inline">\(Y\)</span> unrelated to <span class="math inline">\(T\)</span>. If the model fits well, the residual variance shrinks and the estimator becomes more precise. If misspecified or covariates are weakly predictive, the variance reduction is small or zero, but <em>no bias is introduced</em>. This stands in sharp contrast to the observational setting, where the regression model carries a double burden: it must both adjust for confounding (unbiasedness) and fit the outcome surface (efficiency). Misspecification in an observational study threatens <em>both</em> properties simultaneously.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Precedence in Survey Sampling
</div>
</div>
<div class="callout-body-container callout-body">
<p>The design-consistency result in <span class="quarto-unresolved-ref">?thm-lin</span> — model-agnostic consistency under the randomization distribution — was established in the survey sampling literature decades before <span class="citation" data-cites="lin2013agnostic">Lin (<a href="references.html#ref-lin2013agnostic" role="doc-biblioref">2013</a>)</span>. <span class="citation" data-cites="isaki1982survey">Isaki and Fuller (<a href="references.html#ref-isaki1982survey" role="doc-biblioref">1982</a>)</span> proved this for the generalized regression (GREG) estimator under general probability sampling designs. A CRE is structurally equivalent to simple random sampling from the finite population of potential outcomes, so their result directly implies <span class="quarto-unresolved-ref">?thm-lin</span>. <span class="citation" data-cites="deville1992calibration">Deville and Särndal (<a href="references.html#ref-deville1992calibration" role="doc-biblioref">1992</a>)</span> extended this to calibration estimators. <span class="citation" data-cites="lin2013agnostic">Lin (<a href="references.html#ref-lin2013agnostic" role="doc-biblioref">2013</a>)</span>’s contribution was restating and proving this within the Neyman–Rubin framework for the experimental causal inference audience.</p>
</div>
</div>
</section>
</section>
<section id="sec-stratification" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-stratification"><span class="header-section-number">5.4</span> Stratification</h2>
<p>Stratification (subclassification) is a non-parametric implementation of the back-door formula. Rather than modeling <span class="math inline">\(\E[Y \mid T, X]\)</span>, the analyst divides the sample into <em>strata</em> — subgroups with similar values of <span class="math inline">\(X\)</span> — and estimates the treatment effect within each stratum.</p>
<p>Within stratum <span class="math inline">\(\mathcal{S}_k\)</span>, the treated and control units have similar covariate distributions. If the stratum is narrow enough, ignorability holds approximately, and the within-stratum DIM: <span class="math display">\[\hat\tau_k = \bar Y_{1,k} - \bar Y_{0,k}\]</span> is approximately unbiased for the stratum-specific ATE. The overall ATE is estimated as: <span id="eq-strat"><span class="math display">\[\hat\tau_{\mathrm{STRAT}} = \sum_{k=1}^K \hat\tau_k \cdot \frac{n_k}{n}. \tag{5.11}\]</span></span></p>
<p><span class="citation" data-cites="cochran1968effectiveness">Cochran (<a href="references.html#ref-cochran1968effectiveness" role="doc-biblioref">1968</a>)</span> showed that with <span class="math inline">\(K = 5\)</span> equal-size strata, roughly 90% of the bias from a single continuous confounder is removed; with <span class="math inline">\(K = 10\)</span>, over 95%.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark: Stratification, Standardization, and Survey Sampling Terminology
</div>
</div>
<div class="callout-body-container callout-body">
<p>When <span class="math inline">\(X\)</span> is categorical, the stratified estimator <a href="#eq-strat" class="quarto-xref">Equation&nbsp;<span>5.11</span></a> and the standardization estimator <a href="#eq-std" class="quarto-xref">Equation&nbsp;<span>5.8</span></a> are algebraically identical: both compute within-cell treatment effect estimates and aggregate with marginal weights <span class="math inline">\(n_k/n\)</span>. The names reflect disciplinary tradition.</p>
<p>When <span class="math inline">\(X\)</span> is continuous, stratification estimates <span class="math inline">\(\hat\mu(t,x)\)</span> by a piecewise-constant step function; regression fits a smooth model. In the survey sampling literature, <em>stratification</em> (design-stage: divide before sampling) and <em>post-stratification</em> (analysis-stage: reweight after sampling) are distinct. Standardization in causal inference corresponds to post-stratification.</p>
</div>
</div>
<p><strong>Limitations.</strong> Stratification faces the <em>curse of dimensionality</em>: with <span class="math inline">\(p\)</span> binary covariates, there are <span class="math inline">\(2^p\)</span> cells, many empty in practice. Two solutions: regression adjustment, which imposes parametric structure on <span class="math inline">\(\hat\mu(t,x)\)</span>; and propensity score stratification (Chapter 6), which collapses multivariate <span class="math inline">\(X\)</span> to a scalar <span class="math inline">\(\pi(X) = P(T{=}1 \mid X)\)</span>.</p>
</section>
<section id="sec-simpson" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-simpson"><span class="header-section-number">5.5</span> Simpson’s Paradox</h2>
<p>Simpson’s paradox — the reversal of an association when conditioning on a third variable — was introduced in Chapter 1. This chapter’s development gives it a second layer of interpretation. The back-door formula used in Chapter 1 is precisely the standardization estimator <a href="#eq-std" class="quarto-xref">Equation&nbsp;<span>5.8</span></a>: within-stratum conditional means averaged over the <em>marginal</em> distribution of the confounder rather than its treatment-conditional distribution. The pooled association does not do this — it weights strata by <span class="math inline">\(P(X \mid T)\)</span> instead of <span class="math inline">\(P(X)\)</span>.</p>
<section id="sec-simpson-collider" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="sec-simpson-collider"><span class="header-section-number">5.5.1</span> When Should You <em>Not</em> Condition on <span class="math inline">\(X\)</span>?</h3>
<p>Simpson’s paradox has a mirror image: conditioning can <em>create</em> a spurious association or make a true causal effect disappear. This occurs when <span class="math inline">\(X\)</span> is a mediator or a collider. The back-door criterion gives the correct prescription: include <span class="math inline">\(X\)</span> only if it blocks back-door paths <em>without</em> opening collider paths.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Conditioning on a Mediator or Collider
</div>
</div>
<div class="callout-body-container callout-body">
<p>Adjusting for a post-treatment variable <span class="math inline">\(X\)</span> that lies on a causal pathway <span class="math inline">\(T \to X \to Y\)</span> blocks part of the causal effect, producing a downward-biased estimate of the total effect. Adjusting for a collider <span class="math inline">\(X\)</span> with <span class="math inline">\(T \to X \leftarrow Y\)</span> opens a spurious association that does not exist in the population. Neither mistake is detectable from the data alone; the DAG is essential.</p>
</div>
</div>
</section>
</section>
<section id="sec-lab" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-lab"><span class="header-section-number">5.6</span> Lab: Simulation Study of the Outcome Regression Estimator</h2>
<p>This simulation compares the linear and local-linear OR estimators across two designs and illustrates the bias-variance tradeoff.</p>
<p><strong>Data-generating process.</strong> <span class="math inline">\(X \sim \mathrm{Uniform}(0,1)\)</span>, <span class="math inline">\(\varepsilon \sim \mathcal{N}(0,1)\)</span> independent of <span class="math inline">\(X\)</span>. Potential outcomes: <span id="eq-lab-dgp"><span class="math display">\[Y(t) = t + 3(1+t)X^2 + \varepsilon, \qquad t \in \{0,1\}. \tag{5.12}\]</span></span> The conditional ATE is <span class="math inline">\(\tau(x) = 1 + 3x^2\)</span>, so <span class="math inline">\(\tau_{\mathrm{ATE}} = 1 + 3\E[X^2] = 1 + 1 = 2\)</span>.</p>
<p><strong>Two assignment mechanisms:</strong></p>
<ul>
<li><strong>CRD</strong>: <span class="math inline">\(T \sim \mathrm{Bern}(0.5)\)</span>, independent of <span class="math inline">\(X\)</span>.</li>
<li><strong>Observational</strong>: <span class="math inline">\(T \mid X \sim \mathrm{Bern}(\mathrm{expit}(-2 + 5X))\)</span>, giving <span class="math inline">\(\pi(0) \approx 0.12\)</span>, <span class="math inline">\(\pi(0.5) \approx 0.62\)</span>, <span class="math inline">\(\pi(1) \approx 0.95\)</span>. Strong confounding: high-<span class="math inline">\(X\)</span> units are nearly always treated.</li>
</ul>
<p>Strong ignorability holds in both: under CRD by design; under the observational mechanism because <span class="math inline">\(T\)</span> depends only on <span class="math inline">\(X\)</span> through a known stochastic function, leaving no unmeasured variable affecting both <span class="math inline">\(T\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p><strong>Estimators.</strong> <em>Linear OR</em>: within each arm, fit OLS of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> (misspecified: true conditional mean is quadratic with a <span class="math inline">\(TX^2\)</span> interaction). <em>Local-linear OR</em>: within each arm, fit local linear regression with Gaussian kernel, bandwidth <span class="math inline">\(h = 0.5 \cdot n^{-1/5}\)</span>.</p>
<p><strong>Results</strong> (<span class="math inline">\(n = 1000\)</span>, <span class="math inline">\(B = 2000\)</span> replications, seed 2024):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Design</strong></th>
<th><strong>Estimator</strong></th>
<th><strong>Mean</strong></th>
<th><strong>Bias</strong></th>
<th><strong>SD</strong></th>
<th><strong>RMSE</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CRD</td>
<td>Linear OR</td>
<td>2.0013</td>
<td>+0.0013</td>
<td>0.0679</td>
<td>0.0678</td>
</tr>
<tr class="even">
<td>CRD</td>
<td>Local-linear OR</td>
<td>2.0333</td>
<td>+0.0333</td>
<td>0.0659</td>
<td>0.0738</td>
</tr>
<tr class="odd">
<td>Observational</td>
<td>Linear OR</td>
<td>1.9602</td>
<td>−0.0398</td>
<td>0.0851</td>
<td>0.0939</td>
</tr>
<tr class="even">
<td>Observational</td>
<td>Local-linear OR</td>
<td>2.0240</td>
<td>+0.0240</td>
<td>0.0923</td>
<td>0.0953</td>
</tr>
</tbody>
</table>
<p><strong>Lesson 1: Under CRD, the linear OR is unbiased regardless of model specification.</strong> This confirms <span class="quarto-unresolved-ref">?thm-lin</span>: under complete randomization, the linear OR converges to <span class="math inline">\(\tau_{\mathrm{ATE}}\)</span> even with a wrong outcome model. The randomization distribution, not the model, does the identification work.</p>
<p><strong>Lesson 2: Under an observational design, the misspecified linear OR is biased.</strong> The bias grows from <span class="math inline">\(+0.0013\)</span> under CRD to <span class="math inline">\(-0.0398\)</span> under the observational design. The omitted <span class="math inline">\(X^2\)</span> and <span class="math inline">\(TX^2\)</span> terms cause <span class="math inline">\(\hat\mu(t,x)\)</span> to misrepresent the outcome surface; because high-<span class="math inline">\(X\)</span> units are predominantly treated, the misfit is systematically amplified in the direction of confounding. Under CRD, the balanced assignment averages out the same misfit.</p>
<p><strong>Lesson 3: The local-linear OR nearly eliminates bias at the cost of higher variance.</strong> Under the observational design, local-linear OR reduces bias from <span class="math inline">\(-0.0398\)</span> to <span class="math inline">\(+0.0240\)</span> but its SD is 0.0923 vs.&nbsp;0.0851 for the linear model. The RMSE comparison (0.0939 vs.&nbsp;0.0953) favors the linear estimator in MSE, even though it is biased — the classic bias-variance tradeoff.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Model Misspecification and Confounding Interact
</div>
</div>
<div class="callout-body-container callout-body">
<p>The linear OR bias is <span class="math inline">\(+0.0013\)</span> under CRD and <span class="math inline">\(-0.0398\)</span> under the observational design. The misspecification is identical in both cases — the difference comes entirely from the assignment mechanism. Under CRD, <span class="math inline">\(T \indep X\)</span>, so <span class="math inline">\(X\)</span> within each arm is <span class="math inline">\(\mathrm{Uniform}(0,1)\)</span>. The population OLS pointwise error <span class="math inline">\(b(x) = -\tfrac{1}{2} + 3x - 3x^2\)</span> integrates to exactly zero over <span class="math inline">\(U(0,1)\)</span>: <span class="math inline">\(\E[b(X)] = \int_0^1 (-\tfrac{1}{2}+3x-3x^2)\, dx = 0\)</span>. This cancellation is structural: the population OLS line is the linear projection of <span class="math inline">\(\tau(X)\)</span> onto <span class="math inline">\(\{1, X\}\)</span> under <span class="math inline">\(U(0,1)\)</span>, and a linear projection always preserves the mean. Under the observational design, the within-arm distributions of <span class="math inline">\(X\)</span> are distorted by the propensity score, so the same cancellation fails.</p>
</div>
</div>
</section>
<section id="chapter-summary" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">5.7</span> Chapter Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Estimand</strong></th>
<th><strong>Identification</strong></th>
<th><strong>Key assumption</strong></th>
<th><strong>Method</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ATE under CRD</td>
<td><span class="math inline">\(\E[Y(t)] = \E[Y \mid T{=}t]\)</span></td>
<td>Randomization protocol</td>
<td>DIM, regression-adjusted DIM</td>
</tr>
<tr class="even">
<td>ATE under observability</td>
<td><a href="#eq-backdoor" class="quarto-xref">Equation&nbsp;<span>5.5</span></a></td>
<td>Ignorability + overlap</td>
<td>OR, standardization, stratification</td>
</tr>
<tr class="odd">
<td>ATT</td>
<td><a href="#eq-backdoor-att" class="quarto-xref">Equation&nbsp;<span>5.6</span></a></td>
<td>Same, one-sided overlap for <span class="math inline">\(t=0\)</span></td>
<td>Same methods, weighted over treated</td>
</tr>
<tr class="even">
<td>Propensity score (Ch. 6)</td>
<td>Reduces <span class="math inline">\(X\)</span> to scalar <span class="math inline">\(\pi(X)\)</span></td>
<td>Correctly specified PS model</td>
<td>IPW, matching, PS stratification</td>
</tr>
</tbody>
</table>
<ol type="1">
<li><strong>Randomization as graph surgery.</strong> A randomized experiment removes all arrows into <span class="math inline">\(T\)</span>, so <span class="math inline">\(f(y \mid \doop(T{=}t)) = f(y \mid T{=}t)\)</span> and DIM is unbiased for the ATE without covariate adjustment.</li>
<li><strong>Ignorability is the key assumption.</strong> Under unconfoundedness <span class="math inline">\((Y(0),Y(1)) \indep T \mid X\)</span>, the back-door adjustment formula <a href="#eq-backdoor" class="quarto-xref">Equation&nbsp;<span>5.5</span></a> identifies the ATE. This assumption is substantive, design-determined in RCTs, and untestable from observational data.</li>
<li><strong>Three estimation strategies.</strong> Regression adjustment (G-formula), standardization, and stratification all implement <a href="#eq-backdoor" class="quarto-xref">Equation&nbsp;<span>5.5</span></a> via different modeling choices. Under a randomized experiment, regression adjustment is design-consistent for the ATE even when the outcome model is misspecified (<span class="quarto-unresolved-ref">?thm-lin</span>); in observational studies, it is consistent only when the outcome model is.</li>
<li><strong>Simpson’s paradox.</strong> Pooled associations can reverse within subgroups when a confounder determines treatment selection. The correct causal estimate requires standardization over the <em>marginal</em> covariate distribution, guided by the back-door criterion.</li>
<li><strong>The propensity score dimension reduction.</strong> When <span class="math inline">\(X\)</span> is high-dimensional, direct stratification or cell-by-cell standardization breaks down. The propensity score <span class="math inline">\(\pi(X)\)</span> provides a scalar sufficient statistic for adjustment. Chapter 6 develops the theory and estimation methods.</li>
</ol>
</section>
<section id="problems" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="problems"><span class="header-section-number">5.8</span> Problems</h2>
<p><strong>1. Randomization and the do-calculus.</strong> Let the observational DAG be <span class="math inline">\(\{U \to T, U \to Y, X \to T, T \to Y\}\)</span> with <span class="math inline">\(U\)</span> unobserved.</p>
<ol type="a">
<li>Identify all back-door paths from <span class="math inline">\(T\)</span> to <span class="math inline">\(Y\)</span>.</li>
<li>Does <span class="math inline">\(X\)</span> satisfy the back-door criterion? Does <span class="math inline">\(U\)</span>? Explain.</li>
<li>Now suppose treatment is randomized. Draw the modified DAG and identify all back-door paths. Show that <span class="math inline">\(f(y \mid \doop(T{=}t)) = f(y \mid T{=}t)\)</span> holds using Rule 2 of the do-calculus. (<em>Hint</em>: identify the appropriate <span class="math inline">\((X, Z, W)\)</span> instantiation, construct <span class="math inline">\(\mathcal{G}_{\underline{T}}\)</span>, and verify <span class="math inline">\((Y \indep T)_{\mathcal{G}_{\underline{T}}}\)</span>.)</li>
<li>Under randomization, is covariate adjustment on <span class="math inline">\(X\)</span> necessary for unbiasedness? Is it ever beneficial? Explain.</li>
</ol>
<p><strong>2. Ignorability and the back-door criterion.</strong> Consider the DAG <span class="math inline">\(\{X \to T, X \to Y, T \to Y, U \to Y\}\)</span> with <span class="math inline">\(U\)</span> unobserved.</p>
<ol type="a">
<li>Does <span class="math inline">\(\{X\}\)</span> satisfy the back-door criterion? Write out the identifying formula for <span class="math inline">\(\tau_{\mathrm{ATE}}\)</span>.</li>
<li>Now add the edge <span class="math inline">\(U \to T\)</span> to the DAG. Does <span class="math inline">\(\{X\}\)</span> still satisfy the back-door criterion? What does the criterion require when both <span class="math inline">\(X\)</span> and <span class="math inline">\(U\)</span> affect <span class="math inline">\(T\)</span>?</li>
<li>Explain in words what “unconfoundedness given <span class="math inline">\(X\)</span>” means about the role of <span class="math inline">\(U\)</span> in the data-generating process.</li>
</ol>
<p><strong>3. Standardization.</strong> A study of job training (<span class="math inline">\(T\)</span>) and earnings (<span class="math inline">\(Y\)</span>, in thousands) produces the following cell means, with <span class="math inline">\(P(X{=}0) = 0.4\)</span> and <span class="math inline">\(P(X{=}1) = 0.6\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(X\)</span></th>
<th><span class="math inline">\(\hat\mu(1,x)\)</span></th>
<th><span class="math inline">\(\hat\mu(0,x)\)</span></th>
<th><span class="math inline">\(n_x/n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>28</td>
<td>22</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>1</td>
<td>35</td>
<td>31</td>
<td>0.6</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Compute <span class="math inline">\(\hat\tau_{\mathrm{ATE}}\)</span> using the standardization formula <a href="#eq-std" class="quarto-xref">Equation&nbsp;<span>5.8</span></a>.</li>
<li>Compute <span class="math inline">\(\hat\tau_{\mathrm{ATT}}\)</span>, given that all treated units come from <span class="math inline">\(X{=}1\)</span> — i.e., <span class="math inline">\(P(X{=}1 \mid T{=}1) = 1\)</span>.</li>
<li>The unadjusted difference in means is <span class="math inline">\(33 - 25 = 8\)</span>. Compare to your answers in (a) and (b) and explain the discrepancy.</li>
</ol>
<p><strong>4. Stratification and Cochran’s rule.</strong> You have a binary confounder <span class="math inline">\(X \in \{0,1\}\)</span> and form two strata. Within stratum <span class="math inline">\(X{=}0\)</span>: <span class="math inline">\(n_0 = 600\)</span>, <span class="math inline">\(\bar Y_1 = 10\)</span>, <span class="math inline">\(\bar Y_0 = 8\)</span>. Within stratum <span class="math inline">\(X{=}1\)</span>: <span class="math inline">\(n_1 = 400\)</span>, <span class="math inline">\(\bar Y_1 = 15\)</span>, <span class="math inline">\(\bar Y_0 = 12\)</span>.</p>
<ol type="a">
<li>Compute the stratified ATE estimator <span class="math inline">\(\hat\tau_{\mathrm{STRAT}}\)</span> via <a href="#eq-strat" class="quarto-xref">Equation&nbsp;<span>5.11</span></a>.</li>
<li>Suppose an unadjusted DIM gives <span class="math inline">\(\hat\tau_{\mathrm{DIM}} = 5.5\)</span>. Explain why the two estimates differ and which is the appropriate causal estimate.</li>
<li>Describe one limitation that would arise if <span class="math inline">\(X\)</span> were a continuous variable with 15 dimensions.</li>
</ol>
<p><strong>5. Simpson’s paradox.</strong> A hospital reports that ICU patients (<span class="math inline">\(T{=}1\)</span>) have higher mortality than others (<span class="math inline">\(T{=}0\)</span>): <span class="math inline">\(P(Y{=}1 \mid T{=}1) = 0.30\)</span> vs.&nbsp;<span class="math inline">\(P(Y{=}1 \mid T{=}0) = 0.10\)</span>.</p>
<ol type="a">
<li>Construct a numerical example (a <span class="math inline">\(2 \times 2 \times 2\)</span> table with disease severity <span class="math inline">\(X\)</span> as the confounder) consistent with the pooled numbers yet showing ICU admission <em>reduces</em> mortality within both severity strata.</li>
<li>Compute the standardized ATE using the marginal distribution of <span class="math inline">\(X\)</span>.</li>
<li>Draw the DAG. Identify the back-door path that the pooled comparison fails to block.</li>
<li>A colleague argues the pooled statistic is the right answer since the hospital treats patients with both mild and severe illness. Explain, using potential outcomes notation, why this argument is incorrect.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-cochran1968effectiveness" class="csl-entry" role="listitem">
Cochran, William G. 1968. <span>“The Effectiveness of Adjustment by Subclassification in Removing Bias in Observational Studies.”</span> <em>Biometrics</em> 24 (2): 295–313. <a href="https://doi.org/10.2307/2528036">https://doi.org/10.2307/2528036</a>.
</div>
<div id="ref-deville1992calibration" class="csl-entry" role="listitem">
Deville, Jean-Claude, and Carl-Erik Särndal. 1992. <span>“Calibration Estimators in Survey Sampling.”</span> <em>Journal of the American Statistical Association</em> 87 (418): 376–82.
</div>
<div id="ref-ding2023first" class="csl-entry" role="listitem">
Ding, Peng. 2024. <em>A First Course in Causal Inference</em>. CRC Press.
</div>
<div id="ref-ding2016randomization" class="csl-entry" role="listitem">
Ding, Peng, Avi Feller, and Luke Miratrix. 2016. <span>“Randomization Inference for Treatment Effect Variation.”</span> <em>Journal of the Royal Statistical Society: Series B</em> 78 (3): 655–71.
</div>
<div id="ref-isaki1982survey" class="csl-entry" role="listitem">
Isaki, Cary T., and Wayne A. Fuller. 1982. <span>“Survey Design Under the Regression Superpopulation Model.”</span> <em>Journal of the American Statistical Association</em> 77 (377): 89–96.
</div>
<div id="ref-li2017general" class="csl-entry" role="listitem">
Li, Xinran, and Peng Ding. 2017. <span>“General Forms of Finite Population Central Limit Theorems with Applications to Causal Inference.”</span> <em>Journal of the American Statistical Association</em> 112 (520): 1759–69.
</div>
<div id="ref-lin2013agnostic" class="csl-entry" role="listitem">
Lin, Winston. 2013. <span>“Agnostic Notes on Regression Adjustments to Experimental Data: Reexamining <span>Freedman</span>’s Critique.”</span> <em>The Annals of Applied Statistics</em> 7 (1): 295–318.
</div>
<div id="ref-robins1986new" class="csl-entry" role="listitem">
Robins, James M. 1986. <span>“A New Approach to Causal Inference in Mortality Studies with a Sustained Exposure Period—Application to Control of the Healthy Worker Survivor Effect.”</span> <em>Mathematical Modelling</em> 7 (9–12): 1393–512.
</div>
<div id="ref-rosenbaum2002observational" class="csl-entry" role="listitem">
Rosenbaum, Paul R. 2002. <em>Observational Studies</em>. 2nd ed. Springer. <a href="https://doi.org/10.1007/978-1-4757-3692-2">https://doi.org/10.1007/978-1-4757-3692-2</a>.
</div>
<div id="ref-rosenbaum1983central" class="csl-entry" role="listitem">
Rosenbaum, Paul R., and Donald B. Rubin. 1983. <span>“The Central Role of the Propensity Score in Observational Studies for Causal Effects.”</span> <em>Biometrika</em> 70 (1): 41–55.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_04.html" class="pagination-link" aria-label="Potential Outcomes and Adjustment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Potential Outcomes and Adjustment</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_06.html" class="pagination-link" aria-label="Propensity Score Methods">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Propensity Score Methods</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>